/**
 * Couche A (5e) — 30 contextes narratifs pour la famille "Club de loisirs" (5gen23). Un seul est
 * tiré uniformément à chaque génération (`clubLoisirs.ts`). `grandeurArticle` est TOUJOURS masculin
 * par construction ("l'effectif"/"le nombre de X"/"le chiffre d'affaires") pour éviter tout calcul
 * d'accord grammatical à l'exécution — voir `core5e/limitesContexte.types.ts` pour le contrat.
 */
import type { ContexteClubLoisirs } from "../../core5e/limitesContexte.types";

export const CONTEXTES_CLUB_LOISIRS: ContexteClubLoisirs[] = [
  {
    id: "club-loisirs",
    entiteDescription: "L'effectif d'un club de loisirs",
    parentheseUnite: "centaines de membres",
    unitePluriel: "membres",
    origine: "la création du club",
    grandeurLabel: "Effectif",
    grandeurArticle: "l'effectif",
  },
  {
    id: "youtube",
    entiteDescription: "Le nombre d'abonnés d'une chaîne YouTube",
    parentheseUnite: "centaines d'abonnés",
    unitePluriel: "abonnés",
    origine: "le lancement de la chaîne",
    grandeurLabel: "Nombre d'abonnés",
    grandeurArticle: "le nombre d'abonnés",
  },
  {
    id: "appli-mobile",
    entiteDescription: "Le nombre d'utilisateurs actifs d'une application mobile",
    parentheseUnite: "centaines d'utilisateurs",
    unitePluriel: "utilisateurs",
    origine: "le lancement de l'application",
    grandeurLabel: "Nombre d'utilisateurs",
    grandeurArticle: "le nombre d'utilisateurs",
  },
  {
    id: "salle-sport",
    entiteDescription: "Le nombre d'adhérents d'une salle de sport",
    parentheseUnite: "centaines d'adhérents",
    unitePluriel: "adhérents",
    origine: "l'ouverture de la salle",
    grandeurLabel: "Nombre d'adhérents",
    grandeurArticle: "le nombre d'adhérents",
  },
  {
    id: "reseau-social",
    entiteDescription: "Le nombre de followers d'un compte de réseau social",
    parentheseUnite: "centaines de followers",
    unitePluriel: "followers",
    origine: "la création du compte",
    grandeurLabel: "Nombre de followers",
    grandeurArticle: "le nombre de followers",
  },
  {
    id: "chiffre-affaires",
    entiteDescription: "Le chiffre d'affaires mensuel d'une petite entreprise",
    parentheseUnite: "centaines d'euros",
    unitePluriel: "euros",
    origine: "la création de l'entreprise",
    grandeurLabel: "Chiffre d'affaires",
    grandeurArticle: "le chiffre d'affaires",
  },
  {
    id: "site-web",
    entiteDescription: "Le nombre de visiteurs d'un site web",
    parentheseUnite: "centaines de visiteurs",
    unitePluriel: "visiteurs",
    origine: "la mise en ligne du site",
    grandeurLabel: "Nombre de visiteurs",
    grandeurArticle: "le nombre de visiteurs",
  },
  {
    id: "ecole-musique",
    entiteDescription: "Le nombre d'élèves d'une école de musique",
    parentheseUnite: "centaines d'élèves",
    unitePluriel: "élèves",
    origine: "l'ouverture de l'école",
    grandeurLabel: "Nombre d'élèves",
    grandeurArticle: "le nombre d'élèves",
  },
  {
    id: "livraison-repas",
    entiteDescription: "Le nombre de clients d'un service de livraison de repas",
    parentheseUnite: "centaines de clients",
    unitePluriel: "clients",
    origine: "le lancement du service",
    grandeurLabel: "Nombre de clients",
    grandeurArticle: "le nombre de clients",
  },
  {
    id: "bibliotheque",
    entiteDescription: "Le nombre de membres d'une bibliothèque municipale",
    parentheseUnite: "centaines de membres",
    unitePluriel: "membres",
    origine: "l'ouverture de la bibliothèque",
    grandeurLabel: "Nombre de membres",
    grandeurArticle: "le nombre de membres",
  },
  {
    id: "marathon",
    entiteDescription: "Le nombre de participants à un marathon annuel",
    parentheseUnite: "centaines de participants",
    unitePluriel: "participants",
    origine: "la première édition du marathon",
    grandeurLabel: "Nombre de participants",
    grandeurArticle: "le nombre de participants",
  },
  {
    id: "mutuelle",
    entiteDescription: "Le nombre d'adhérents d'une mutuelle",
    parentheseUnite: "centaines d'adhérents",
    unitePluriel: "adhérents",
    origine: "la création de la mutuelle",
    grandeurLabel: "Nombre d'adhérents",
    grandeurArticle: "le nombre d'adhérents",
  },
  {
    id: "telechargements",
    entiteDescription: "Le nombre de téléchargements d'une application",
    parentheseUnite: "centaines de téléchargements",
    unitePluriel: "téléchargements",
    origine: "la sortie de l'application",
    grandeurLabel: "Nombre de téléchargements",
    grandeurArticle: "le nombre de téléchargements",
  },
  {
    id: "festival",
    entiteDescription: "Le nombre de spectateurs d'un festival annuel",
    parentheseUnite: "centaines de spectateurs",
    unitePluriel: "spectateurs",
    origine: "la première édition du festival",
    grandeurLabel: "Nombre de spectateurs",
    grandeurArticle: "le nombre de spectateurs",
  },
  {
    id: "association-caritative",
    entiteDescription: "Le nombre de bénévoles d'une association caritative",
    parentheseUnite: "centaines de bénévoles",
    unitePluriel: "bénévoles",
    origine: "la création de l'association",
    grandeurLabel: "Nombre de bénévoles",
    grandeurArticle: "le nombre de bénévoles",
  },
  {
    id: "salon-coiffure",
    entiteDescription: "Le nombre de clients d'un salon de coiffure",
    parentheseUnite: "centaines de clients",
    unitePluriel: "clients",
    origine: "l'ouverture du salon",
    grandeurLabel: "Nombre de clients",
    grandeurArticle: "le nombre de clients",
  },
  {
    id: "club-echecs",
    entiteDescription: "Le nombre d'élèves d'un club d'échecs scolaire",
    parentheseUnite: "centaines d'élèves",
    unitePluriel: "élèves",
    origine: "la création du club",
    grandeurLabel: "Nombre d'élèves",
    grandeurArticle: "le nombre d'élèves",
  },
  {
    id: "magazine",
    entiteDescription: "Le nombre d'abonnés à un magazine",
    parentheseUnite: "centaines d'abonnés",
    unitePluriel: "abonnés",
    origine: "le lancement du magazine",
    grandeurLabel: "Nombre d'abonnés",
    grandeurArticle: "le nombre d'abonnés",
  },
  {
    id: "parc-location",
    entiteDescription: "Le nombre de véhicules d'un parc de location",
    parentheseUnite: "centaines de véhicules",
    unitePluriel: "véhicules",
    origine: "la création du parc",
    grandeurLabel: "Nombre de véhicules",
    grandeurArticle: "le nombre de véhicules",
  },
  {
    id: "cabinet-medical",
    entiteDescription: "Le nombre de patients d'un cabinet médical",
    parentheseUnite: "centaines de patients",
    unitePluriel: "patients",
    origine: "l'ouverture du cabinet",
    grandeurLabel: "Nombre de patients",
    grandeurArticle: "le nombre de patients",
  },
  {
    id: "boutique-en-ligne",
    entiteDescription: "Le nombre d'achats d'une boutique en ligne",
    parentheseUnite: "centaines d'achats",
    unitePluriel: "achats",
    origine: "l'ouverture de la boutique",
    grandeurLabel: "Nombre d'achats",
    grandeurArticle: "le nombre d'achats",
  },
  {
    id: "chorale",
    entiteDescription: "Le nombre de membres d'une chorale",
    parentheseUnite: "centaines de membres",
    unitePluriel: "membres",
    origine: "la création de la chorale",
    grandeurLabel: "Nombre de membres",
    grandeurArticle: "le nombre de membres",
  },
  {
    id: "parking-covoiturage",
    entiteDescription: "Le nombre d'utilisateurs d'un parking de covoiturage",
    parentheseUnite: "centaines d'utilisateurs",
    unitePluriel: "utilisateurs",
    origine: "l'ouverture du parking",
    grandeurLabel: "Nombre d'utilisateurs",
    grandeurArticle: "le nombre d'utilisateurs",
  },
  {
    id: "newsletter",
    entiteDescription: "Le nombre d'inscrits à une newsletter",
    parentheseUnite: "centaines d'inscrits",
    unitePluriel: "inscrits",
    origine: "le lancement de la newsletter",
    grandeurLabel: "Nombre d'inscrits",
    grandeurArticle: "le nombre d'inscrits",
  },
  {
    id: "club-football",
    entiteDescription: "Le nombre de licenciés d'un club de football",
    parentheseUnite: "centaines de licenciés",
    unitePluriel: "licenciés",
    origine: "la création du club",
    grandeurLabel: "Nombre de licenciés",
    grandeurArticle: "le nombre de licenciés",
  },
  {
    id: "musee",
    entiteDescription: "Le nombre de visiteurs d'un musée",
    parentheseUnite: "centaines de visiteurs",
    unitePluriel: "visiteurs",
    origine: "l'ouverture du musée",
    grandeurLabel: "Nombre de visiteurs",
    grandeurArticle: "le nombre de visiteurs",
  },
  {
    id: "cafe-quartier",
    entiteDescription: "Le nombre de clients fidèles d'un café de quartier",
    parentheseUnite: "centaines de clients",
    unitePluriel: "clients",
    origine: "l'ouverture du café",
    grandeurLabel: "Nombre de clients",
    grandeurArticle: "le nombre de clients",
  },
  {
    id: "plateforme-covoiturage",
    entiteDescription: "Le nombre d'adhérents d'une plateforme de covoiturage",
    parentheseUnite: "centaines d'adhérents",
    unitePluriel: "adhérents",
    origine: "le lancement de la plateforme",
    grandeurLabel: "Nombre d'adhérents",
    grandeurArticle: "le nombre d'adhérents",
  },
  {
    id: "club-lecture",
    entiteDescription: "Le nombre de membres d'un club de lecture",
    parentheseUnite: "centaines de membres",
    unitePluriel: "membres",
    origine: "la création du club",
    grandeurLabel: "Nombre de membres",
    grandeurArticle: "le nombre de membres",
  },
  {
    id: "velos-libre-service",
    entiteDescription: "Le nombre d'utilisateurs d'un service de vélos en libre-service",
    parentheseUnite: "centaines d'utilisateurs",
    unitePluriel: "utilisateurs",
    origine: "le lancement du service",
    grandeurLabel: "Nombre d'utilisateurs",
    grandeurArticle: "le nombre d'utilisateurs",
  },
];
