/**
 * Couche A (5e) — 30 contextes narratifs pour la famille "Prix de revient" (5gen23). Un seul est
 * tiré uniformément à chaque génération (`prixRevient.ts`). Champs pré-écrits, jamais de calcul
 * d'accord grammatical à l'exécution — voir `core5e/limitesContexte.types.ts` pour le contrat.
 */
import type { ContextePrixRevient } from "../../core5e/limitesContexte.types";

export const CONTEXTES_PRIX_REVIENT: ContextePrixRevient[] = [
  {
    id: "brochures",
    sujetPhrase: "Une imprimerie",
    sujetGenerique: "l'imprimerie",
    activiteFixe: "la mise en page",
    uniteSingulier: "brochure",
    unitePluriel: "brochures",
    verbeParticipePluriel: "commandées",
    verbeInfinitif: "imprimer",
  },
  {
    id: "gateaux",
    sujetPhrase: "Une pâtisserie",
    sujetGenerique: "la pâtisserie",
    activiteFixe: "la préparation du matériel",
    uniteSingulier: "gâteau",
    unitePluriel: "gâteaux",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "confectionner",
  },
  {
    id: "tshirts",
    sujetPhrase: "Un atelier de sérigraphie",
    sujetGenerique: "l'atelier",
    activiteFixe: "la création du gabarit d'impression",
    uniteSingulier: "t-shirt",
    unitePluriel: "t-shirts",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "location-salle",
    sujetPhrase: "Une agence événementielle",
    sujetGenerique: "l'agence",
    activiteFixe: "la location de la salle",
    uniteSingulier: "invité",
    unitePluriel: "invités",
    verbeParticipePluriel: "accueillis",
    verbeInfinitif: "accueillir",
  },
  {
    id: "bougies",
    sujetPhrase: "Un atelier de bougies artisanales",
    sujetGenerique: "l'atelier",
    activiteFixe: "la préparation des moules",
    uniteSingulier: "bougie",
    unitePluriel: "bougies",
    verbeParticipePluriel: "commandées",
    verbeInfinitif: "couler",
  },
  {
    id: "voyage-autocar",
    sujetPhrase: "Une école",
    sujetGenerique: "l'école",
    activiteFixe: "la réservation de l'autocar",
    uniteSingulier: "élève",
    unitePluriel: "élèves",
    verbeParticipePluriel: "inscrits",
    verbeInfinitif: "inscrire",
  },
  {
    id: "badges-festival",
    sujetPhrase: "Un festival",
    sujetGenerique: "le festival",
    activiteFixe: "la création des gabarits",
    uniteSingulier: "badge",
    unitePluriel: "badges",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "produire",
  },
  {
    id: "calendriers",
    sujetPhrase: "Une boutique de calendriers personnalisés",
    sujetGenerique: "la boutique",
    activiteFixe: "la mise en page",
    uniteSingulier: "calendrier",
    unitePluriel: "calendriers",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "savons",
    sujetPhrase: "Un atelier de savonnerie",
    sujetGenerique: "l'atelier",
    activiteFixe: "la préparation des moules",
    uniteSingulier: "savon",
    unitePluriel: "savons",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "couler",
  },
  {
    id: "mugs",
    sujetPhrase: "Une boutique de mugs personnalisés",
    sujetGenerique: "la boutique",
    activiteFixe: "le réglage de la machine à sublimation",
    uniteSingulier: "mug",
    unitePluriel: "mugs",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "confitures",
    sujetPhrase: "Une conserverie artisanale",
    sujetGenerique: "la conserverie",
    activiteFixe: "la stérilisation des bocaux",
    uniteSingulier: "pot",
    unitePluriel: "pots",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "préparer",
  },
  {
    id: "cartes-visite",
    sujetPhrase: "Une imprimerie",
    sujetGenerique: "l'imprimerie",
    activiteFixe: "la mise en page",
    uniteSingulier: "carte de visite",
    unitePluriel: "cartes de visite",
    verbeParticipePluriel: "commandées",
    verbeInfinitif: "imprimer",
  },
  {
    id: "colliers",
    sujetPhrase: "Un atelier de bijouterie",
    sujetGenerique: "l'atelier",
    activiteFixe: "la préparation des fournitures",
    uniteSingulier: "collier",
    unitePluriel: "colliers",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "confectionner",
  },
  {
    id: "cours-particuliers",
    sujetPhrase: "Un organisme de soutien scolaire",
    sujetGenerique: "l'organisme",
    activiteFixe: "la préparation du cours",
    uniteSingulier: "élève",
    unitePluriel: "élèves",
    verbeParticipePluriel: "inscrits",
    verbeInfinitif: "inscrire",
  },
  {
    id: "videos-pub",
    sujetPhrase: "Une agence de production vidéo",
    sujetGenerique: "l'agence",
    activiteFixe: "le repérage et le scénario",
    uniteSingulier: "vidéo",
    unitePluriel: "vidéos",
    verbeParticipePluriel: "commandées",
    verbeInfinitif: "produire",
  },
  {
    id: "pique-nique",
    sujetPhrase: "Un traiteur",
    sujetGenerique: "le traiteur",
    activiteFixe: "la préparation du matériel",
    uniteSingulier: "convive",
    unitePluriel: "convives",
    verbeParticipePluriel: "accueillis",
    verbeInfinitif: "accueillir",
  },
  {
    id: "meubles-bois",
    sujetPhrase: "Un atelier de menuiserie",
    sujetGenerique: "l'atelier",
    activiteFixe: "le réglage des machines",
    uniteSingulier: "meuble",
    unitePluriel: "meubles",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "fabriquer",
  },
  {
    id: "puzzles",
    sujetPhrase: "Une boutique de puzzles personnalisés",
    sujetGenerique: "la boutique",
    activiteFixe: "la préparation du visuel",
    uniteSingulier: "puzzle",
    unitePluriel: "puzzles",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "produire",
  },
  {
    id: "poterie",
    sujetPhrase: "Un atelier de poterie",
    sujetGenerique: "l'atelier",
    activiteFixe: "la préparation de l'argile et du four",
    uniteSingulier: "participant",
    unitePluriel: "participants",
    verbeParticipePluriel: "inscrits",
    verbeInfinitif: "inscrire",
  },
  {
    id: "sacs-tissu",
    sujetPhrase: "Un atelier textile",
    sujetGenerique: "l'atelier",
    activiteFixe: "la création du patron",
    uniteSingulier: "sac",
    unitePluriel: "sacs",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "coudre",
  },
  {
    id: "posters",
    sujetPhrase: "Une imprimerie",
    sujetGenerique: "l'imprimerie",
    activiteFixe: "la mise en page",
    uniteSingulier: "poster",
    unitePluriel: "posters",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "bijoux-resine",
    sujetPhrase: "Un atelier de bijoux en résine",
    sujetGenerique: "l'atelier",
    activiteFixe: "la préparation des moules",
    uniteSingulier: "bijou",
    unitePluriel: "bijoux",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "couler",
  },
  {
    id: "jeu-societe",
    sujetPhrase: "Un éditeur de jeux de société",
    sujetGenerique: "l'éditeur",
    activiteFixe: "la conception du prototype",
    uniteSingulier: "exemplaire",
    unitePluriel: "exemplaires",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "chandelles",
    sujetPhrase: "Un atelier de chandelles parfumées",
    sujetGenerique: "l'atelier",
    activiteFixe: "la préparation des moules",
    uniteSingulier: "chandelle",
    unitePluriel: "chandelles",
    verbeParticipePluriel: "commandées",
    verbeInfinitif: "couler",
  },
  {
    id: "flyers",
    sujetPhrase: "Une imprimerie",
    sujetGenerique: "l'imprimerie",
    activiteFixe: "la mise en page",
    uniteSingulier: "flyer",
    unitePluriel: "flyers",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "cuisine-collective",
    sujetPhrase: "Une école de cuisine",
    sujetGenerique: "l'école de cuisine",
    activiteFixe: "la préparation des ingrédients",
    uniteSingulier: "participant",
    unitePluriel: "participants",
    verbeParticipePluriel: "inscrits",
    verbeInfinitif: "inscrire",
  },
  {
    id: "tote-bags",
    sujetPhrase: "Une boutique de tote bags imprimés",
    sujetGenerique: "la boutique",
    activiteFixe: "la création du visuel",
    uniteSingulier: "tote bag",
    unitePluriel: "tote bags",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "stickers",
    sujetPhrase: "Une boutique de stickers personnalisés",
    sujetGenerique: "la boutique",
    activiteFixe: "la découpe du gabarit",
    uniteSingulier: "sticker",
    unitePluriel: "stickers",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "faire-part",
    sujetPhrase: "Une imprimerie",
    sujetGenerique: "l'imprimerie",
    activiteFixe: "la mise en page",
    uniteSingulier: "faire-part",
    unitePluriel: "faire-part",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
  {
    id: "etuis-telephone",
    sujetPhrase: "Une boutique d'étuis personnalisés",
    sujetGenerique: "la boutique",
    activiteFixe: "la préparation du visuel",
    uniteSingulier: "étui",
    unitePluriel: "étuis",
    verbeParticipePluriel: "commandés",
    verbeInfinitif: "imprimer",
  },
];
