/**
 * Couche A (5e) — 30 contextes narratifs pour la famille "Population" (5gen23). Un seul est tiré
 * uniformément à chaque génération (`population.ts`). Certains contextes sont des taux (%) plutôt
 * que des effectifs — mathématiquement indifférent (b/seuil restent de simples nombres comparés),
 * seul l'habillage change. Champs pré-écrits, jamais de calcul d'accord grammatical à l'exécution —
 * voir `core5e/limitesContexte.types.ts` pour le contrat.
 */
import type { ContextePopulation } from "../../core5e/limitesContexte.types";

export const CONTEXTES_POPULATION: ContextePopulation[] = [
  {
    id: "population-pays",
    entiteDescription: "La population d'un pays",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en millions d'habitants",
    unitePourValeur: "millions d'habitants",
  },
  {
    id: "espece-protegee",
    entiteDescription: "L'effectif d'une espèce protégée dans une réserve naturelle",
    grandeurLabel: "Effectif",
    grandeurArticle: "l'effectif",
    uniteParenthese: "en milliers d'individus",
    unitePourValeur: "milliers d'individus",
  },
  {
    id: "part-marche",
    entiteDescription: "La part de marché d'une entreprise",
    grandeurLabel: "Part de marché",
    grandeurArticle: "la part de marché",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "taux-adoption",
    entiteDescription: "Le taux d'adoption d'une nouvelle technologie",
    grandeurLabel: "Taux d'adoption",
    grandeurArticle: "le taux d'adoption",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "population-ville-stabilisation",
    entiteDescription: "La population d'une ville en stabilisation",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en millions d'habitants",
    unitePourValeur: "millions d'habitants",
  },
  {
    id: "arbres-foret",
    entiteDescription: "Le nombre d'arbres dans une forêt gérée durablement",
    grandeurLabel: "Nombre d'arbres",
    grandeurArticle: "le nombre d'arbres",
    uniteParenthese: "en milliers d'arbres",
    unitePourValeur: "milliers d'arbres",
  },
  {
    id: "poissons-lac",
    entiteDescription: "La population de poissons dans un lac protégé",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en milliers d'individus",
    unitePourValeur: "milliers d'individus",
  },
  {
    id: "couverture-vaccinale",
    entiteDescription: "La couverture vaccinale d'une population",
    grandeurLabel: "Couverture vaccinale",
    grandeurArticle: "la couverture vaccinale",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "colonie-oiseaux",
    entiteDescription: "L'effectif d'une colonie d'oiseaux protégée",
    grandeurLabel: "Effectif",
    grandeurArticle: "l'effectif",
    uniteParenthese: "en milliers d'individus",
    unitePourValeur: "milliers d'individus",
  },
  {
    id: "foyers-internet",
    entiteDescription: "Le nombre de foyers équipés d'internet haut débit",
    grandeurLabel: "Nombre de foyers",
    grandeurArticle: "le nombre de foyers",
    uniteParenthese: "en milliers de foyers",
    unitePourValeur: "milliers de foyers",
  },
  {
    id: "rucher",
    entiteDescription: "Le nombre de ruches d'un rucher en expansion contrôlée",
    grandeurLabel: "Nombre de ruches",
    grandeurArticle: "le nombre de ruches",
    uniteParenthese: "en centaines de ruches",
    unitePourValeur: "centaines de ruches",
  },
  {
    id: "alphabetisation",
    entiteDescription: "Le taux d'alphabétisation d'une région",
    grandeurLabel: "Taux d'alphabétisation",
    grandeurArticle: "le taux d'alphabétisation",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "population-loups",
    entiteDescription: "La population de loups dans une réserve",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en dizaines d'individus",
    unitePourValeur: "dizaines d'individus",
  },
  {
    id: "vehicules-electriques",
    entiteDescription: "Le nombre de véhicules électriques dans un parc automobile",
    grandeurLabel: "Nombre de véhicules",
    grandeurArticle: "le nombre de véhicules",
    uniteParenthese: "en milliers de véhicules",
    unitePourValeur: "milliers de véhicules",
  },
  {
    id: "population-ville-frontaliere",
    entiteDescription: "La population d'une ville frontalière",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en millions d'habitants",
    unitePourValeur: "millions d'habitants",
  },
  {
    id: "panneaux-solaires",
    entiteDescription: "Le taux d'équipement en panneaux solaires d'une région",
    grandeurLabel: "Taux d'équipement",
    grandeurArticle: "le taux d'équipement",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "coraux",
    entiteDescription: "La couverture corallienne d'une zone protégée en restauration",
    grandeurLabel: "Couverture corallienne",
    grandeurArticle: "la couverture corallienne",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "entreprises-renouvelable",
    entiteDescription: "Le taux d'entreprises utilisant l'énergie renouvelable",
    grandeurLabel: "Taux d'entreprises",
    grandeurArticle: "le taux d'entreprises",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "reserve-gazelles",
    entiteDescription: "La population d'une réserve de gazelles",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en centaines d'individus",
    unitePourValeur: "centaines d'individus",
  },
  {
    id: "taux-recyclage",
    entiteDescription: "Le taux de recyclage d'une commune",
    grandeurLabel: "Taux de recyclage",
    grandeurArticle: "le taux de recyclage",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "population-village-declin",
    entiteDescription: "La population d'un village en léger déclin",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en centaines d'habitants",
    unitePourValeur: "centaines d'habitants",
  },
  {
    id: "usagers-transports",
    entiteDescription: "Le nombre d'usagers des transports en commun",
    grandeurLabel: "Nombre d'usagers",
    grandeurArticle: "le nombre d'usagers",
    uniteParenthese: "en milliers d'usagers",
    unitePourValeur: "milliers d'usagers",
  },
  {
    id: "population-ours",
    entiteDescription: "La population d'ours dans un parc national",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en dizaines d'individus",
    unitePourValeur: "dizaines d'individus",
  },
  {
    id: "fibre-optique",
    entiteDescription: "Le taux de pénétration d'un réseau de fibre optique",
    grandeurLabel: "Taux de pénétration",
    grandeurArticle: "le taux de pénétration",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "tortues-marines",
    entiteDescription: "Le nombre de tortues marines sur une plage protégée",
    grandeurLabel: "Nombre de tortues",
    grandeurArticle: "le nombre de tortues",
    uniteParenthese: "en centaines d'individus",
    unitePourValeur: "centaines d'individus",
  },
  {
    id: "tri-selectif",
    entiteDescription: "Le taux de foyers pratiquant le tri sélectif",
    grandeurLabel: "Taux de foyers",
    grandeurArticle: "le taux de foyers",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "reserve-bisons",
    entiteDescription: "La population d'une réserve de bisons",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en centaines d'individus",
    unitePourValeur: "centaines d'individus",
  },
  {
    id: "acces-eau-potable",
    entiteDescription: "Le taux d'accès à l'eau potable dans une région en développement",
    grandeurLabel: "Taux d'accès",
    grandeurArticle: "le taux d'accès",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
  {
    id: "population-dauphins",
    entiteDescription: "La population de dauphins dans une baie protégée",
    grandeurLabel: "Population",
    grandeurArticle: "la population",
    uniteParenthese: "en dizaines d'individus",
    unitePourValeur: "dizaines d'individus",
  },
  {
    id: "terres-bio",
    entiteDescription: "Le taux de terres agricoles converties au bio",
    grandeurLabel: "Taux de conversion",
    grandeurArticle: "le taux de conversion",
    uniteParenthese: "en %",
    unitePourValeur: "%",
  },
];
