/**
 * Couche A (5e) — 30 contextes narratifs pour la famille "Eau salée" (5gen23). Un seul est tiré
 * uniformément à chaque génération (`eauSalee.ts`). Champs pré-écrits, jamais de calcul d'accord
 * grammatical à l'exécution — voir `core5e/limitesContexte.types.ts` pour le contrat.
 */
import type { ContexteEauSalee } from "../../core5e/limitesContexte.types";

export const CONTEXTES_EAU_SALEE: ContexteEauSalee[] = [
  {
    id: "citerne-sel",
    sujetPhrase: "Une citerne",
    contenuInitial: "d'eau pure",
    ajoutPhrase: "de l'eau salée",
    quantitePhrase: "de sel",
    etatAccord: "dissous",
  },
  {
    id: "piscine-chlore",
    sujetPhrase: "Une piscine",
    contenuInitial: "d'eau non traitée",
    ajoutPhrase: "de l'eau chlorée",
    quantitePhrase: "de chlore",
    etatAccord: "dissous",
  },
  {
    id: "perfusion-medicament",
    sujetPhrase: "Une poche de perfusion",
    contenuInitial: "de sérum physiologique",
    ajoutPhrase: "une solution médicamenteuse",
    quantitePhrase: "de médicament",
    etatAccord: "dissous",
  },
  {
    id: "sirop-sucre",
    sujetPhrase: "Un réservoir",
    contenuInitial: "d'eau pure",
    ajoutPhrase: "du sirop sucré",
    quantitePhrase: "de sucre",
    etatAccord: "dissous",
  },
  {
    id: "irrigation-engrais",
    sujetPhrase: "Un bassin d'irrigation",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "de l'eau enrichie en engrais",
    quantitePhrase: "d'engrais",
    etatAccord: "dissous",
  },
  {
    id: "cuve-colorant",
    sujetPhrase: "Une cuve",
    contenuInitial: "d'eau incolore",
    ajoutPhrase: "une solution colorée",
    quantitePhrase: "de colorant",
    etatAccord: "dissous",
  },
  {
    id: "fermentation-alcool",
    sujetPhrase: "Une cuve de fermentation",
    contenuInitial: "de moût sans alcool",
    ajoutPhrase: "un moût en cours de fermentation",
    quantitePhrase: "d'alcool",
    etatAccord: "dissous",
  },
  {
    id: "serre-co2",
    sujetPhrase: "Une serre ventilée",
    contenuInitial: "d'air extérieur",
    ajoutPhrase: "de l'air enrichi en CO₂",
    quantitePhrase: "de CO₂",
    etatAccord: "présent",
  },
  {
    id: "riviere-polluant",
    sujetPhrase: "Une rivière",
    contenuInitial: "d'eau propre",
    ajoutPhrase: "de l'eau polluée en provenance d'un affluent",
    quantitePhrase: "de polluant",
    etatAccord: "dissous",
  },
  {
    id: "aquarium-oxygene",
    sujetPhrase: "Un aquarium",
    contenuInitial: "d'eau pauvre en oxygène",
    ajoutPhrase: "de l'eau oxygénée par le bulleur",
    quantitePhrase: "d'oxygène",
    etatAccord: "dissous",
  },
  {
    id: "elevage-poissons-sel",
    sujetPhrase: "Un bassin d'élevage de poissons",
    contenuInitial: "d'eau douce",
    ajoutPhrase: "de l'eau salée",
    quantitePhrase: "de sel",
    etatAccord: "dissous",
  },
  {
    id: "cuve-desinfectant",
    sujetPhrase: "Une cuve industrielle",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "une solution désinfectante",
    quantitePhrase: "de désinfectant",
    etatAccord: "dissous",
  },
  {
    id: "boisson-vitamine",
    sujetPhrase: "Une cuve de boisson enrichie",
    contenuInitial: "de boisson non enrichie",
    ajoutPhrase: "une solution vitaminée",
    quantitePhrase: "de vitamine",
    etatAccord: "dissoute",
  },
  {
    id: "reseau-fluor",
    sujetPhrase: "Un réservoir du réseau d'eau potable",
    contenuInitial: "d'eau non fluorée",
    ajoutPhrase: "de l'eau fluorée",
    quantitePhrase: "de fluor",
    etatAccord: "dissous",
  },
  {
    id: "jus-sucre",
    sujetPhrase: "Une cuve de jus",
    contenuInitial: "d'eau pure",
    ajoutPhrase: "du jus sucré concentré",
    quantitePhrase: "de sucre",
    etatAccord: "dissous",
  },
  {
    id: "saumure-fromagerie",
    sujetPhrase: "Un bac de saumure",
    contenuInitial: "d'eau douce",
    ajoutPhrase: "de la saumure concentrée",
    quantitePhrase: "de sel",
    etatAccord: "dissous",
  },
  {
    id: "carburant-additif",
    sujetPhrase: "Un réservoir de carburant",
    contenuInitial: "de carburant sans additif",
    ajoutPhrase: "du carburant additivé",
    quantitePhrase: "d'additif",
    etatAccord: "dissous",
  },
  {
    id: "bain-teinture",
    sujetPhrase: "Un bain de teinture textile",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "une solution de teinture",
    quantitePhrase: "de teinture",
    etatAccord: "dissoute",
  },
  {
    id: "brasserie-levure",
    sujetPhrase: "Une cuve de brasserie",
    contenuInitial: "de moût sans levure",
    ajoutPhrase: "un moût ensemencé en levure",
    quantitePhrase: "de levure",
    etatAccord: "dissoute",
  },
  {
    id: "lac-source-salee",
    sujetPhrase: "Un lac",
    contenuInitial: "d'eau douce",
    ajoutPhrase: "de l'eau d'une source salée",
    quantitePhrase: "de sel",
    etatAccord: "dissous",
  },
  {
    id: "bassin-pesticide",
    sujetPhrase: "Un bassin de traitement agricole",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "une solution de pesticide",
    quantitePhrase: "de pesticide",
    etatAccord: "dissous",
  },
  {
    id: "elevage-ammoniac",
    sujetPhrase: "Un bassin d'élevage",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "de l'eau chargée en ammoniac",
    quantitePhrase: "d'ammoniac",
    etatAccord: "dissous",
  },
  {
    id: "perfusion-glucose",
    sujetPhrase: "Une poche de perfusion",
    contenuInitial: "de sérum physiologique",
    ajoutPhrase: "une solution glucosée",
    quantitePhrase: "de glucose",
    etatAccord: "dissous",
  },
  {
    id: "savon-parfum",
    sujetPhrase: "Une cuve de savon liquide",
    contenuInitial: "de savon non parfumé",
    ajoutPhrase: "du savon parfumé concentré",
    quantitePhrase: "de parfum",
    etatAccord: "dissous",
  },
  {
    id: "reservoir-calcaire",
    sujetPhrase: "Un réservoir d'eau",
    contenuInitial: "d'eau douce",
    ajoutPhrase: "de l'eau calcaire",
    quantitePhrase: "de calcaire",
    etatAccord: "dissous",
  },
  {
    id: "traitement-surface-acide",
    sujetPhrase: "Une cuve de traitement de surface",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "une solution acide",
    quantitePhrase: "d'acide",
    etatAccord: "dissous",
  },
  {
    id: "marais-salant",
    sujetPhrase: "Un marais salant",
    contenuInitial: "d'eau douce",
    ajoutPhrase: "de l'eau de mer",
    quantitePhrase: "de sel",
    etatAccord: "dissous",
  },
  {
    id: "hydroponie-nutriments",
    sujetPhrase: "Un bac hydroponique",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "une solution nutritive",
    quantitePhrase: "de nutriments",
    etatAccord: "dissous",
  },
  {
    id: "desinfection-iode",
    sujetPhrase: "Un bassin de désinfection",
    contenuInitial: "d'eau claire",
    ajoutPhrase: "une solution iodée",
    quantitePhrase: "d'iode",
    etatAccord: "dissous",
  },
  {
    id: "confiture-industrielle",
    sujetPhrase: "Une cuve de fabrication de confiture",
    contenuInitial: "de fruits mixés sans sucre",
    ajoutPhrase: "un sirop de sucre concentré",
    quantitePhrase: "de sucre",
    etatAccord: "dissous",
  },
];
