import type { QuestionVraiFaux, VarianteQuizCalculVectoriel } from "../../core/quizCalculVectoriel.types";

/**
 * Banque de questions pré-écrites — 315 affirmations (35 par thème × 9 thèmes, portées de 20 à 35
 * par une campagne d'enrichissement ultérieure), toutes vérifiées mathématiquement avant publication
 * (aucune génération procédurale, contrairement aux générateurs gen20-29 eux-mêmes). Même convention
 * que `quizCercleTriangles/banque.ts` (gen63).
 */
export const BANQUE_QUIZ_CALCUL_VECTORIEL: Record<VarianteQuizCalculVectoriel, QuestionVraiFaux[]> = {
  relationVectorielle: [
    { enonce: "Si vec(AB) = vec(u), alors les coordonnées de B s'obtiennent en ajoutant celles de u à celles de A.", reponse: true, justification: "vec(AB) = B − A, donc B = A + vec(u)." },
    { enonce: "Le milieu M de [AB] vérifie vec(AM) = vec(MB).", reponse: true, justification: "M équidistant de A et B, sur le segment : les deux vecteurs sont égaux." },
    { enonce: "Si M est le milieu de [AB], alors vec(AM) = (1/2)·vec(AB).", reponse: true, justification: "M partage [AB] exactement en son milieu." },
    { enonce: "Si vec(AB) = vec(CD), alors ABDC est un parallélogramme (éventuellement aplati).", reponse: true, justification: "Deux vecteurs égaux définissent des côtés opposés parallèles et de même longueur." },
    { enonce: "Pour placer M tel que vec(AM) = (1/3)·vec(AB), M partage [AB] dans le rapport AM:MB = 1:2.", reponse: true, justification: "AM vaut le tiers de AB, donc MB en vaut les deux tiers." },
    { enonce: "Si A(2 ; 5) et vec(u) = (3 ; −1), le translaté B de A par u a pour coordonnées (5 ; 4).", reponse: true, justification: "2+3=5 et 5+(−1)=4." },
    { enonce: "Le milieu de A(2 ; 5) et B(4 ; 1) a pour coordonnées (3 ; 3).", reponse: true, justification: "(2+4)/2=3 et (5+1)/2=3." },
    { enonce: "vec(AM) = vec(0) signifie que M est confondu avec A.", reponse: true, justification: "Le seul vecteur de norme nulle relie un point à lui-même." },
    { enonce: "La relation vec(AM) = k·vec(AB) place toujours M sur la droite (AB), quel que soit k.", reponse: true, justification: "M est un multiple scalaire du vecteur AB depuis A, donc toujours aligné avec A et B." },
    { enonce: "La relation vec(AM) = k·vec(AB) avec k négatif place M à l'extérieur du segment [AB], du côté de A.", reponse: true, justification: "Un coefficient négatif inverse le sens, M s'éloigne de B au-delà de A." },
    { enonce: "Les coordonnées du milieu M de [AB] sont (xB − xA ; yB − yA).", reponse: false, justification: "Ce sont les composantes de vec(AB), pas les coordonnées du milieu — le milieu est la moyenne des coordonnées." },
    { enonce: "vec(AB) = vec(CD) signifie que AB et CD ont la même longueur, mais peuvent avoir des directions différentes.", reponse: false, justification: "Une égalité vectorielle impose la même direction, le même sens et la même longueur." },
    { enonce: "Deux vecteurs égaux ont nécessairement le même point de départ.", reponse: false, justification: "Un vecteur ne dépend que de sa direction, son sens et sa longueur — pas de son point d'application." },
    { enonce: "Le milieu de A(2 ; 5) et B(4 ; 1) a pour coordonnées (3 ; 2).", reponse: false, justification: "L'ordonnée du milieu vaut (5+1)/2 = 3, pas 2." },
    { enonce: "Dans une relation vectorielle comme 2·vec(AM) = vec(AB), on résout directement les coordonnées de M sans jamais passer par les composantes du vecteur.", reponse: false, justification: "Il faut d'abord traduire la relation en composantes (Δx, Δy) avant de retrouver les coordonnées de M." },
    { enonce: "Si vec(AB) = vec(AC), alors B et C sont nécessairement deux points distincts.", reponse: false, justification: "vec(AB) = vec(AC) entraîne B − A = C − A, donc B = C : ils sont toujours confondus." },
    { enonce: "Pour un vecteur vec(u) = (ux ; uy), le translaté d'un point A(xA ; yA) est B(xA − ux ; yA − uy).", reponse: false, justification: "Le translaté s'obtient en additionnant les composantes, pas en les soustrayant." },
    { enonce: "Si k = 1 dans vec(AM) = k·vec(AB), alors M est le milieu de [AB].", reponse: false, justification: "k = 1 donne vec(AM) = vec(AB), donc M est confondu avec B, pas avec le milieu." },
    { enonce: "Une translation de vecteur vec(u) déplace chaque point du plan d'un vecteur différent, dépendant de sa position.", reponse: false, justification: "Une translation applique le même vecteur vec(u) à tous les points, quelle que soit leur position." },
    { enonce: "Si M est le milieu de [AB] et que A = B, alors M est différent de A.", reponse: false, justification: "Si A = B, le milieu de [AB] est confondu avec A (et avec B)." },
    { enonce: "Si A(−1 ; 3) et vec(u) = (4 ; −2), le translaté B de A par u a pour coordonnées (3 ; 1).", reponse: true, justification: "−1+4=3 et 3+(−2)=1." },
    { enonce: "Le milieu de A(−3 ; 7) et B(5 ; −1) a pour coordonnées (1 ; 3).", reponse: true, justification: "(−3+5)/2=1 et (7+(−1))/2=3." },
    { enonce: "Si vec(AM) = (2/5)·vec(AB), alors M partage [AB] dans le rapport AM:MB = 2:3.", reponse: true, justification: "AM vaut 2/5 de AB, donc MB en vaut les 3/5 restants : le rapport est bien 2:3." },
    { enonce: "Si vec(EF) = vec(GH), alors EFHG est un parallélogramme (éventuellement aplati).", reponse: true, justification: "Deux vecteurs égaux définissent des côtés opposés parallèles et de même longueur, comme pour ABDC à partir de vec(AB)=vec(CD)." },
    { enonce: "Si vec(AM) = 2·vec(MB), alors M partage le segment [AB] dans le rapport AM:MB = 2:1.", reponse: true, justification: "vec(AB) = vec(AM)+vec(MB) = 3·vec(MB), donc vec(MB) vaut le tiers de vec(AB) et vec(AM) les deux tiers : le rapport est 2:1." },
    { enonce: "Si A(0 ; 0) et vec(u) = (−5 ; 2), le translaté B de A par u a pour coordonnées (−5 ; 2).", reponse: true, justification: "0+(−5)=−5 et 0+2=2 : B a les mêmes coordonnées que vec(u) puisque A est l'origine." },
    { enonce: "Le point M vérifiant vec(AM) = (3/4)·vec(AB) partage [AB] dans le rapport AM:MB = 3:1.", reponse: true, justification: "AM vaut 3/4 de AB, donc MB en vaut le 1/4 restant : le rapport est bien 3:1." },
    { enonce: "Si M est le milieu de [AB] avec A(6 ; −2) et B(−2 ; 8), alors M a pour coordonnées (2 ; 3).", reponse: true, justification: "(6+(−2))/2=2 et (−2+8)/2=3." },
    { enonce: "Le milieu de A(−3 ; 7) et B(5 ; −1) a pour coordonnées (1 ; 4).", reponse: false, justification: "L'ordonnée du milieu vaut (7+(−1))/2 = 3, pas 4." },
    { enonce: "Si vec(AM) = (2/5)·vec(AB), alors M partage [AB] dans le rapport AM:MB = 2:5.", reponse: false, justification: "MB vaut 3/5 de AB (pas 2/5), donc le rapport correct est 2:3, pas 2:5." },
    { enonce: "Si A(−1 ; 3) et vec(u) = (4 ; −2), le translaté B de A par u a pour coordonnées (3 ; 5).", reponse: false, justification: "3+(−2)=1, pas 5 : l'ordonnée correcte de B est 1." },
    { enonce: "Si vec(AM) = 2·vec(MB), alors M est situé au-delà de B, à l'extérieur du segment [AB].", reponse: false, justification: "Le coefficient 2 est positif : M reste entre A et B, aux deux tiers du segment depuis A." },
    { enonce: "Si A(6 ; −2) et B(−2 ; 8), le milieu M de [AB] a pour coordonnées (4 ; 6).", reponse: false, justification: "Le milieu correct est (2 ; 3), obtenu en faisant la moyenne des coordonnées, pas leur différence." },
    { enonce: "Le point M vérifiant vec(AM) = (3/4)·vec(AB) partage [AB] dans le rapport AM:MB = 4:3.", reponse: false, justification: "MB vaut seulement 1/4 de AB, donc le rapport correct est 3:1, pas 4:3." },
    { enonce: "Si vec(EF) = vec(GH), alors EFGH (dans cet ordre) est nécessairement un parallélogramme convexe.", reponse: false, justification: "L'ordre correspondant est EFHG, pas EFGH ; de plus le parallélogramme peut être aplati si E, F, G, H sont alignés." },
  ],
  combinaisonLineaire: [
    { enonce: "Les composantes de vec(AB) sont (xB − xA ; yB − yA).", reponse: true, justification: "Définition des composantes d'un vecteur à partir des coordonnées de ses extrémités." },
    { enonce: "vec(BA) = −vec(AB).", reponse: true, justification: "Inverser les extrémités d'un vecteur donne son opposé." },
    { enonce: "Si vec(u) = (2 ; −3), alors les composantes de 3·vec(u) sont (6 ; −9).", reponse: true, justification: "Chaque composante est multipliée par le scalaire : 3×2=6 et 3×(−3)=−9." },
    { enonce: "La somme de deux vecteurs s'obtient en additionnant leurs composantes une à une.", reponse: true, justification: "L'addition vectorielle est une addition composante par composante." },
    { enonce: "vec(AB) + vec(BC) = vec(AC) (relation de Chasles).", reponse: true, justification: "Identité fondamentale de la relation de Chasles." },
    { enonce: "Si vec(u) = (1 ; 4) et vec(v) = (−2 ; 3), alors vec(u) + vec(v) = (−1 ; 7).", reponse: true, justification: "1+(−2)=−1 et 4+3=7." },
    { enonce: "Réduire une expression vectorielle signifie la ramener à un seul vecteur, éventuellement le vecteur nul.", reponse: true, justification: "C'est l'objectif d'une réduction : obtenir un unique vecteur résultant." },
    { enonce: "vec(AB) − vec(AC) = vec(CB).", reponse: true, justification: "(B−A)−(C−A) = B−C = vec(CB)." },
    { enonce: "Le vecteur nul a pour composantes (0 ; 0), quels que soient les points qui le définissent (point confondu avec lui-même).", reponse: true, justification: "vec(AA) = A − A = (0 ; 0), pour tout point A." },
    { enonce: "Dans une expression combinant un vecteur nommé vec(u) et un vecteur point-à-point vec(AB), on peut additionner leurs composantes directement, chacune calculée séparément.", reponse: true, justification: "Une fois les composantes de chaque vecteur connues, l'addition se fait terme à terme, quelle que soit sa notation d'origine." },
    { enonce: "Les composantes de vec(AB) sont (xA − xB ; yA − yB).", reponse: false, justification: "C'est l'inverse : les composantes sont (xB−xA ; yB−yA), ce qui correspond en fait à vec(BA)." },
    { enonce: "vec(BA) = vec(AB).", reponse: false, justification: "vec(BA) est l'opposé de vec(AB), pas son égal (sauf si le vecteur est nul)." },
    { enonce: "Si vec(u) = (2 ; −3), les composantes de 3·vec(u) sont (6 ; −3) (on ne multiplie que la première composante).", reponse: false, justification: "Les DEUX composantes sont multipliées par le scalaire : (6 ; −9)." },
    { enonce: "La somme de deux vecteurs s'obtient en additionnant leurs normes.", reponse: false, justification: "On additionne les composantes, pas les normes — la norme de la somme n'est pas la somme des normes en général." },
    { enonce: "vec(AB) + vec(BC) = vec(BA) (relation de Chasles).", reponse: false, justification: "La relation de Chasles donne vec(AC), pas vec(BA)." },
    { enonce: "Si vec(u) = (1 ; 4) et vec(v) = (−2 ; 3), alors vec(u) + vec(v) = (3 ; 1) (composantes inversées).", reponse: false, justification: "Le bon résultat est (−1 ; 7) ; ceci additionne les mauvaises composantes ensemble." },
    { enonce: "Réduire une expression vectorielle signifie toujours obtenir le vecteur nul.", reponse: false, justification: "Le résultat réduit peut être n'importe quel vecteur, pas seulement le vecteur nul." },
    { enonce: "vec(AB) − vec(AC) = vec(BC).", reponse: false, justification: "Le bon résultat est vec(CB) (B−C), pas vec(BC) (C−B)." },
    { enonce: "Le vecteur vec(AA) (point A répété) a des composantes qui dépendent de la position de A.", reponse: false, justification: "vec(AA) = A − A = (0 ; 0) quelle que soit la position de A." },
    { enonce: "Un vecteur nommé (vec(u)) et un vecteur défini par deux points (vec(AB)) ne peuvent jamais apparaître dans la même expression vectorielle.", reponse: false, justification: "Il suffit de calculer les composantes de chacun séparément pour pouvoir les combiner librement." },
    { enonce: "Si vec(u) = (−4 ; 5), alors les composantes de −2·vec(u) sont (8 ; −10).", reponse: true, justification: "−2×(−4)=8 et −2×5=−10." },
    { enonce: "Si A(1 ; 2) et B(5 ; −1), alors vec(AB) a pour composantes (4 ; −3).", reponse: true, justification: "5−1=4 et −1−2=−3." },
    { enonce: "Si vec(u) = (3 ; −2) et vec(v) = (−1 ; 5), alors 2·vec(u) − vec(v) a pour composantes (7 ; −9).", reponse: true, justification: "2·(3;−2)=(6;−4), puis (6;−4)−(−1;5)=(7;−9)." },
    { enonce: "Pour tout vecteur vec(u), on a vec(u) + (−vec(u)) = vec(0).", reponse: true, justification: "Un vecteur et son opposé s'annulent toujours en s'additionnant." },
    { enonce: "Si vec(u) = (4 ; −2), alors −vec(u) a pour composantes (−4 ; 2).", reponse: true, justification: "L'opposé d'un vecteur change le signe de chacune de ses composantes." },
    { enonce: "Si A(3 ; −4) et B(−1 ; 2), les composantes de vec(BA) sont (4 ; −6).", reponse: true, justification: "vec(BA) = A − B = (3−(−1) ; −4−2) = (4 ; −6)." },
    { enonce: "Si vec(u) = (1 ; 1), alors 5·vec(u) − 2·vec(u) = 3·vec(u), soit (3 ; 3).", reponse: true, justification: "5−2=3, et 3·(1;1)=(3;3)." },
    { enonce: "Les composantes d'un vecteur ne dépendent pas des points choisis pour le représenter, seulement de sa direction, son sens et sa longueur.", reponse: true, justification: "Un vecteur est défini indépendamment de son point d'application ; ses composantes restent identiques pour tous ses représentants." },
    { enonce: "Si vec(u) = (−4 ; 5), alors les composantes de −2·vec(u) sont (−8 ; −10) (le coefficient n'affecte que la première composante).", reponse: false, justification: "Les deux composantes sont multipliées par −2 : le résultat correct est (8 ; −10)." },
    { enonce: "Si A(1 ; 2) et B(5 ; −1), alors vec(AB) a pour composantes (−4 ; 3) (coordonnées de A moins celles de B).", reponse: false, justification: "Ce calcul donne vec(BA), pas vec(AB) ; les composantes correctes de vec(AB) sont (4 ; −3)." },
    { enonce: "Si vec(u) = (3 ; −2) et vec(v) = (−1 ; 5), alors 2·vec(u) − vec(v) a pour composantes (4 ; −7) (en oubliant de multiplier vec(u) par 2).", reponse: false, justification: "Il faut d'abord multiplier vec(u) par 2 avant de soustraire vec(v) : le résultat correct est (7 ; −9), pas (4 ; −7)." },
    { enonce: "vec(u) + (−vec(u)) est un vecteur qui dépend de vec(u), jamais le vecteur nul.", reponse: false, justification: "Un vecteur et son opposé s'annulent toujours : la somme vaut systématiquement vec(0), quel que soit vec(u)." },
    { enonce: "Si vec(u) = (4 ; −2), alors −vec(u) a pour composantes (4 ; −2) (les mêmes que vec(u)).", reponse: false, justification: "L'opposé d'un vecteur change le signe des deux composantes : le résultat correct est (−4 ; 2)." },
    { enonce: "Si A(3 ; −4) et B(−1 ; 2), les composantes de vec(BA) sont (−4 ; 6) (sans changer de signe par rapport à vec(AB)).", reponse: false, justification: "vec(BA) est l'opposé de vec(AB) : les composantes correctes sont (4 ; −6)." },
    { enonce: "Combiner (additionner) trois vecteurs vec(u), vec(v) et vec(w) nécessite de les additionner dans un ordre précis, sinon le résultat change.", reponse: false, justification: "L'addition vectorielle est commutative et associative : l'ordre des trois vecteurs n'a aucune influence sur le résultat." },
  ],
  constructionGraphique: [
    { enonce: "Multiplier vec(AB) par un coefficient k > 1 donne un vecteur de même sens, mais plus long.", reponse: true, justification: "Un coefficient positif supérieur à 1 conserve le sens et allonge le vecteur." },
    { enonce: "Multiplier vec(AB) par un coefficient k négatif inverse le sens du vecteur.", reponse: true, justification: "Un coefficient négatif retourne le vecteur dans le sens opposé." },
    { enonce: "Le vecteur (−1)·vec(AB) est égal à vec(BA).", reponse: true, justification: "Multiplier par −1 donne exactement l'opposé du vecteur." },
    { enonce: "Quel que soit le coefficient k (non nul), le vecteur k·vec(AB) reste colinéaire à vec(AB).", reponse: true, justification: "Un multiple scalaire d'un vecteur reste toujours porté par la même direction." },
    { enonce: "Multiplier vec(AB) par 0 donne le vecteur nul, sans direction définie.", reponse: true, justification: "0·vec(AB) = vec(0), qui n'a pas de direction propre." },
    { enonce: "Multiplier vec(AB) par un coefficient k tel que 0 < k < 1 donne un vecteur plus court, de même sens.", reponse: true, justification: "Un coefficient positif inférieur à 1 raccourcit le vecteur sans changer son sens." },
    { enonce: "Deux représentants d'un même vecteur (même longueur, direction, sens) peuvent être placés à des endroits différents de la grille sans que le vecteur change.", reponse: true, justification: "Un vecteur est indépendant de son point d'application." },
    { enonce: "Le vecteur 2·vec(AB) a une norme égale au double de celle de vec(AB).", reponse: true, justification: "||2·vec(AB)|| = |2|·||vec(AB)|| = 2·||vec(AB)||." },
    { enonce: "Le vecteur (−2)·vec(AB) a la même norme que 2·vec(AB).", reponse: true, justification: "La norme dépend de la valeur absolue du coefficient : |−2| = |2| = 2." },
    { enonce: "Pour tracer k·vec(AB) à partir d'un point de départ donné, il faut reporter k fois la longueur de AB dans la bonne direction et le bon sens.", reponse: true, justification: "C'est la construction géométrique d'un multiple scalaire d'un vecteur." },
    { enonce: "Multiplier vec(AB) par un coefficient k > 1 donne un vecteur de sens opposé.", reponse: false, justification: "Un coefficient positif conserve le sens ; seul un coefficient négatif l'inverse." },
    { enonce: "Multiplier vec(AB) par un coefficient positif peut changer sa direction.", reponse: false, justification: "Multiplier par un scalaire ne change jamais la direction (la droite support reste la même)." },
    { enonce: "Le vecteur (−1)·vec(AB) est égal à vec(AB).", reponse: false, justification: "(−1)·vec(AB) est l'opposé de vec(AB), donc égal à vec(BA), pas à vec(AB)." },
    { enonce: "Le vecteur k·vec(AB), pour un k négatif, n'est plus colinéaire à vec(AB).", reponse: false, justification: "Il reste colinéaire : seul le sens change, la direction reste identique." },
    { enonce: "Multiplier vec(AB) par 0 donne un vecteur de même direction que vec(AB), mais de norme nulle.", reponse: false, justification: "Le vecteur nul n'a pas de direction propre définie." },
    { enonce: "Multiplier vec(AB) par un coefficient k tel que 0 < k < 1 donne un vecteur plus long.", reponse: false, justification: "Un coefficient strictement compris entre 0 et 1 raccourcit le vecteur." },
    { enonce: "Deux représentants d'un même vecteur doivent obligatoirement partager le même point de départ.", reponse: false, justification: "Un vecteur peut être représenté à partir de n'importe quel point, tant que direction/sens/longueur sont conservés." },
    { enonce: "Le vecteur 2·vec(AB) a une norme égale à celle de vec(AB) plus 2.", reponse: false, justification: "La norme est multipliée par 2, pas augmentée de 2." },
    { enonce: "Le vecteur (−2)·vec(AB) est deux fois plus court que 2·vec(AB).", reponse: false, justification: "Les deux vecteurs ont la même norme (|−2| = |2|), seul le sens diffère." },
    { enonce: "La direction d'un vecteur k·vec(AB) change selon la valeur absolue de k.", reponse: false, justification: "La direction (la droite support) ne dépend jamais de k — seules la longueur et éventuellement le sens changent." },
    { enonce: "Pour tracer (1/2)·vec(AB) à partir d'un point donné, on doit reporter une longueur égale à la moitié de AB, dans le même sens que vec(AB).", reponse: true, justification: "Un coefficient 1/2, positif et inférieur à 1, conserve le sens et divise la longueur par deux." },
    { enonce: "Le vecteur (−3)·vec(AB) est trois fois plus long que vec(AB) et de sens opposé.", reponse: true, justification: "La valeur absolue du coefficient (3) triple la longueur, et son signe négatif inverse le sens." },
    { enonce: "Si l'on trace successivement vec(AB) puis 2·vec(AB) à partir du même point de départ, les deux flèches sont portées par la même droite.", reponse: true, justification: "Un multiple scalaire d'un vecteur reste toujours colinéaire à ce vecteur, donc sur la même droite support." },
    { enonce: "Un coefficient multiplicateur k = 1 laisse le vecteur totalement inchangé (même longueur, même direction, même sens).", reponse: true, justification: "1·vec(AB) = vec(AB) : le vecteur reste rigoureusement identique." },
    { enonce: "Sur une grille quadrillée, si vec(AB) correspond à un déplacement de 2 carreaux à droite et 1 carreau vers le haut, alors 3·vec(AB) correspond à un déplacement de 6 carreaux à droite et 3 carreaux vers le haut.", reponse: true, justification: "Chaque composante du déplacement est multipliée par 3 : 2×3=6 et 1×3=3." },
    { enonce: "Pour construire graphiquement −(1/2)·vec(AB), on trace un vecteur deux fois plus court que vec(AB), orienté en sens opposé.", reponse: true, justification: "La valeur absolue du coefficient (1/2) divise la longueur par deux, et son signe négatif inverse le sens." },
    { enonce: "Deux constructions graphiques de k·vec(AB), réalisées à partir de deux points de départ différents, produisent des flèches parallèles entre elles.", reponse: true, justification: "Les deux flèches représentent le même vecteur k·vec(AB), donc partagent la même direction." },
    { enonce: "Si un vecteur vec(v) est construit comme 4·vec(AB), alors pour retrouver vec(AB) à partir de vec(v), il faut multiplier vec(v) par 1/4.", reponse: true, justification: "(1/4)·vec(v) = (1/4)·4·vec(AB) = vec(AB)." },
    { enonce: "Pour tracer (1/2)·vec(AB) à partir d'un point donné, on doit reporter une longueur égale au double de AB.", reponse: false, justification: "Un coefficient 1/2 divise la longueur par deux, il ne la double pas." },
    { enonce: "Le vecteur (−3)·vec(AB) est trois fois plus court que vec(AB).", reponse: false, justification: "La valeur absolue du coefficient (3) triple la longueur, elle ne la divise pas." },
    { enonce: "Si l'on trace successivement vec(AB) puis 2·vec(AB) à partir du même point de départ, les deux flèches ne sont jamais portées par la même droite.", reponse: false, justification: "Elles sont au contraire colinéaires, donc portées par la même droite." },
    { enonce: "Un coefficient multiplicateur k = 1 double la longueur du vecteur.", reponse: false, justification: "k = 1 laisse le vecteur inchangé ; c'est k = 2 qui double sa longueur." },
    { enonce: "Sur une grille quadrillée, si vec(AB) correspond à un déplacement de 2 carreaux à droite et 1 carreau vers le haut, alors 3·vec(AB) correspond à un déplacement de 5 carreaux à droite et 3 carreaux vers le haut.", reponse: false, justification: "Le déplacement horizontal correct est 2×3=6 carreaux, pas 5." },
    { enonce: "Pour construire graphiquement −(1/2)·vec(AB), on trace un vecteur deux fois plus long que vec(AB), dans le même sens.", reponse: false, justification: "La valeur absolue du coefficient (1/2) raccourcit le vecteur, et son signe négatif inverse le sens : ni plus long, ni même sens." },
    { enonce: "Si un vecteur vec(v) est construit comme 4·vec(AB), alors pour retrouver vec(AB) à partir de vec(v), il faut multiplier vec(v) par 4.", reponse: false, justification: "Il faut multiplier par l'inverse du coefficient, soit 1/4, pas par 4." },
  ],
  colinearite: [
    { enonce: "Deux vecteurs vec(u)(ux ; uy) et vec(v)(vx ; vy) sont colinéaires si et seulement si ux·vy − uy·vx = 0.", reponse: true, justification: "C'est le critère du déterminant nul pour la colinéarité." },
    { enonce: "Trois points A, B, C sont alignés si et seulement si vec(AB) et vec(AC) sont colinéaires.", reponse: true, justification: "L'alignement se traduit exactement par la colinéarité de deux vecteurs formés à partir des 3 points." },
    { enonce: "Le vecteur nul est colinéaire à tout autre vecteur.", reponse: true, justification: "Le déterminant impliquant le vecteur nul est toujours nul, par convention le vecteur nul est colinéaire à tous les vecteurs." },
    { enonce: "Deux vecteurs colinéaires ont soit le même sens, soit des sens opposés.", reponse: true, justification: "Être colinéaire signifie être un multiple scalaire l'un de l'autre — positif (même sens) ou négatif (sens opposé)." },
    { enonce: "vec(u) = (4 ; 6) et vec(v) = (2 ; 3) sont colinéaires.", reponse: true, justification: "4×3 − 6×2 = 12 − 12 = 0 ; en effet vec(u) = 2·vec(v)." },
    { enonce: "Si vec(u) = (2 ; −1) et vec(v) = (−6 ; 3), alors vec(u) et vec(v) sont colinéaires (vec(v) = −3·vec(u)).", reponse: true, justification: "2×3 − (−1)×(−6) = 6 − 6 = 0." },
    { enonce: "Trois points alignés peuvent être vérifiés en calculant un seul déterminant (à partir de deux vecteurs formés avec les 3 points).", reponse: true, justification: "Un unique calcul ux·vy−uy·vx suffit à trancher l'alignement." },
    { enonce: "Deux vecteurs colinéaires sont nécessairement portés par des droites parallèles (ou la même droite).", reponse: true, justification: "La colinéarité signifie exactement même direction, donc des droites parallèles ou confondues." },
    { enonce: "Pour tester l'alignement de A, B, C, le choix des deux vecteurs à comparer (vec(AB)/vec(AC) ou vec(BA)/vec(BC)) ne change pas la conclusion.", reponse: true, justification: "L'alignement des 3 points est une propriété géométrique unique, indépendante du couple de vecteurs choisi." },
    { enonce: "Deux vecteurs colinéaires peuvent avoir des normes différentes.", reponse: true, justification: "La colinéarité concerne la direction, pas la longueur — un vecteur peut être un multiple quelconque de l'autre." },
    { enonce: "Deux vecteurs vec(u)(ux ; uy) et vec(v)(vx ; vy) sont colinéaires si et seulement si ux·vx + uy·vy = 0.", reponse: false, justification: "Cette formule (produit scalaire) teste l'orthogonalité, pas la colinéarité." },
    { enonce: "Trois points A, B, C sont alignés si et seulement si vec(AB) et vec(AC) sont orthogonaux.", reponse: false, justification: "Des vecteurs orthogonaux donneraient un angle droit en A, pas un alignement." },
    { enonce: "Le vecteur nul n'est colinéaire à aucun autre vecteur.", reponse: false, justification: "Le vecteur nul est colinéaire à tout vecteur, par convention." },
    { enonce: "Deux vecteurs colinéaires sont nécessairement perpendiculaires.", reponse: false, justification: "Colinéaire signifie même direction ; perpendiculaire signifie angle droit — ce sont des notions opposées, sauf cas du vecteur nul." },
    { enonce: "vec(u) = (3 ; 5) et vec(v) = (6 ; 9) sont colinéaires.", reponse: false, justification: "3×9 − 5×6 = 27 − 30 = −3 ≠ 0 : ils ne sont pas colinéaires." },
    { enonce: "Si vec(u) = (2 ; −1) et vec(v) = (−6 ; 3), alors vec(u) et vec(v) ne sont pas colinéaires.", reponse: false, justification: "2×3 − (−1)×(−6) = 0 : ils sont bien colinéaires (vec(v) = −3·vec(u))." },
    { enonce: "Trois points alignés ne peuvent être vérifiés qu'en mesurant physiquement les distances entre eux.", reponse: false, justification: "Un simple calcul de déterminant sur les coordonnées suffit, sans aucune mesure physique." },
    { enonce: "Deux vecteurs colinéaires sont nécessairement portés par deux droites sécantes distinctes.", reponse: false, justification: "Colinéaire signifie porté par des droites parallèles ou confondues, jamais sécantes en un seul point (sauf coïncidence triviale)." },
    { enonce: "Pour tester l'alignement de A, B, C, le résultat dépend du couple de vecteurs choisi parmi les trois points.", reponse: false, justification: "L'alignement est une propriété géométrique des 3 points, elle ne dépend pas du couple de vecteurs utilisé pour la vérifier." },
    { enonce: "Deux vecteurs colinéaires ont toujours la même norme.", reponse: false, justification: "La colinéarité n'impose rien sur les longueurs, seulement sur la direction." },
    { enonce: "vec(u) = (3 ; 7) et vec(v) = (6 ; 14) sont colinéaires.", reponse: true, justification: "3×14 − 7×6 = 42 − 42 = 0 ; en effet vec(v) = 2·vec(u)." },
    { enonce: "vec(u) = (5 ; −2) et vec(v) = (−15 ; 6) sont colinéaires (vec(v) = −3·vec(u)).", reponse: true, justification: "5×6 − (−2)×(−15) = 30 − 30 = 0." },
    { enonce: "Les points A(1 ; 2), B(3 ; 5) et C(7 ; 11) sont alignés.", reponse: true, justification: "vec(AB)=(2;3) et vec(AC)=(6;9) : 2×9 − 3×6 = 18 − 18 = 0." },
    { enonce: "Si vec(u) et vec(v) sont colinéaires et non nuls, il existe un réel k tel que vec(v) = k·vec(u).", reponse: true, justification: "C'est la définition même de la colinéarité entre deux vecteurs non nuls." },
    { enonce: "Le vecteur vec(u) = (0 ; 5) est colinéaire à tout vecteur de la forme (0 ; k).", reponse: true, justification: "0×k − 5×0 = 0, quel que soit k : le déterminant est toujours nul." },
    { enonce: "Si trois points A, B, C sont alignés, alors vec(BA) et vec(BC) sont également colinéaires.", reponse: true, justification: "L'alignement des 3 points reste vrai quel que soit le couple de vecteurs formé à partir d'eux." },
    { enonce: "Deux vecteurs directeurs différents d'une même droite sont toujours colinéaires entre eux.", reponse: true, justification: "Tous les vecteurs directeurs d'une droite partagent la même direction, donc sont colinéaires." },
    { enonce: "vec(u) = (−2 ; 8) et vec(v) = (1 ; −4) sont colinéaires (vec(u) = −2·vec(v)).", reponse: true, justification: "(−2)×(−4) − 8×1 = 8 − 8 = 0." },
    { enonce: "vec(u) = (3 ; 7) et vec(v) = (6 ; 15) sont colinéaires.", reponse: false, justification: "3×15 − 7×6 = 45 − 42 = 3 ≠ 0 : ils ne sont pas colinéaires." },
    { enonce: "vec(u) = (5 ; −2) et vec(v) = (−15 ; 6) ne sont pas colinéaires.", reponse: false, justification: "5×6 − (−2)×(−15) = 0 : ils sont bien colinéaires (vec(v) = −3·vec(u))." },
    { enonce: "Les points A(1 ; 2), B(3 ; 5) et C(7 ; 11) ne sont pas alignés.", reponse: false, justification: "Le déterminant de vec(AB) et vec(AC) vaut 0 : les trois points sont bien alignés." },
    { enonce: "Si vec(u) et vec(v) sont colinéaires et non nuls, alors vec(v) = k·vec(u) uniquement si k est un nombre entier.", reponse: false, justification: "k peut être n'importe quel réel non nul, pas seulement un entier." },
    { enonce: "Le vecteur vec(u) = (0 ; 5) n'est colinéaire qu'aux vecteurs qui ont exactement la même norme que lui.", reponse: false, justification: "La colinéarité ne dépend pas de la norme, seulement de la direction : tout vecteur (0 ; k) convient, quelle que soit sa longueur." },
    { enonce: "Si trois points A, B, C sont alignés, alors vec(BA) et vec(BC) ne sont jamais colinéaires.", reponse: false, justification: "Ils sont au contraire colinéaires, précisément parce que les trois points sont alignés." },
    { enonce: "Deux vecteurs directeurs différents d'une même droite ne sont colinéaires que s'ils ont la même norme.", reponse: false, justification: "La colinéarité ne dépend pas de la norme, seulement de la direction commune à la droite." },
  ],
  orthogonalite: [
    { enonce: "Deux vecteurs vec(u)(ux ; uy) et vec(v)(vx ; vy) sont orthogonaux si et seulement si ux·vx + uy·vy = 0.", reponse: true, justification: "C'est le critère du produit scalaire nul pour l'orthogonalité." },
    { enonce: "Un triangle ABC est rectangle en A si et seulement si vec(AB)·vec(AC) = 0.", reponse: true, justification: "L'angle en A est droit exactement quand les deux côtés issus de A sont orthogonaux." },
    { enonce: "vec(u) = (3 ; 4) et vec(v) = (4 ; −3) sont orthogonaux.", reponse: true, justification: "3×4 + 4×(−3) = 12 − 12 = 0." },
    { enonce: "Le vecteur nul est orthogonal à tout autre vecteur.", reponse: true, justification: "Le produit scalaire avec le vecteur nul vaut toujours 0." },
    { enonce: "On peut aussi prouver qu'un triangle est rectangle en A en vérifiant BC² = AB² + AC² (Pythagore).", reponse: true, justification: "C'est une méthode alternative équivalente au produit scalaire." },
    { enonce: "Deux vecteurs non nuls ne peuvent pas être à la fois colinéaires et orthogonaux.", reponse: true, justification: "Colinéaire (déterminant nul) et orthogonal (produit scalaire nul) simultanément forcerait l'un des deux vecteurs à être nul." },
    { enonce: "Si vec(u)·vec(v) = 0 et que vec(u) et vec(v) sont tous deux non nuls, alors ils forment un angle droit.", reponse: true, justification: "C'est la définition même de l'orthogonalité entre deux vecteurs non nuls." },
    { enonce: "Pour tester si un triangle ABC est rectangle en B, il faut utiliser les vecteurs vec(BA) et vec(BC).", reponse: true, justification: "L'angle testé est celui du sommet B, donc les deux côtés issus de B." },
    { enonce: "vec(u) = (1 ; 2) et vec(v) = (−2 ; 1) sont orthogonaux.", reponse: true, justification: "1×(−2) + 2×1 = −2 + 2 = 0." },
    { enonce: "L'ordre des deux vecteurs dans le calcul du produit ux·vx + uy·vy ne change pas le résultat.", reponse: true, justification: "Le produit scalaire est commutatif." },
    { enonce: "Deux vecteurs vec(u)(ux ; uy) et vec(v)(vx ; vy) sont orthogonaux si et seulement si ux·vy − uy·vx = 0.", reponse: false, justification: "Cette formule (déterminant) teste la colinéarité, pas l'orthogonalité." },
    { enonce: "Un triangle ABC est rectangle en A si et seulement si vec(AB) et vec(AC) sont colinéaires.", reponse: false, justification: "Des vecteurs colinéaires donneraient un triangle aplati, pas un angle droit." },
    { enonce: "vec(u) = (3 ; 4) et vec(v) = (4 ; −3) sont colinéaires mais pas orthogonaux.", reponse: false, justification: "3×(−3) − 4×4 = −25 ≠ 0 : ils ne sont pas colinéaires (ils sont en fait orthogonaux)." },
    { enonce: "Le vecteur nul n'est jamais orthogonal à un autre vecteur.", reponse: false, justification: "Le produit scalaire avec le vecteur nul est toujours 0, il est donc orthogonal à tout vecteur." },
    { enonce: "La seule façon de prouver qu'un triangle est rectangle en A est de calculer vec(AB)·vec(AC).", reponse: false, justification: "Pythagore (BC² = AB² + AC²) est une méthode alternative tout aussi valable." },
    { enonce: "Deux vecteurs non nuls peuvent être à la fois colinéaires et orthogonaux.", reponse: false, justification: "C'est impossible pour des vecteurs non nuls : les deux conditions se contredisent." },
    { enonce: "Si vec(u)·vec(v) = 0, alors au moins l'un des deux vecteurs est nécessairement le vecteur nul.", reponse: false, justification: "Deux vecteurs non nuls perpendiculaires ont aussi un produit scalaire nul." },
    { enonce: "Pour tester si un triangle ABC est rectangle en B, il faut utiliser les vecteurs vec(AB) et vec(AC).", reponse: false, justification: "Ces vecteurs testent l'angle en A, pas en B — il faut vec(BA) et vec(BC)." },
    { enonce: "vec(u) = (1 ; 2) et vec(v) = (−2 ; 1) sont colinéaires.", reponse: false, justification: "1×1 − 2×(−2) = 1 + 4 = 5 ≠ 0 : ils ne sont pas colinéaires (ils sont en fait orthogonaux)." },
    { enonce: "Le produit ux·vx + uy·vy dépend de l'ordre dans lequel on écrit les deux vecteurs.", reponse: false, justification: "Le produit scalaire est commutatif : l'ordre n'a aucune importance." },
    { enonce: "vec(u) = (5 ; 2) et vec(v) = (2 ; −5) sont orthogonaux.", reponse: true, justification: "5×2 + 2×(−5) = 10 − 10 = 0." },
    { enonce: "vec(u) = (6 ; −3) et vec(v) = (1 ; 2) sont orthogonaux.", reponse: true, justification: "6×1 + (−3)×2 = 6 − 6 = 0." },
    { enonce: "Le triangle A(0 ; 0), B(4 ; 0), C(0 ; 3) est rectangle en A.", reponse: true, justification: "vec(AB)=(4;0) et vec(AC)=(0;3) : 4×0 + 0×3 = 0." },
    { enonce: "Si vec(u)·vec(v) > 0 (avec vec(u) et vec(v) non nuls), alors l'angle entre les deux vecteurs est aigu.", reponse: true, justification: "Le signe du produit scalaire indique la nature de l'angle : positif signifie un angle strictement inférieur à 90°." },
    { enonce: "Si vec(u)·vec(v) < 0 (avec vec(u) et vec(v) non nuls), alors l'angle entre les deux vecteurs est obtus.", reponse: true, justification: "Un produit scalaire négatif signifie un angle strictement supérieur à 90°." },
    { enonce: "vec(u) = (7 ; 0) et vec(v) = (0 ; −4) sont orthogonaux.", reponse: true, justification: "7×0 + 0×(−4) = 0." },
    { enonce: "vec(u) = (−3 ; 6) et vec(v) = (4 ; 2) sont orthogonaux.", reponse: true, justification: "(−3)×4 + 6×2 = −12 + 12 = 0." },
    { enonce: "Dans un repère orthonormé, deux vecteurs directeurs de deux droites perpendiculaires ont un produit scalaire nul.", reponse: true, justification: "Des droites perpendiculaires forment un angle droit, ce qui se traduit exactement par un produit scalaire nul entre leurs vecteurs directeurs." },
    { enonce: "vec(u) = (5 ; 2) et vec(v) = (2 ; −5) ne sont pas orthogonaux.", reponse: false, justification: "5×2 + 2×(−5) = 0 : ils sont bien orthogonaux." },
    { enonce: "vec(u) = (6 ; −3) et vec(v) = (1 ; 2) ont un produit scalaire égal à 12.", reponse: false, justification: "6×1 + (−3)×2 = 0, pas 12 : ces deux vecteurs sont en réalité orthogonaux." },
    { enonce: "Le triangle A(0 ; 0), B(4 ; 0), C(1 ; 3) est rectangle en B.", reponse: false, justification: "vec(BA)=(−4;0) et vec(BC)=(−3;3) : (−4)×(−3) + 0×3 = 12 ≠ 0, l'angle en B n'est pas droit." },
    { enonce: "Si vec(u)·vec(v) > 0, l'angle entre les deux vecteurs est nécessairement obtus.", reponse: false, justification: "Un produit scalaire positif correspond à un angle aigu, pas obtus." },
    { enonce: "vec(u) = (7 ; 0) et vec(v) = (0 ; −4) ne sont pas orthogonaux.", reponse: false, justification: "7×0 + 0×(−4) = 0 : ils sont bien orthogonaux." },
    { enonce: "vec(u) = (−3 ; 6) et vec(v) = (4 ; 2) ont un produit scalaire égal à −4.", reponse: false, justification: "(−3)×4 + 6×2 = 0, pas −4." },
    { enonce: "Dans un repère orthonormé, deux droites perpendiculaires ont des vecteurs directeurs colinéaires entre eux.", reponse: false, justification: "Leurs vecteurs directeurs sont orthogonaux, pas colinéaires (sauf cas impossible pour des vecteurs non nuls)." },
  ],
  normeDistance: [
    { enonce: "La norme de vec(u) = (ux ; uy) vaut √(ux² + uy²).", reponse: true, justification: "Définition de la norme d'un vecteur, via Pythagore." },
    { enonce: "La distance entre A(xA ; yA) et B(xB ; yB) est égale à la norme de vec(AB).", reponse: true, justification: "La distance entre deux points est exactement la longueur du vecteur qui les relie." },
    { enonce: "vec(u) = (3 ; 4) a pour norme 5.", reponse: true, justification: "√(3²+4²) = √25 = 5 (triangle 3-4-5)." },
    { enonce: "La distance entre A(1 ; 1) et B(4 ; 5) vaut 5.", reponse: true, justification: "√((4−1)²+(5−1)²) = √(9+16) = √25 = 5." },
    { enonce: "Une norme est toujours positive ou nulle, jamais négative.", reponse: true, justification: "Une norme est une racine carrée d'une somme de carrés, donc toujours ≥ 0." },
    { enonce: "||vec(u)|| = 0 si et seulement si vec(u) est le vecteur nul.", reponse: true, justification: "Seul le vecteur (0;0) a une norme nulle." },
    { enonce: "La norme de k·vec(u) vaut |k| fois la norme de vec(u).", reponse: true, justification: "Multiplier chaque composante par k multiplie la norme par |k|." },
    { enonce: "Un triangle isocèle a (au moins) deux côtés de même longueur.", reponse: true, justification: "C'est la définition d'un triangle isocèle." },
    { enonce: "Un triangle scalène a ses trois côtés de longueurs différentes.", reponse: true, justification: "C'est la définition d'un triangle scalène." },
    { enonce: "Le théorème de Pythagore peut servir de méthode alternative pour vérifier qu'un triangle est rectangle, sans passer par le produit scalaire.", reponse: true, justification: "Comparer BC² à AB²+AC² est une méthode équivalente au produit scalaire nul." },
    { enonce: "La norme de vec(u) = (ux ; uy) vaut ux² + uy² (sans racine carrée).", reponse: false, justification: "Il manque la racine carrée : la norme est √(ux²+uy²)." },
    { enonce: "La distance entre A(xA ; yA) et B(xB ; yB) est égale à la somme des composantes de vec(AB).", reponse: false, justification: "La distance est la norme (racine de la somme des carrés), pas la somme simple des composantes." },
    { enonce: "vec(u) = (3 ; 4) a pour norme 7.", reponse: false, justification: "La norme vaut √(3²+4²) = 5, pas 7 (3+4)." },
    { enonce: "La distance entre A(1 ; 1) et B(4 ; 5) vaut 4.", reponse: false, justification: "Le bon résultat est 5 (triangle 3-4-5), pas 4." },
    { enonce: "Une norme peut être négative si le vecteur pointe vers la gauche ou vers le bas.", reponse: false, justification: "La norme est toujours positive ou nulle, quelle que soit l'orientation du vecteur." },
    { enonce: "||vec(u)|| = 0 est possible même si vec(u) n'est pas le vecteur nul.", reponse: false, justification: "Une norme nulle impose que toutes les composantes soient nulles." },
    { enonce: "La norme de k·vec(u) vaut k fois la norme de vec(u), même si k est négatif (sans valeur absolue).", reponse: false, justification: "Une norme est toujours positive : il faut la valeur absolue de k, sinon on obtiendrait une norme négative pour k<0." },
    { enonce: "Un triangle isocèle a ses trois côtés de longueurs différentes.", reponse: false, justification: "C'est la définition d'un triangle scalène, pas isocèle." },
    { enonce: "Un triangle scalène a (au moins) deux côtés de même longueur.", reponse: false, justification: "C'est la définition d'un triangle isocèle, pas scalène." },
    { enonce: "Le théorème de Pythagore ne peut jamais remplacer le produit scalaire pour tester l'orthogonalité.", reponse: false, justification: "Il peut au contraire servir de méthode alternative équivalente, pour un triangle rectangle." },
    { enonce: "vec(u) = (6 ; 8) a pour norme 10.", reponse: true, justification: "√(6²+8²) = √100 = 10." },
    { enonce: "vec(u) = (5 ; 12) a pour norme 13.", reponse: true, justification: "√(5²+12²) = √169 = 13." },
    { enonce: "La distance entre A(2 ; 3) et B(2 ; 7) vaut 4.", reponse: true, justification: "√((2−2)²+(7−3)²) = √16 = 4." },
    { enonce: "La distance entre A(−1 ; −1) et B(2 ; 3) vaut 5.", reponse: true, justification: "√((2−(−1))²+(3−(−1))²) = √(9+16) = √25 = 5." },
    { enonce: "Si A et B sont confondus, la distance entre A et B vaut 0.", reponse: true, justification: "vec(AB) est alors le vecteur nul, de norme 0." },
    { enonce: "vec(u) = (−6 ; 8) a pour norme 10, tout comme vec(v) = (6 ; 8).", reponse: true, justification: "La norme dépend des carrés des composantes : le signe n'a pas d'influence, √((−6)²+8²) = √(6²+8²) = 10." },
    { enonce: "Pour un triangle de sommets A(0 ; 0), B(3 ; 0), C(0 ; 4), le côté BC a une longueur de 5.", reponse: true, justification: "vec(BC) = (0−3 ; 4−0) = (−3;4), de norme √(9+16) = 5." },
    { enonce: "Si ||vec(u)|| = ||vec(v)||, cela ne signifie pas que vec(u) = vec(v).", reponse: true, justification: "Deux vecteurs de même norme peuvent avoir des directions ou des sens différents." },
    { enonce: "vec(u) = (6 ; 8) a pour norme 14.", reponse: false, justification: "√(6²+8²) = 10, pas 14 (14 serait la somme des composantes, pas la norme)." },
    { enonce: "vec(u) = (5 ; 12) a pour norme 17.", reponse: false, justification: "√(5²+12²) = 13, pas 17 (17 serait la somme des composantes, pas la norme)." },
    { enonce: "La distance entre A(2 ; 3) et B(2 ; 7) vaut 16.", reponse: false, justification: "16 est le carré de la différence des ordonnées ; il manque la racine carrée : la distance correcte est 4." },
    { enonce: "La distance entre A(−1 ; −1) et B(2 ; 3) vaut 7.", reponse: false, justification: "7 est la somme des écarts (3+4) ; la distance correcte, via Pythagore, est √(9+16) = 5." },
    { enonce: "Si A et B sont confondus, la distance entre A et B est indéfinie.", reponse: false, justification: "La distance vaut simplement 0 dans ce cas, elle reste parfaitement définie." },
    { enonce: "Pour un triangle de sommets A(0 ; 0), B(3 ; 0), C(0 ; 4), le côté BC a une longueur de 7.", reponse: false, justification: "7 serait la somme de AB et AC ; la longueur correcte de BC, par Pythagore, est √(3²+4²) = 5." },
    { enonce: "Si ||vec(u)|| = ||vec(v)||, alors vec(u) = vec(v) nécessairement.", reponse: false, justification: "L'égalité des normes n'entraîne pas l'égalité des vecteurs : leur direction ou leur sens peuvent différer." },
  ],
  chasles: [
    { enonce: "La relation de Chasles s'écrit vec(AB) + vec(BC) = vec(AC).", reponse: true, justification: "C'est l'identité fondamentale de la relation de Chasles." },
    { enonce: "Une chaîne de vecteurs vec(A1A2) + vec(A2A3) + ... + vec(An−1An) se réduit à vec(A1An).", reponse: true, justification: "Application répétée de la relation de Chasles, les points intermédiaires s'éliminent." },
    { enonce: "Si une chaîne de vecteurs revient à son point de départ (A1 = An), sa somme vaut le vecteur nul.", reponse: true, justification: "La chaîne se réduit à vec(A1An) = vec(A1A1) = vec(0)." },
    { enonce: "La relation de Chasles est toujours vraie, quelle que soit la position réelle des points sur la figure.", reponse: true, justification: "C'est une identité algébrique générale, indépendante de la figure dessinée." },
    { enonce: "Pour que deux vecteurs consécutifs d'une chaîne se télescopent, le point d'arrivée du premier doit être le point de départ du second.", reponse: true, justification: "C'est la condition nécessaire pour appliquer la relation de Chasles entre deux vecteurs." },
    { enonce: "vec(AB) + vec(BC) + vec(CD) + vec(DA) = vec(0).", reponse: true, justification: "La chaîne fermée A→B→C→D→A se réduit à vec(AA) = vec(0)." },
    { enonce: "Si un vecteur de la chaîne est écrit à l'envers (par exemple vec(CB) au lieu de vec(BC)), il faut le remplacer par −vec(BC) avant de télescoper.", reponse: true, justification: "vec(CB) = −vec(BC) ; il faut réécrire le vecteur dans le bon sens pour pouvoir télescoper." },
    { enonce: "La relation de Chasles permet de réduire une expression comportant de nombreux vecteurs à un seul vecteur final.", reponse: true, justification: "C'est précisément l'utilité de la relation de Chasles pour réduire une chaîne." },
    { enonce: "vec(AB) − vec(AC) peut se réécrire vec(CB) grâce à la relation de Chasles.", reponse: true, justification: "vec(AB) − vec(AC) = vec(CA) + vec(AB) = vec(CB)." },
    { enonce: "Sur une figure fermée (comme un hexagone), la somme de tous les vecteurs qui en font le tour dans le même sens est le vecteur nul.", reponse: true, justification: "Faire le tour complet ramène au point de départ, la somme se réduit donc à vec(0)." },
    { enonce: "La relation de Chasles s'écrit vec(AB) + vec(BC) = vec(BA).", reponse: false, justification: "Le résultat correct est vec(AC), pas vec(BA)." },
    { enonce: "Une chaîne de vecteurs vec(A1A2) + vec(A2A3) + ... + vec(An−1An) se réduit à vec(AnA1) (sens inversé).", reponse: false, justification: "Le résultat correct est vec(A1An), dans le sens du point de départ vers le point d'arrivée." },
    { enonce: "Si une chaîne de vecteurs revient à son point de départ, sa somme est toujours différente du vecteur nul.", reponse: false, justification: "Au contraire, une chaîne fermée se réduit toujours au vecteur nul." },
    { enonce: "La relation de Chasles n'est valable que sur des figures régulières comme l'hexagone.", reponse: false, justification: "C'est une identité algébrique valable pour n'importe quels points, régulière ou non." },
    { enonce: "Pour que deux vecteurs consécutifs d'une chaîne se télescopent, il suffit qu'ils aient la même norme.", reponse: false, justification: "Ce qui compte, c'est que le point d'arrivée du premier soit le point de départ du second — la norme n'a rien à voir." },
    { enonce: "vec(AB) + vec(BC) + vec(CD) + vec(DA) est toujours un vecteur non nul.", reponse: false, justification: "Cette chaîne fermée se réduit toujours au vecteur nul." },
    { enonce: "Un vecteur écrit à l'envers dans une chaîne (par exemple vec(CB) au lieu de vec(BC)) peut être télescopé sans le modifier.", reponse: false, justification: "Il faut d'abord le remplacer par son opposé (−vec(BC)) pour pouvoir télescoper correctement." },
    { enonce: "La relation de Chasles ne fonctionne que pour des chaînes de 2 vecteurs, jamais plus.", reponse: false, justification: "Elle s'applique de proche en proche à des chaînes de longueur quelconque." },
    { enonce: "vec(AB) − vec(AC) se réécrit vec(BC) grâce à la relation de Chasles.", reponse: false, justification: "Le résultat correct est vec(CB), pas vec(BC) — l'ordre est inversé." },
    { enonce: "Sur une figure fermée, la somme des vecteurs qui en font le tour dépend du point de départ choisi.", reponse: false, justification: "Le résultat est toujours le vecteur nul, quel que soit le point de départ choisi pour faire le tour." },
    { enonce: "vec(AB) + vec(BC) + vec(CA) = vec(0).", reponse: true, justification: "La chaîne fermée A→B→C→A se réduit à vec(AA) = vec(0)." },
    { enonce: "vec(AB) + vec(BC) + vec(CD) + vec(DE) = vec(AE).", reponse: true, justification: "Application répétée de la relation de Chasles : les points intermédiaires B, C, D s'éliminent." },
    { enonce: "2·vec(AB) + 2·vec(BC) = 2·vec(AC).", reponse: true, justification: "2·vec(AB) + 2·vec(BC) = 2·(vec(AB)+vec(BC)) = 2·vec(AC)." },
    { enonce: "vec(AB) + vec(BA) = vec(0).", reponse: true, justification: "La chaîne fermée A→B→A se réduit à vec(AA) = vec(0)." },
    { enonce: "Si vec(AB) + vec(BC) + vec(CD) = vec(0), alors D est confondu avec A.", reponse: true, justification: "La chaîne se réduit à vec(AD) = vec(0), donc D est confondu avec A." },
    { enonce: "vec(MA) + vec(AB) = vec(MB), quel que soit le point M choisi.", reponse: true, justification: "C'est la relation de Chasles appliquée à la chaîne M→A→B, valable pour n'importe quel point M." },
    { enonce: "vec(AB) − vec(CB) peut se réécrire vec(AC) grâce à la relation de Chasles.", reponse: true, justification: "vec(AB) − vec(CB) = vec(AB) + vec(BC) = vec(AC)." },
    { enonce: "Sur un pentagone ABCDE parcouru dans l'ordre des sommets, vec(AB)+vec(BC)+vec(CD)+vec(DE)+vec(EA) = vec(0).", reponse: true, justification: "C'est une chaîne fermée qui revient à son point de départ A, elle se réduit donc au vecteur nul." },
    { enonce: "vec(AB) + vec(BC) + vec(CA) = vec(AC).", reponse: false, justification: "Cette chaîne fermée se réduit au vecteur nul, pas à vec(AC)." },
    { enonce: "vec(AB) + vec(BC) + vec(CD) + vec(DE) = vec(AD) (le point E n'intervient pas dans le résultat).", reponse: false, justification: "Le télescopage donne vec(AE) : le point d'arrivée final E doit apparaître dans le résultat." },
    { enonce: "2·vec(AB) + 2·vec(BC) = vec(AC) (le facteur 2 disparaît lors du télescopage).", reponse: false, justification: "Il faut conserver le facteur commun : le résultat correct est 2·vec(AC), pas vec(AC)." },
    { enonce: "vec(AB) + vec(BA) = 2·vec(AB).", reponse: false, justification: "vec(BA) = −vec(AB), donc la somme vaut vec(0), pas 2·vec(AB)." },
    { enonce: "Si vec(AB) + vec(BC) + vec(CD) = vec(0), alors D est nécessairement confondu avec B.", reponse: false, justification: "La chaîne se réduit à vec(AD) = vec(0) : D est confondu avec A, pas avec B." },
    { enonce: "vec(MA) + vec(AB) = vec(MB) seulement si M est le milieu de [AB].", reponse: false, justification: "Cette relation de Chasles est vraie pour n'importe quel point M, sans condition particulière." },
    { enonce: "vec(AB) − vec(CB) se réécrit vec(BC) grâce à la relation de Chasles.", reponse: false, justification: "Le résultat correct est vec(AC), pas vec(BC)." },
  ],
  comparaisonVisuelle: [
    { enonce: "Deux vecteurs colinéaires ont toujours la même direction.", reponse: true, justification: "C'est la définition même de la colinéarité." },
    { enonce: "Deux vecteurs de même sens sont nécessairement colinéaires.", reponse: true, justification: "Avoir un sens comparable suppose déjà d'être sur des droites parallèles, donc colinéaires." },
    { enonce: "Un vecteur vec(u) et son opposé −vec(u) ont la même direction mais un sens opposé.", reponse: true, justification: "L'opposé conserve la droite support mais inverse l'orientation." },
    { enonce: "Un vecteur vec(u) et son opposé −vec(u) ont la même norme.", reponse: true, justification: "||−vec(u)|| = |−1|·||vec(u)|| = ||vec(u)||." },
    { enonce: "Deux vecteurs peuvent avoir le même sens sans avoir la même longueur.", reponse: true, justification: "Le sens ne dit rien sur la longueur — par exemple vec(u) et 3·vec(u) ont le même sens mais des longueurs différentes." },
    { enonce: "Deux vecteurs égaux partagent nécessairement la même longueur, la même direction et le même sens.", reponse: true, justification: "C'est la définition même de l'égalité de deux vecteurs." },
    { enonce: "Deux vecteurs de même longueur ne sont pas forcément colinéaires.", reponse: true, justification: "Deux vecteurs peuvent avoir la même norme tout en pointant dans des directions complètement différentes." },
    { enonce: "Un vecteur multiplié par un coefficient positif garde le même sens que le vecteur d'origine.", reponse: true, justification: "Un coefficient positif ne change jamais le sens, seulement la longueur." },
    { enonce: "Un vecteur multiplié par un coefficient négatif prend le sens opposé au vecteur d'origine.", reponse: true, justification: "Un coefficient négatif inverse systématiquement le sens." },
    { enonce: "Deux vecteurs peuvent partager la même direction sans partager le même sens.", reponse: true, justification: "Deux vecteurs colinéaires de coefficient négatif ont la même direction mais des sens opposés." },
    { enonce: "Deux vecteurs colinéaires ont nécessairement des directions différentes.", reponse: false, justification: "C'est l'inverse : la colinéarité impose la même direction." },
    { enonce: "Deux vecteurs de même sens ne sont jamais colinéaires.", reponse: false, justification: "Avoir le même sens implique justement d'être colinéaires." },
    { enonce: "Un vecteur vec(u) et son opposé −vec(u) ont des directions différentes.", reponse: false, justification: "Ils partagent la même direction (même droite support), seul le sens diffère." },
    { enonce: "Un vecteur vec(u) et son opposé −vec(u) n'ont jamais la même norme.", reponse: false, justification: "Au contraire, un vecteur et son opposé ont toujours exactement la même norme." },
    { enonce: "Deux vecteurs de même sens ont automatiquement la même longueur.", reponse: false, justification: "Le sens ne détermine pas la longueur : deux vecteurs de même sens peuvent avoir des normes très différentes." },
    { enonce: "Deux vecteurs égaux peuvent avoir des longueurs différentes, tant que leur direction est la même.", reponse: false, justification: "Deux vecteurs égaux ont, par définition, la même longueur, la même direction et le même sens." },
    { enonce: "Deux vecteurs de même longueur sont automatiquement colinéaires.", reponse: false, justification: "La longueur seule ne dit rien sur la direction : deux vecteurs de même norme peuvent pointer dans des directions différentes." },
    { enonce: "Un vecteur multiplié par un coefficient positif change systématiquement de sens.", reponse: false, justification: "Un coefficient positif conserve toujours le sens d'origine." },
    { enonce: "Un vecteur multiplié par un coefficient négatif garde le même sens que le vecteur d'origine.", reponse: false, justification: "Un coefficient négatif inverse toujours le sens." },
    { enonce: "Deux vecteurs qui partagent la même direction partagent automatiquement le même sens.", reponse: false, justification: "Ils peuvent aussi être de sens opposés tout en partageant la même direction (droite support)." },
    { enonce: "Si deux vecteurs ont la même direction et la même norme, ils sont soit égaux, soit opposés.", reponse: true, justification: "Même direction et même norme ne fixent pas le sens : celui-ci peut être identique (vecteurs égaux) ou contraire (vecteurs opposés)." },
    { enonce: "Un vecteur et son double (2·vec(u)) ont toujours la même direction et le même sens.", reponse: true, justification: "Un coefficient positif (2) conserve à la fois la direction et le sens." },
    { enonce: "Un vecteur vec(u) non nul et le vecteur (−3)·vec(u) ont des sens opposés mais la même direction.", reponse: true, justification: "Le coefficient négatif inverse le sens sans changer la droite support." },
    { enonce: "Si vec(u) et vec(v) ont la même norme mais des directions différentes, ils ne peuvent pas être égaux.", reponse: true, justification: "Deux vecteurs égaux doivent obligatoirement partager la même direction." },
    { enonce: "Trois vecteurs peuvent avoir tous la même norme sans être colinéaires entre eux.", reponse: true, justification: "La norme commune ne dit rien sur les directions respectives des trois vecteurs." },
    { enonce: "Si vec(u) = k·vec(v) avec k > 0, alors vec(u) et vec(v) ont le même sens.", reponse: true, justification: "Un coefficient strictement positif conserve toujours le sens du vecteur d'origine." },
    { enonce: "Si vec(u) = k·vec(v) avec k < 0, alors vec(u) et vec(v) ont des sens opposés mais la même direction.", reponse: true, justification: "Un coefficient négatif inverse le sens tout en conservant la droite support." },
    { enonce: "Deux vecteurs peuvent avoir des sens opposés tout en ayant des normes différentes.", reponse: true, justification: "Le sens ne détermine pas la longueur : deux vecteurs de sens opposés peuvent avoir des normes quelconques." },
    { enonce: "Si deux vecteurs ont la même direction et la même norme, ils sont nécessairement égaux, jamais opposés.", reponse: false, justification: "Ils peuvent aussi être opposés : même direction et même norme n'imposent rien sur le sens." },
    { enonce: "Un vecteur et son double (2·vec(u)) peuvent avoir des sens opposés.", reponse: false, justification: "Multiplier par un coefficient positif (ici 2) conserve toujours le sens d'origine." },
    { enonce: "Un vecteur vec(u) non nul et le vecteur (−3)·vec(u) ont la même direction et le même sens.", reponse: false, justification: "Le coefficient négatif inverse le sens ; seule la direction reste identique." },
    { enonce: "Si vec(u) et vec(v) ont la même norme mais des directions différentes, ils peuvent malgré tout être égaux.", reponse: false, justification: "Des directions différentes excluent l'égalité : deux vecteurs égaux partagent nécessairement la même direction." },
    { enonce: "Trois vecteurs de même norme sont automatiquement colinéaires entre eux.", reponse: false, justification: "La norme commune ne dit rien sur leur direction respective : ils peuvent très bien ne pas être colinéaires." },
    { enonce: "Si vec(u) = k·vec(v) avec k > 0, alors vec(u) et vec(v) ont nécessairement des sens opposés.", reponse: false, justification: "Un coefficient positif conserve le sens, il ne l'inverse jamais." },
    { enonce: "Deux vecteurs de sens opposés ont obligatoirement la même norme.", reponse: false, justification: "Le sens opposé n'impose rien sur la longueur : les deux normes peuvent être différentes." },
  ],
  applicationsPhysiques: [
    { enonce: "La résultante de deux vecteurs vec(v1) et vec(v2) est leur somme vectorielle vec(v1) + vec(v2).", reponse: true, justification: "C'est la définition physique de la résultante." },
    { enonce: "Si les deux vecteurs sont colinéaires et de même sens, la norme de la résultante est la somme de leurs deux normes.", reponse: true, justification: "Dans ce cas particulier, l'inégalité triangulaire devient une égalité." },
    { enonce: "Si les deux vecteurs sont perpendiculaires, la norme de la résultante se calcule par le théorème de Pythagore.", reponse: true, justification: "Un cas particulier de la loi des cosinus, quand l'angle entre les vecteurs vaut 90°." },
    { enonce: "En général, la norme de la résultante de deux vecteurs dépend de l'angle qu'ils forment entre eux.", reponse: true, justification: "L'angle influence directement la longueur du troisième côté du triangle formé par les deux vecteurs." },
    { enonce: "La loi des cosinus permet de calculer la norme de la résultante connaissant les deux normes et l'angle entre les vecteurs.", reponse: true, justification: "C'est exactement l'usage de la loi des cosinus dans ce contexte (chapitre 3)." },
    { enonce: "Pour un problème de forces (par exemple deux forces F1 et F2), la notation de la résultante est vec(FR).", reponse: true, justification: "La notation reste cohérente avec les vecteurs d'origine, ici les forces F." },
    { enonce: "Pour un problème de vitesses (par exemple avion et vent), la notation de la résultante est vec(vR).", reponse: true, justification: "La notation reste cohérente avec les vecteurs d'origine, ici les vitesses v." },
    { enonce: "La déviation est l'écart angulaire entre la direction prévue et la direction réellement suivie sous l'effet du second vecteur.", reponse: true, justification: "C'est la définition de la déviation dans ce type de problème (par exemple un avion dévié par le vent)." },
    { enonce: "La norme de la résultante de deux vecteurs non colinéaires est toujours strictement inférieure à la somme de leurs deux normes.", reponse: true, justification: "Inégalité triangulaire stricte, dès que les deux vecteurs ne sont pas colinéaires de même sens." },
    { enonce: "Traduire un angle en direction cardinale (Nord, Sud-Est, etc.) dépend de la géométrie réelle de la situation, pas d'une règle universelle fixe.", reponse: true, justification: "La correspondance angle-direction cardinale se déduit à chaque fois du contexte précis de la figure." },
    { enonce: "La résultante de deux vecteurs vec(v1) et vec(v2) est leur différence vectorielle vec(v1) − vec(v2).", reponse: false, justification: "La résultante est la somme, pas la différence, des deux vecteurs." },
    { enonce: "Si les deux vecteurs sont colinéaires et de même sens, la norme de la résultante est toujours inférieure à celle de chaque vecteur pris séparément.", reponse: false, justification: "Au contraire, elle est égale à la somme des deux normes, donc supérieure à chacune." },
    { enonce: "Si les deux vecteurs sont perpendiculaires, on ne peut pas calculer la norme de la résultante sans connaître un troisième côté.", reponse: false, justification: "Le théorème de Pythagore permet justement de la calculer directement à partir des deux normes seules." },
    { enonce: "La norme de la résultante de deux vecteurs ne dépend jamais de l'angle qu'ils forment entre eux.", reponse: false, justification: "Elle en dépend fortement : deux mêmes vecteurs donnent des résultantes différentes selon l'angle entre eux." },
    { enonce: "La loi des cosinus ne s'applique qu'aux triangles rectangles, jamais aux triangles quelconques formés par deux vecteurs.", reponse: false, justification: "C'est l'inverse : la loi des cosinus s'applique justement à tout triangle, rectangle ou non." },
    { enonce: "Pour un problème de forces, la résultante se note toujours vec(vR), quel que soit le contexte.", reponse: false, justification: "La notation dépend du contexte : pour des forces, on utilise vec(FR), pas vec(vR)." },
    { enonce: "Pour un problème de vitesses, la résultante se note toujours vec(FR), quel que soit le contexte.", reponse: false, justification: "La notation dépend du contexte : pour des vitesses, on utilise vec(vR), pas vec(FR)." },
    { enonce: "La déviation est la norme totale de la résultante, exprimée en degrés.", reponse: false, justification: "La déviation est un écart angulaire, pas une norme — et une norme ne s'exprime jamais en degrés." },
    { enonce: "La norme de la résultante de deux vecteurs non colinéaires est toujours supérieure ou égale à la somme de leurs deux normes.", reponse: false, justification: "L'inégalité triangulaire dit l'inverse : elle est toujours strictement inférieure à cette somme." },
    { enonce: "La direction cardinale correspondant à un angle donné est toujours la même, indépendamment du contexte de la figure.", reponse: false, justification: "La correspondance dépend de la façon dont la figure et les axes ont été orientés dans chaque situation." },
    { enonce: "Deux forces de normes 3 N et 4 N, perpendiculaires entre elles, ont une résultante de norme 5 N.", reponse: true, justification: "Par Pythagore, √(3²+4²) = √25 = 5." },
    { enonce: "Deux forces colinéaires de même sens, de normes 5 N et 3 N, ont une résultante de norme 8 N.", reponse: true, justification: "Colinéaires et de même sens : les normes s'additionnent, 5+3=8." },
    { enonce: "Deux forces colinéaires de sens opposés, de normes 7 N et 4 N, ont une résultante de norme 3 N.", reponse: true, justification: "Colinéaires et de sens opposés : les normes se soustraient, 7−4=3." },
    { enonce: "Deux vecteurs de normes 5 et 5, formant un angle de 120° entre eux, ont une résultante de norme 5.", reponse: true, justification: "Par la loi des cosinus, R² = 5²+5²+2×5×5×cos(120°) = 50−25 = 25, donc R=5." },
    { enonce: "Si l'angle entre deux vecteurs non nuls augmente de 0° à 180° (à normes fixées), la norme de la résultante est maximale à 0° et diminue ensuite.", reponse: true, justification: "R² = v1²+v2²+2·v1·v2·cos(θ) est maximal quand cos(θ)=1, donc quand θ=0°." },
    { enonce: "Si l'angle entre deux vecteurs non nuls vaut 180°, la norme de la résultante est minimale par rapport à toute autre valeur de cet angle (à normes fixées).", reponse: true, justification: "R² = v1²+v2²+2·v1·v2·cos(θ) est minimal quand cos(θ)=−1, donc quand θ=180°." },
    { enonce: "Un avion volant à une certaine vitesse propre et subissant un vent latéral a une vitesse résultante (vitesse-sol) différente de sa vitesse propre affichée.", reponse: true, justification: "La résultante de la vitesse propre et du vecteur vent diffère de la vitesse propre seule, sauf si le vent est nul." },
    { enonce: "La résultante de deux vecteurs peut être calculée composante par composante, en additionnant séparément leurs abscisses puis leurs ordonnées.", reponse: true, justification: "C'est une méthode alternative à la loi des cosinus, tout aussi valable lorsque les composantes sont connues." },
    { enonce: "Deux forces de normes 3 N et 4 N, perpendiculaires entre elles, ont une résultante de norme 7 N.", reponse: false, justification: "7 N correspondrait à une simple somme des normes ; par Pythagore, la résultante correcte est 5 N." },
    { enonce: "Deux forces colinéaires de même sens, de normes 5 N et 3 N, ont une résultante de norme 2 N.", reponse: false, justification: "2 N correspondrait à une soustraction, réservée aux sens opposés ; ici, de même sens, les normes s'additionnent : 8 N." },
    { enonce: "Deux forces colinéaires de sens opposés, de normes 7 N et 4 N, ont une résultante de norme 11 N.", reponse: false, justification: "11 N correspondrait à une addition, réservée au même sens ; ici, de sens opposés, les normes se soustraient : 3 N." },
    { enonce: "Deux vecteurs de normes 5 et 5, formant un angle de 120° entre eux, ont une résultante de norme 10.", reponse: false, justification: "10 correspondrait à un angle de 0° (même sens) ; à 120°, la loi des cosinus donne une résultante de norme 5." },
    { enonce: "Si l'angle entre deux vecteurs non nuls vaut 0°, la norme de la résultante est minimale par rapport à toute autre valeur de cet angle.", reponse: false, justification: "C'est l'inverse : à 0°, les vecteurs s'additionnent complètement, la résultante est alors maximale." },
    { enonce: "Si l'angle entre deux vecteurs non nuls vaut 180°, la norme de la résultante est maximale par rapport à toute autre valeur de cet angle.", reponse: false, justification: "C'est l'inverse : à 180°, les vecteurs se contrent au maximum, la résultante est alors minimale." },
    { enonce: "La résultante de deux vecteurs ne peut être calculée qu'avec la loi des cosinus, jamais composante par composante.", reponse: false, justification: "La méthode par composantes (additionner abscisses et ordonnées séparément) est tout aussi valable." },
  ],
};
