/**
 * Couche A — banque de questions vrai/faux pour "Géométrie dans l'espace" (gen66). 3 thèmes (un par
 * générateur, gen39-41), 35 affirmations chacun (proche de 50/50 vrai/faux) — mêmes conventions
 * exactes que `core/positionDroitePlan.types.ts`/`core/sectionPlaneSolide.types.ts`/
 * `core/ombreSoleil.types.ts` (classification incluse/parallèle/sécante, principe de section d'un
 * solide convexe, projection parallèle), jamais réinventées ici. Vocabulaire banni côté élève
 * ("déterminant", "produit scalaire") jamais utilisé ici non plus, même règle transversale au
 * chapitre.
 *
 * Les 20 premières affirmations de chaque thème forment la banque d'origine (10 vraies/10 fausses).
 * Les 15 suivantes sont un enrichissement portant sur des nuances non couvertes par les 20
 * premières (candidats distracteurs, invariants de construction, spécificités par gabarit, etc.),
 * vérifiées directement contre `moteur/verificationPositionDroitePlan.ts`/
 * `moteur/verificationSectionPlaneSolide.ts`/`moteur/verificationOmbreSoleil.ts` et les contrats
 * `core/positionDroitePlan.types.ts`/`core/sectionPlaneSolide.types.ts`/`core/ombreSoleil.types.ts`
 * — jamais une simple reformulation d'une affirmation déjà présente dans les 20 premières.
 */
import type { QuestionVraiFaux, VarianteQuizGeometrieEspace } from "../../core/quizGeometrieEspace.types";

const POSITION_DROITE_PLAN: QuestionVraiFaux[] = [
  { enonce: "Une droite est incluse dans un plan si et seulement si deux de ses points distincts appartiennent à ce plan.", reponse: true, justification: "Deux points distincts déterminent la droite ; s'ils sont tous deux dans le plan, la droite entière y est aussi." },
  { enonce: "Si une droite n'est pas incluse dans un plan et que sa direction est parallèle à ce plan, alors elle ne rencontre jamais ce plan.", reponse: true, justification: "Une direction parallèle au plan mais un point hors du plan signifie que la droite reste à distance constante du plan, sans jamais le toucher." },
  { enonce: "Une droite non incluse dans un plan et dont la direction n'est pas parallèle à ce plan est nécessairement sécante à ce plan.", reponse: true, justification: "C'est la troisième et dernière branche de la classification — il n'existe pas de quatrième cas." },
  { enonce: "Dans cet exercice, le plan utilisé pour classer une droite est considéré infini, même si le dessin ne montre qu'une face limitée du solide.", reponse: true, justification: "Le plan géométrique n'est jamais borné aux arêtes du solide dessiné, contrairement à ce que le dessin peut suggérer." },
  { enonce: "Une droite peut être sécante à un plan en un point situé en dehors du solide représenté sur le dessin.", reponse: true, justification: "Le plan étant infini, le point d'intersection peut tomber hors des limites visibles du solide." },
  { enonce: "Pour vérifier qu'une droite est incluse dans un plan, il suffit de vérifier que ses deux extrémités appartiennent au plan.", reponse: true, justification: "Si les deux points de la droite appartiennent au plan, toute la droite y est incluse." },
  { enonce: "Une droite sécante à un plan peut couper ce plan exactement en un sommet du solide.", reponse: true, justification: "Le point d'intersection peut coïncider avec un sommet nommé du solide, un cas explicitement prévu par l'exercice." },
  { enonce: "Une droite peut être sécante à un plan en un point situé strictement à l'intérieur d'une arête du solide, sans coïncider avec aucun sommet.", reponse: true, justification: "C'est également un cas prévu — le point d'intersection tombe alors sur une arête, entre ses deux extrémités." },
  { enonce: "Si une droite est incluse dans un plan, alors chacun de ses points appartient à ce plan.", reponse: true, justification: "C'est la définition même de l'inclusion d'une droite dans un plan." },
  { enonce: "La position d'une droite par rapport à un plan appartient toujours à exactement une des trois catégories : incluse, parallèle ou sécante.", reponse: true, justification: "Ces trois catégories sont exhaustives et s'excluent mutuellement — il n'y a pas de quatrième cas possible." },
  { enonce: "Une droite dont un seul point appartient à un plan est automatiquement incluse dans ce plan.", reponse: false, justification: "Un seul point commun ne suffit pas — il faut les DEUX points de la droite dans le plan pour qu'elle y soit incluse." },
  { enonce: "Une droite parallèle à un plan a nécessairement au moins un point commun avec ce plan.", reponse: false, justification: "Une droite strictement parallèle à un plan (non incluse) n'a par définition aucun point commun avec lui." },
  { enonce: "Si la direction d'une droite est parallèle à un plan, la droite est nécessairement incluse dans ce plan.", reponse: false, justification: "Une direction parallèle au plan n'implique pas l'inclusion — la droite peut rester parallèle sans être incluse, si un seul de ses points s'écarte du plan." },
  { enonce: "Une droite sécante à un plan coupe ce plan en une infinité de points.", reponse: false, justification: "Une droite non incluse dans un plan et non parallèle à celui-ci le coupe en un unique point." },
  { enonce: "Le point d'intersection entre une droite sécante et un plan est toujours situé à l'intérieur du solide dessiné.", reponse: false, justification: "Le plan étant considéré infini, ce point peut très bien tomber hors du solide représenté." },
  { enonce: "Deux droites de même direction, dont l'une est incluse dans un plan, sont nécessairement toutes les deux incluses dans ce plan.", reponse: false, justification: "Une droite parallèle à la première mais passant par un point hors du plan n'est que parallèle au plan, jamais incluse." },
  { enonce: "La position d'une droite par rapport à un plan dépend de la taille du solide dessiné, pas seulement du plan et de la droite eux-mêmes.", reponse: false, justification: "La classification incluse/parallèle/sécante est une propriété purement géométrique du plan et de la droite (supposés infinis), indépendante de la portion de solide représentée." },
  { enonce: "Une droite parallèle à un plan, non incluse dans celui-ci, finit toujours par le couper si on la prolonge suffisamment loin.", reponse: false, justification: "Par définition, une droite parallèle à un plan sans y être incluse ne le rencontre jamais, même prolongée à l'infini." },
  { enonce: "Il est possible qu'une droite ne soit ni incluse, ni parallèle, ni sécante à un plan donné.", reponse: false, justification: "Ces trois catégories sont exhaustives : toute droite de l'espace appartient obligatoirement à l'une d'elles." },
  { enonce: "Une droite incluse dans un plan est un cas particulier de droite sécante à ce plan.", reponse: false, justification: "Incluse et sécante sont deux catégories disjointes et exclusives, jamais l'une un cas particulier de l'autre." },

  // --- Enrichissement (15 affirmations supplémentaires, nuances non couvertes ci-dessus) ---
  { enonce: "Lorsque la classification trouvée à l'écran 1 est « incluse », l'écran suivant demande de sélectionner les deux sommets qui définissent la droite, jamais un candidat parmi une liste de segments ou de cibles.", reponse: true, justification: "La forme de la question du second écran dépend directement de la catégorie trouvée au premier écran — le cas « incluse » se justifie par les deux sommets de la droite, jamais par un choix parmi des candidats." },
  { enonce: "Pour le cas « parallèle », un seul segment candidat est proposé à l'élève : celui qui est réellement parallèle à la droite.", reponse: false, justification: "Au moins trois candidats sont toujours proposés pour ce cas, un seul étant réellement parallèle à la droite — les autres servent de distracteurs." },
  { enonce: "Parmi les candidats proposés pour le cas « parallèle », plusieurs peuvent porter des étiquettes différentes (« arête AB », « diagonale AC ») sans qu'aucune de leurs directions ne coïncide avec celle de la droite, sauf celle du candidat correct.", reponse: true, justification: "Les candidats distracteurs sont choisis parmi les arêtes et diagonales du solide dont la direction diffère de la droite ; un seul partage réellement sa direction." },
  { enonce: "Une diagonale d'une face ne peut jamais servir de segment candidat pour le cas « parallèle » ; seules les arêtes du solide sont proposées.", reponse: false, justification: "Les diagonales d'une face sont aussi des segments candidats valables pour ce cas, au même titre que les arêtes — l'étiquette « diagonale AC » en est un exemple prévu par l'exercice." },
  { enonce: "Pour le cas « sécante », la cible désignée par l'élève peut être un sommet nommé du solide ou une arête entière, mais jamais une face.", reponse: true, justification: "Les deux seuls types de cibles prévus pour ce cas sont le sommet et l'arête — une face n'est jamais une cible possible, même si le point d'intersection s'y trouve." },
  { enonce: "Pour le cas « sécante », il est possible que le point d'intersection réel ne corresponde à aucun des candidats proposés.", reponse: false, justification: "L'exercice garantit toujours qu'un des candidats proposés correspond exactement au point d'intersection réel — ce cas est écarté dès la construction de l'exercice." },
  { enonce: "Si l'élève trouve la bonne classification « incluse » à l'écran 1 mais choisit ensuite, à l'écran 2, une réponse de type « sécante », cette réponse est rejetée automatiquement, quel que soit le candidat sécante choisi.", reponse: true, justification: "La réponse de l'écran 2 doit correspondre exactement à la classification trouvée à l'écran 1 ; un type différent est rejeté avant même d'examiner le candidat précis choisi." },
  { enonce: "Deux candidats distincts pour le cas « parallèle » peuvent partager exactement la même direction, sans que cela pose de problème pour l'exercice.", reponse: false, justification: "Les directions des candidats sont toujours choisies distinctes à la construction de l'exercice — deux candidats de même direction créeraient une ambiguïté entre deux bonnes réponses possibles." },
  { enonce: "La classification trouvée à l'écran 1 peut être recalculée différemment à l'écran 2, si l'élève choisit une réponse incompatible avec elle.", reponse: false, justification: "La classification est calculée une seule fois, à la génération de l'exercice — elle ne change jamais en cours d'exercice, quelle que soit la réponse donnée." },
  { enonce: "Pour le cas « incluse », les deux sommets attendus peuvent être sélectionnés dans n'importe quel ordre par l'élève — seul le fait qu'ils forment exactement la bonne paire compte.", reponse: true, justification: "La vérification compare l'ensemble des deux sommets choisis à l'ensemble des deux sommets de la droite, sans tenir compte de l'ordre de sélection." },
  { enonce: "Pour le cas « incluse », il suffit de sélectionner un sommet appartenant à la droite et n'importe quel second sommet appartenant au plan, même s'il n'appartient pas à la droite.", reponse: false, justification: "Les deux sommets sélectionnés doivent être exactement les deux sommets qui définissent la droite — un second sommet appartenant seulement au plan, sans appartenir à la droite, rend la réponse incorrecte." },
  { enonce: "Le test de parallélisme entre un segment candidat et la droite de l'exercice est effectué à partir des coordonnées réelles du solide, jamais par une simple comparaison du numéro de candidat jugé correct à l'avance.", reponse: true, justification: "Chaque candidat est vérifié géométriquement (calcul réel des directions), ce qui valide n'importe quel candidat réellement parallèle, pas seulement celui prévu à l'origine." },
  { enonce: "Le vocabulaire « déterminant » ou « produit scalaire » peut apparaître dans les étiquettes proposées à l'élève pour désigner un candidat, à condition d'en rappeler la définition.", reponse: false, justification: "Ce vocabulaire est banni de cet exercice, sans exception — les étiquettes utilisent uniquement des désignations comme « arête AB » ou « diagonale AC »." },
  { enonce: "La droite étudiée dans cet exercice est toujours définie par deux sommets nommés du solide, jamais par un point choisi arbitrairement sur une arête.", reponse: true, justification: "La droite de l'exercice est toujours désignée par deux sommets nommés parmi ceux du solide, jamais par un point intermédiaire quelconque." },
  { enonce: "Le plan étudié dans cet exercice est toujours désigné par trois sommets nommés du solide, jamais par une équation affichée à l'élève.", reponse: true, justification: "Le plan est toujours donné par trois sommets nommés du solide — aucune équation cartésienne n'est jamais montrée à l'élève." },
];

const SECTION_PLANE_SOLIDE: QuestionVraiFaux[] = [
  { enonce: "Pour un solide convexe coupé par un plan qui ne touche aucun sommet exactement, la section obtenue est toujours un unique polygone fermé.", reponse: true, justification: "C'est une propriété générale des solides convexes — jamais deux morceaux séparés ni une section ouverte." },
  { enonce: "Chaque face du solide réellement traversée par le plan de coupe contribue exactement deux sommets au polygone de section.", reponse: true, justification: "Le tracé du plan de coupe sur une face convexe la traverse en exactement deux points." },
  { enonce: "On peut tracer directement le segment de section d'une face dès que ses deux points de section sont déjà connus.", reponse: true, justification: "C'est le premier des deux types de coup autorisés — relier deux points déjà découverts sur une même face." },
  { enonce: "Lorsque plus aucune face n'a ses deux points de section connus, il faut construire un point auxiliaire par intersection de deux droites coplanaires prolongées.", reponse: true, justification: "C'est le second type de coup, utilisé quand le premier n'est plus disponible." },
  { enonce: "Un point auxiliaire peut être construit en prolongeant deux arêtes, deux diagonales, ou un mélange des deux, du solide.", reponse: true, justification: "Les droites candidates pour cette construction incluent arêtes, diagonales et segments déjà tracés de la section." },
  { enonce: "Tenter de tracer directement le segment de section d'une face qui n'a qu'un seul point de section connu est une erreur.", reponse: true, justification: "C'est précisément le piège central de cet exercice — un segment direct exige deux points déjà connus, pas un seul." },
  { enonce: "Le polygone de section est considéré complet lorsque tous ses segments ont été tracés.", reponse: true, justification: "C'est la condition d'arrêt de l'exercice — la fermeture complète du polygone." },
  { enonce: "Un point auxiliaire construit par intersection de deux droites peut débloquer la découverte d'un nouveau sommet du polygone de section.", reponse: true, justification: "C'est le but de cette construction — retrouver un point de section encore inconnu grâce à un point auxiliaire." },
  { enonce: "Le nombre d'écrans de cet exercice varie d'un exercice à l'autre, selon le nombre de faces réellement traversées par le plan de coupe.", reponse: true, justification: "Contrairement à la plupart des exercices, le nombre de coups nécessaires dépend de l'instance générée, pas d'un déroulé fixe." },
  { enonce: "Une section qui ne traverserait que trois faces d'un solide serait un simple triangle, ne nécessitant aucune construction auxiliaire.", reponse: true, justification: "Trois points de section suffiraient déjà à former un polygone fermé (un triangle), sans qu'aucun point supplémentaire ne soit nécessaire." },
  { enonce: "La section d'un solide convexe par un plan peut donner deux polygones séparés.", reponse: false, justification: "Pour un solide convexe, la section est toujours un unique polygone, jamais deux morceaux distincts." },
  { enonce: "Une face traversée par le plan de coupe peut contribuer un nombre de sommets différent de deux, comme un ou trois.", reponse: false, justification: "Une face convexe traversée par le plan de coupe l'est toujours en exactement deux points." },
  { enonce: "On peut tracer le segment de section d'une face dès qu'un seul de ses deux points de section est connu.", reponse: false, justification: "C'est justement le piège à éviter — il faut les deux points de section connus sur cette face pour tracer le segment." },
  { enonce: "La construction d'un point auxiliaire ne peut se faire qu'en prolongeant deux arêtes du solide, jamais des diagonales ni des segments déjà tracés.", reponse: false, justification: "Les droites candidates incluent aussi les diagonales des faces et les segments déjà tracés de la section elle-même." },
  { enonce: "Le polygone de section peut être considéré fermé même s'il manque encore un segment à tracer.", reponse: false, justification: "La fermeture exige que tous les segments attendus du cycle soient tracés, sans exception." },
  { enonce: "Un point auxiliaire, une fois construit, ne sert jamais à découvrir un nouveau point de section.", reponse: false, justification: "C'est justement son rôle — débloquer la découverte d'un point de section encore inconnu." },
  { enonce: "Cet exercice comporte toujours exactement le même nombre d'écrans, quel que soit le solide et le plan de coupe tirés.", reponse: false, justification: "Le nombre d'écrans dépend du nombre de faces réellement traversées, qui varie d'un exercice à l'autre." },
  { enonce: "Un point auxiliaire peut être construit même si les deux droites choisies ne se croisent pas dans l'espace.", reponse: false, justification: "Si les deux droites sont parallèles ou non coplanaires (des droites « gauches »), elles ne se croisent jamais et aucun point auxiliaire n'existe." },
  { enonce: "Dans cet exercice, la position exacte d'un point de section peut être saisie librement au clavier par l'élève.", reponse: false, justification: "Toute l'interaction se fait par sélection parmi des propositions, jamais par une saisie libre de coordonnées." },
  { enonce: "Une section qui traverse exactement quatre faces d'un solide ne peut jamais nécessiter la construction d'un point auxiliaire.", reponse: false, justification: "C'est au contraire le cas typique visé par l'exercice — en dessous de quatre faces traversées, aucune construction auxiliaire ne serait jamais nécessaire, ce qui viderait l'exercice de son intérêt." },

  // --- Enrichissement (15 affirmations supplémentaires, nuances non couvertes ci-dessus) ---
  { enonce: "Un point auxiliaire peut être construit en utilisant, comme l'une des deux droites, un segment de section déjà tracé — pas seulement une arête ou une diagonale du solide.", reponse: true, justification: "Les droites candidates pour cette construction incluent aussi bien les arêtes et diagonales du solide que les segments de section déjà tracés au fil de l'exercice." },
  { enonce: "Un point auxiliaire ne peut être construit qu'à partir de deux arêtes ou diagonales du solide, jamais à partir d'un segment de section déjà tracé.", reponse: false, justification: "Un segment de section déjà tracé est lui aussi une droite candidate valable pour cette construction, au même titre qu'une arête ou une diagonale." },
  { enonce: "Choisir deux fois la même droite pour construire un point auxiliaire est toujours rejeté, même si cette droite permettrait, à elle seule, de débloquer une face.", reponse: true, justification: "Les deux droites choisies doivent être strictement distinctes l'une de l'autre — un choix identique est rejeté d'emblée, avant même d'examiner ce qu'il débloquerait." },
  { enonce: "Il est possible de choisir deux fois la même droite pour construire un point auxiliaire, tant que cette droite débloque bien une face.", reponse: false, justification: "Les deux droites choisies doivent être distinctes l'une de l'autre — un même choix répété deux fois est toujours rejeté, quel que soit son effet potentiel." },
  { enonce: "Une face dont les deux points de section sont déjà connus ne peut jamais être la cible d'une construction de point auxiliaire.", reponse: true, justification: "Seule une face à moitié connue, avec exactement un de ses deux points déjà trouvé, peut être débloquée par un point auxiliaire — une face déjà entièrement connue n'a plus rien à débloquer." },
  { enonce: "Une face dont les deux points de section sont déjà connus peut malgré tout être choisie comme cible d'une construction de point auxiliaire.", reponse: false, justification: "Une face déjà entièrement connue (ses deux points de section trouvés) n'est jamais une cible valable pour un point auxiliaire — il n'y a plus rien à y découvrir." },
  { enonce: "Une face dont aucun des deux points de section n'est encore connu ne peut pas non plus être débloquée directement par un point auxiliaire.", reponse: true, justification: "Seule une face à moitié connue (exactement un point trouvé) peut être débloquée — une face totalement inconnue ne l'est jamais directement, comme une face totalement connue." },
  { enonce: "Le point auxiliaire calculé à partir de deux droites qui se coupent débloque automatiquement toutes les faces à moitié connues de l'exercice, sans autre condition.", reponse: false, justification: "Une face à moitié connue n'est débloquée que si le point auxiliaire, le point déjà connu de cette face et son point cible sont alignés — ce n'est pas automatique pour toutes les faces à moitié connues à la fois." },
  { enonce: "Il ne peut jamais y avoir plus de deux points de section déjà connus pour une même face croisée, à n'importe quel moment de l'exercice.", reponse: true, justification: "Cette limite à deux points connus par face est garantie dès la construction de l'exercice et reste vraie tout au long de sa résolution." },
  { enonce: "Le nombre de points de section connus pour une face donnée peut temporairement dépasser deux, avant d'être ramené à deux au moment de tracer le segment.", reponse: false, justification: "Cette limite à deux points connus par face n'est jamais dépassée, même temporairement — c'est un invariant garanti dès la construction de l'exercice." },
  { enonce: "Les trois premiers points de section de l'exercice (nommés P, Q, R) sont toujours donnés déjà connus à l'élève, avant même son premier coup.", reponse: true, justification: "Ces trois points de départ font partie de la vérité terrain fournie dès la génération de l'exercice, jamais retrouvés par l'élève lui-même." },
  { enonce: "Les trois points de section P, Q, R doivent être retrouvés par l'élève dès le premier écran, avant de pouvoir tracer le moindre segment.", reponse: false, justification: "Ces trois points sont au contraire fournis déjà connus dès le départ — l'élève ne les retrouve jamais lui-même, il part directement de leur connaissance." },
  { enonce: "Le plan de coupe de cet exercice n'est pas nécessairement défini par trois sommets nommés du solide : il peut s'agir de trois points quelconques de l'espace.", reponse: true, justification: "Contrairement à d'autres exercices du même chapitre, le plan de coupe ici est choisi parmi trois points quelconques, pas obligatoirement des sommets nommés du solide." },
  { enonce: "Le plan de coupe de cet exercice est toujours défini par trois sommets nommés du solide, exactement comme pour la classification d'une droite par rapport à un plan.", reponse: false, justification: "Ici, le plan de coupe peut être formé de trois points quelconques de l'espace, pas nécessairement des sommets nommés — contrairement à l'exercice sur la position d'une droite par rapport à un plan." },
  { enonce: "Un même point de section peut appartenir à deux faces traversées différentes du solide à la fois, lorsque ce point tombe sur l'arête commune à ces deux faces.", reponse: true, justification: "C'est exactement ainsi que le polygone de section se referme : chaque point de section commun à deux faces traversées relie leurs deux segments respectifs, formant un polygone cyclique continu." },
];

const OMBRE_SOLEIL: QuestionVraiFaux[] = [
  { enonce: "La direction de la lumière du soleil n'est jamais affichée numériquement à l'élève dans cet exercice.", reponse: true, justification: "Seuls des boutons génériques (« Candidat 1 » à « 4 ») sont proposés, jamais les composantes réelles de la direction." },
  { enonce: "L'ombre d'un point s'obtient en traçant, depuis ce point, une droite parallèle à la direction du soleil jusqu'à ce qu'elle rencontre le sol ou un obstacle.", reponse: true, justification: "C'est le principe même de la projection parallèle utilisé dans tout l'exercice." },
  { enonce: "La direction du soleil pointe toujours vers le bas, jamais vers le haut.", reponse: true, justification: "Le rayon de lumière descend toujours vers le sol, jamais l'inverse — une contrainte imposée à la génération de chaque exercice." },
  { enonce: "Confondre la projection verticale (orthogonale au sol) avec la vraie direction oblique du soleil est une erreur fréquente que cet exercice cible spécifiquement.", reponse: true, justification: "Un des candidats proposés à chaque écran de direction représente précisément cette confusion, pour la mettre en évidence." },
  { enonce: "Une direction mathématiquement parallèle à la vraie direction du soleil, mais de sens opposé, donne une ombre physiquement fausse.", reponse: true, justification: "Le sens compte : une ombre projetée dans le sens opposé tomberait du mauvais côté du piquet, même si la droite support est bien parallèle." },
  { enonce: "Dans la variante avec obstacles, l'ombre d'un même bâton peut se former sur un obstacle plutôt que directement sur le sol.", reponse: true, justification: "Le rayon lumineux peut être intercepté par un solide-obstacle avant d'atteindre le sol." },
  { enonce: "Pour reconstituer l'ombre complète d'un objet, il faut relier entre eux les points-ombres trouvés pour chacun de ses points.", reponse: true, justification: "C'est la dernière étape du raisonnement en 4 temps de cet exercice." },
  { enonce: "Dans la variante où la direction du soleil est inconnue, elle doit être déduite d'un exemple déjà résolu, comportant un point et son ombre connue.", reponse: true, justification: "C'est le principe de cette variante — retrouver la direction à partir d'une paire point/ombre déjà donnée, avant de résoudre les autres points." },
  { enonce: "Toute la sélection de cet exercice se fait par des boutons, jamais par la saisie de coordonnées au clavier.", reponse: true, justification: "Aucune saisie libre n'est utilisée dans cet exercice — uniquement de la sélection parmi des candidats proposés." },
  { enonce: "Dans la variante avec obstacles, l'ombre du bâton peut successivement rencontrer plusieurs solides-obstacles avant d'atteindre le sol.", reponse: true, justification: "Jusqu'à trois solides-obstacles peuvent se trouver sur la trajectoire de l'ombre, testés dans l'ordre où le rayon les rencontrerait." },
  { enonce: "La direction du soleil est indiquée en toutes lettres au début de chaque exercice, sous forme de composantes numériques.", reponse: false, justification: "La direction n'est jamais montrée numériquement — elle doit être identifiée depuis un exemple déjà résolu, affiché graphiquement." },
  { enonce: "L'ombre d'un point s'obtient en projetant ce point verticalement (à la perpendiculaire) sur le sol.", reponse: false, justification: "C'est justement le piège central de l'exercice : la vraie projection suit la direction oblique du soleil, jamais la verticale." },
  { enonce: "La direction du soleil peut pointer vers le haut dans certains exercices, selon l'heure de la journée simulée.", reponse: false, justification: "La direction du soleil pointe toujours vers le bas dans cet exercice — jamais un rayon montant, quelle que soit l'instance générée." },
  { enonce: "Une direction opposée à la vraie direction du soleil (mais parallèle à elle) donne exactement la même ombre.", reponse: false, justification: "Le sens de la direction compte : une direction opposée, bien que mathématiquement parallèle, place l'ombre du mauvais côté du piquet." },
  { enonce: "Dans la variante avec obstacles, l'ombre ne peut jamais rencontrer un solide-obstacle : elle atteint toujours directement le sol.", reponse: false, justification: "C'est justement le principe de cette variante — l'ombre peut casser sur un ou plusieurs solides-obstacles avant le sol." },
  { enonce: "Reconstituer l'ombre complète d'un objet ne nécessite jamais de relier les différents points-ombres trouvés entre eux.", reponse: false, justification: "C'est au contraire l'étape finale explicitement attendue — relier les points-ombres pour former l'ombre complète." },
  { enonce: "Dans la variante où la direction est inconnue, elle est révélée directement par un bouton dédié, sans avoir à être déduite.", reponse: false, justification: "Elle doit être déduite d'un exemple déjà résolu (un point et son ombre connus), jamais révélée directement." },
  { enonce: "Dans cet exercice, l'élève doit saisir librement les coordonnées du point d'ombre recherché.", reponse: false, justification: "Toute la sélection se fait par boutons parmi des candidats proposés, jamais par saisie libre de coordonnées." },
  { enonce: "Dans la variante avec obstacles, la direction du soleil doit être reconfirmée à chaque nouvel obstacle rencontré.", reponse: false, justification: "La direction n'est confirmée qu'une seule fois pour toute la scène, jamais reconfirmée obstacle par obstacle." },
  { enonce: "Deux directions candidates différentes peuvent produire exactement la même ombre pour un même point, quel que soit le point projeté.", reponse: false, justification: "Des directions différentes projettent en général un même point vers des ombres différentes — sinon la distinction entre elles n'aurait aucun sens dans cet exercice." },

  // --- Enrichissement (15 affirmations supplémentaires, nuances non couvertes ci-dessus) ---
  { enonce: "Dans la variante où la direction est inconnue, si le gabarit tiré est une pyramide, il n'y a aucun autre sommet à résoudre après le sommet connu — l'exercice passe directement à la conclusion.", reponse: true, justification: "La pyramide ne possède qu'un seul sommet qui n'est pas au sol (son sommet supérieur), déjà utilisé comme sommet connu — il ne reste donc plus aucun autre sommet à retrouver." },
  { enonce: "Dans la variante où la direction est inconnue, le gabarit tiré est toujours un campanile, jamais une pyramide.", reponse: false, justification: "Les deux gabarits (pyramide et campanile) sont possibles dans cette variante, tirés au hasard selon l'exercice généré." },
  { enonce: "Dans la variante où la direction est inconnue, le sommet servant à déduire la direction est toujours un sommet du solide affiché, jamais un point construit indépendamment de lui.", reponse: true, justification: "Ce sommet est toujours l'un des sommets réels du solide dessiné, jamais un point ajouté à part — c'est en observant son ombre déjà connue sur ce même solide que la direction se déduit." },
  { enonce: "Dans la variante où la direction est inconnue, le sommet servant à déduire la direction peut être un sommet du sol du solide, à hauteur nulle.", reponse: false, justification: "Ce sommet est toujours pris à une hauteur non nulle — un sommet du sol aurait une ombre confondue avec lui-même, ce qui ne permettrait de déduire aucune direction." },
  { enonce: "Dans la variante avec obstacles, si le rayon lumineux du bâton ne rencontre aucun des solides-obstacles de la scène, son ombre retombe directement sur le sol, exactement comme dans la variante sans obstacle.", reponse: true, justification: "L'obstacle n'intercepte l'ombre que s'il est réellement traversé par le rayon lumineux ; sinon, l'ombre continue jusqu'au sol, comme si aucun obstacle n'existait." },
  { enonce: "Dans la variante avec obstacles, l'ombre du bâton doit obligatoirement rencontrer au moins un solide-obstacle avant d'atteindre le sol.", reponse: false, justification: "Rien ne garantit qu'un obstacle soit réellement sur la trajectoire de l'ombre — si aucun ne l'est, elle atteint directement le sol, comme dans la variante simple." },
  { enonce: "Pour un obstacle en escalier, les deux faces de profil (en forme d'escalier, non rectangulaires) sont exclues du test de rencontre avec l'ombre, contrairement à ses faces latérales qui restent testées normalement.", reponse: true, justification: "Ces deux faces de profil ont une forme concave en escalier qui empêcherait le test géométrique habituel de fonctionner correctement — elles sont donc écartées, sans que cela change le résultat final pour l'élève." },
  { enonce: "Pour un obstacle du type caisse, comme pour l'escalier, deux de ses faces sont exclues du test de rencontre avec l'ombre.", reponse: false, justification: "Une caisse n'a que des faces rectangulaires ordinaires : toutes ses faces sont utilisées pour le test, sans aucune exclusion — seul l'escalier, à cause de ses faces de profil non rectangulaires, en exclut deux." },
  { enonce: "Dans la boucle de résolution des obstacles, chaque étape correspond à un solide-obstacle entier, jamais à une seule face ou une seule marche prise isolément.", reponse: true, justification: "Chaque solide-obstacle (caisse ou escalier) est testé comme un bloc entier — jamais décomposé face par face ni marche par marche du point de vue de l'élève." },
  { enonce: "Pour un obstacle du type escalier, l'élève doit résoudre l'ombre marche par marche, une étape de résolution par marche de l'escalier.", reponse: false, justification: "L'escalier est traité comme un seul solide-obstacle entier, en une seule étape de résolution — jamais décomposé marche par marche." },
  { enonce: "Dans la boucle de résolution des obstacles, l'ombre attendue pour un obstacle donné est calculée comme si cet obstacle était seul dans la scène, indépendamment de la présence des autres.", reponse: true, justification: "Chaque obstacle de la boucle est testé isolément contre la direction de lumière, sans tenir compte des autres solides-obstacles présents par ailleurs dans la scène." },
  { enonce: "Dans la boucle de résolution des obstacles, l'ombre attendue pour un obstacle donné tient compte des autres obstacles de la scène, qui peuvent la modifier.", reponse: false, justification: "Chaque obstacle de la boucle est au contraire testé isolément, comme s'il était seul dans la scène — les autres obstacles n'entrent jamais dans ce calcul particulier." },
  { enonce: "Le nombre de solides-obstacles présents dans la variante avec obstacles est toujours compris entre un et trois.", reponse: true, justification: "Cette variante comporte toujours au moins un et au plus trois solides-obstacles à résoudre, jamais davantage." },
  { enonce: "Le nombre de solides-obstacles présents dans la variante avec obstacles peut atteindre jusqu'à cinq.", reponse: false, justification: "Cette variante ne comporte jamais plus de trois solides-obstacles, quel que soit l'exercice généré." },
  { enonce: "Pour le gabarit campanile, le nombre de sommets restant à résoudre après le sommet connu varie d'un exercice à l'autre, entre un et quatre.", reponse: true, justification: "Contrairement à la pyramide (dont le sommet connu épuise l'unique sommet non-sol disponible), le campanile possède plusieurs sommets non-sol restants, dont le nombre varie selon l'instance tirée." },
];

export const BANQUE_QUIZ_GEOMETRIE_ESPACE: Record<VarianteQuizGeometrieEspace, QuestionVraiFaux[]> = {
  positionDroitePlan: POSITION_DROITE_PLAN,
  sectionPlaneSolide: SECTION_PLANE_SOLIDE,
  ombreSoleil: OMBRE_SOLEIL,
};
