/**
 * Couche A — banque de questions vrai/faux pour "Cercle trigonométrique & triangles quelconques"
 * (chapitre 3 dans la nomenclature du projet). 245 affirmations pré-écrites (jamais générées
 * procéduralement), 7 thèmes de 35 questions chacun, chaque affirmation vérifiée mathématiquement à
 * la rédaction.
 */
import type { QuestionVraiFaux, VarianteQuizCercleTriangles } from "../../core/quizCercleTriangles.types";

export const BANQUE_QUIZ_CERCLE_TRIANGLES: Record<VarianteQuizCercleTriangles, QuestionVraiFaux[]> = {
  placementCercle: [
    { enonce: "Le cercle trigonométrique est un cercle de rayon 1 centré à l'origine du repère.", reponse: true, justification: "C'est sa définition." },
    { enonce: "Sur le cercle trigonométrique, le sens positif des angles est le sens des aiguilles d'une montre.", reponse: false, justification: "Faux : le sens positif est le sens trigonométrique, c'est-à-dire le sens inverse des aiguilles d'une montre." },
    { enonce: "Un angle de 400° se réduit à 40° dans [0°;360°[ en lui retranchant 360°.", reponse: true, justification: "400° − 360° = 40°." },
    { enonce: "Un angle de −45° se réduit à −45° + 720° pour rester dans [0°;360°[.", reponse: false, justification: "Faux : il suffit d'ajouter un seul tour (360°) : −45°+360°=315°, qui est déjà dans [0°;360°[." },
    { enonce: "L'angle de référence d'un angle du deuxième quadrant vaut 180° moins cet angle.", reponse: true, justification: "C'est la formule de l'angle de référence pour le deuxième quadrant." },
    { enonce: "L'angle de référence peut être un angle obtus, supérieur à 90°.", reponse: false, justification: "Faux : par définition, l'angle de référence est toujours aigu, compris entre 0° et 90°." },
    { enonce: "Dans le troisième quadrant, le cosinus et le sinus sont tous les deux négatifs.", reponse: true, justification: "Les deux coordonnées du point sont négatives dans ce quadrant." },
    { enonce: "Dans le quatrième quadrant, la tangente est positive.", reponse: false, justification: "Faux : le cosinus est positif et le sinus négatif dans ce quadrant, donc leur rapport (la tangente) est négatif." },
    { enonce: "cos(180°) vaut −1.", reponse: true, justification: "Le point du cercle trigonométrique associé à 180° est (−1;0)." },
    { enonce: "sin(270°) vaut 1.", reponse: false, justification: "Faux : sin(270°) vaut −1, le point associé à 270° est (0;−1)." },
    { enonce: "La tangente n'est pas définie pour un angle de 90°.", reponse: true, justification: "Car cos(90°)=0, et tan=sin/cos exige un dénominateur non nul." },
    { enonce: "Dans le premier quadrant, la tangente est négative.", reponse: false, justification: "Faux : sinus et cosinus sont tous deux positifs dans ce quadrant, donc leur quotient est positif." },
    { enonce: "Un angle de 90° appartient au premier quadrant.", reponse: false, justification: "Faux : un angle exactement sur un axe (0°, 90°, 180°, 270°) n'appartient à aucun des 4 quadrants." },
    { enonce: "L'angle de référence d'un angle du quatrième quadrant vaut 360° moins cet angle.", reponse: true, justification: "C'est la formule de l'angle de référence pour le quatrième quadrant." },
    { enonce: "Un angle de 720° se réduit à 0° dans [0°;360°[.", reponse: true, justification: "720° = 2×360°, deux tours complets ramènent donc à 0°." },
    { enonce: "Dans le deuxième quadrant, le cosinus est positif.", reponse: false, justification: "Faux : l'abscisse est négative dans ce quadrant, donc le cosinus est négatif." },
    { enonce: "tan(θ) est égal au rapport sin(θ)/cos(θ).", reponse: true, justification: "C'est la définition de la tangente à partir du sinus et du cosinus." },
    { enonce: "cos(0°) vaut 0.", reponse: false, justification: "Faux : cos(0°) vaut 1, le point associé à 0° est (1;0)." },
    { enonce: "Pour réduire un angle supérieur à 360°, on lui retranche des multiples de 360° jusqu'à tomber dans [0°;360°[.", reponse: true, justification: "C'est la méthode de réduction standard." },
    { enonce: "Le signe de la tangente dans le troisième quadrant est positif.", reponse: true, justification: "Cosinus et sinus sont tous deux négatifs dans ce quadrant, leur quotient est donc positif." },
    { enonce: "Un angle de 850° se réduit à 130° dans [0°;360°[.", reponse: true, justification: "850° − 2×360° = 850° − 720° = 130°." },
    { enonce: "Un angle de −200° se réduit à −20° en lui ajoutant 180°.", reponse: false, justification: "Faux : il faut ajouter un tour complet (360°), pas 180° : −200°+360°=160°, qui est bien dans [0°;360°[." },
    { enonce: "L'angle de référence d'un angle du premier quadrant est égal à l'angle lui-même.", reponse: true, justification: "Un angle du premier quadrant est déjà aigu, il est donc son propre angle de référence." },
    { enonce: "L'angle de référence de 95° vaut 95°.", reponse: false, justification: "Faux : 95° appartient au deuxième quadrant, son angle de référence vaut 180°−95°=85°." },
    { enonce: "Un angle de 180° se situe sur un axe et n'appartient à aucun des 4 quadrants.", reponse: true, justification: "Comme 0°, 90° et 270°, un angle exactement sur un axe n'appartient à aucun quadrant." },
    { enonce: "Dans le premier quadrant, la tangente devient négative lorsque l'angle se rapproche de 90°.", reponse: false, justification: "Faux : sinus et cosinus restent tous deux positifs sur tout le premier quadrant, la tangente y reste donc positive (elle tend vers +∞ près de 90°, mais ne devient jamais négative)." },
    { enonce: "Le cosinus est négatif à la fois dans le deuxième et dans le troisième quadrant.", reponse: true, justification: "L'abscisse du point est négative dans ces deux quadrants." },
    { enonce: "Le sinus a le même signe dans le premier et dans le quatrième quadrant.", reponse: false, justification: "Faux : le sinus est positif dans le premier quadrant et négatif dans le quatrième." },
    { enonce: "Pour ramener un angle compris entre −360° et 0° dans [0°;360°[, il suffit de lui ajouter 360°.", reponse: true, justification: "Ajouter un tour complet ramène l'angle dans l'intervalle voulu." },
    { enonce: "Un angle de 1080° se réduit à 360° dans [0°;360°[.", reponse: false, justification: "Faux : 1080°=3×360°, l'angle se réduit à 0°, car 360° n'appartient pas à l'intervalle [0°;360°[, qui exclut sa borne supérieure." },
    { enonce: "Le point du cercle trigonométrique associé à un angle du quatrième quadrant a une abscisse positive et une ordonnée négative.", reponse: true, justification: "C'est la définition même du quatrième quadrant." },
    { enonce: "La tangente est positive dans le deuxième quadrant.", reponse: false, justification: "Faux : dans ce quadrant le cosinus est négatif et le sinus positif, leur quotient est donc négatif." },
    { enonce: "Deux angles qui diffèrent d'un multiple de 360° sont associés au même point du cercle trigonométrique.", reponse: true, justification: "Faire un ou plusieurs tours complets ramène exactement au même point." },
    { enonce: "On réduit d'abord l'angle dans [0°;360°[, puis on calcule son angle de référence à partir de cette valeur réduite.", reponse: true, justification: "C'est l'ordre standard de la méthode : réduction, puis angle de référence." },
    { enonce: "L'angle de référence d'un angle de 300° vaut 300°−180°=120°.", reponse: false, justification: "Faux : 300° appartient au quatrième quadrant, où l'angle de référence vaut 360° moins l'angle : 360°−300°=60°." },
  ],
  valeursRemarquables: [
    { enonce: "sin(30°) vaut 1/2.", reponse: true, justification: "C'est une valeur remarquable à connaître par cœur." },
    { enonce: "cos(30°) vaut 1/2.", reponse: false, justification: "Faux : cos(30°) vaut √3/2 ; c'est sin(30°) qui vaut 1/2." },
    { enonce: "cos(45°) et sin(45°) sont égaux, tous deux égaux à √2/2.", reponse: true, justification: "45° est le seul angle remarquable où sinus et cosinus coïncident." },
    { enonce: "tan(45°) vaut √2/2.", reponse: false, justification: "Faux : tan(45°) vaut 1, puisque sin(45°)=cos(45°)." },
    { enonce: "sin(60°) vaut √3/2.", reponse: true, justification: "C'est une valeur remarquable à connaître par cœur." },
    { enonce: "cos(60°) vaut √3/2.", reponse: false, justification: "Faux : cos(60°) vaut 1/2 ; c'est sin(60°) qui vaut √3/2." },
    { enonce: "tan(60°) vaut √3.", reponse: true, justification: "tan(60°)=sin(60°)/cos(60°)=(√3/2)/(1/2)=√3." },
    { enonce: "sin(90°) vaut 1 et cos(90°) vaut 0.", reponse: true, justification: "Le point associé à 90° est (0;1)." },
    { enonce: "tan(90°) vaut 0.", reponse: false, justification: "Faux : tan(90°) n'est pas définie, car cos(90°)=0." },
    { enonce: "sin(0°) vaut 0 et cos(0°) vaut 1.", reponse: true, justification: "Le point associé à 0° est (1;0)." },
    { enonce: "sin(150°) vaut 1/2, comme sin(30°).", reponse: true, justification: "150° a pour angle de référence 180°−150°=30°, et le sinus est positif dans le deuxième quadrant." },
    { enonce: "cos(120°) vaut 1/2.", reponse: false, justification: "Faux : 120° a pour angle de référence 60° et le cosinus est négatif dans le deuxième quadrant, donc cos(120°)=−1/2." },
    { enonce: "sin(45°) est strictement compris entre sin(30°) et sin(60°).", reponse: true, justification: "1/2 < √2/2 ≈ 0,707 < √3/2 ≈ 0,866." },
    { enonce: "Plus un angle du premier quadrant est grand, plus son cosinus est grand.", reponse: false, justification: "Faux : c'est l'inverse — le cosinus décroît quand l'angle augmente sur [0°;90°]." },
    { enonce: "tan(30°) vaut √3/3 (ou de façon équivalente 1/√3).", reponse: true, justification: "tan(30°)=sin(30°)/cos(30°)=(1/2)/(√3/2)=1/√3=√3/3." },
    { enonce: "tan(0°) n'est pas définie.", reponse: false, justification: "Faux : tan(0°) vaut 0, car sin(0°)=0 et cos(0°)=1." },
    { enonce: "Pour tout angle remarquable du premier quadrant, sin et cos sont tous deux strictement positifs.", reponse: true, justification: "Les deux coordonnées sont positives dans le premier quadrant." },
    { enonce: "cos(90°) vaut 1.", reponse: false, justification: "Faux : cos(90°) vaut 0 ; c'est cos(0°) qui vaut 1." },
    { enonce: "Sur le premier quadrant, sin(θ) et cos(θ) sont toujours compris entre 0 et 1 (bornes incluses).", reponse: true, justification: "Le point reste à coordonnées positives et de norme 1 sur ce quadrant." },
    { enonce: "tan(30°) et tan(60°) sont inverses l'un de l'autre.", reponse: true, justification: "tan(30°)=1/√3 et tan(60°)=√3 : leur produit vaut 1." },
    { enonce: "sin(135°) vaut √2/2, comme sin(45°).", reponse: true, justification: "135° a pour angle de référence 180°−135°=45°, et le sinus est positif dans le deuxième quadrant." },
    { enonce: "cos(135°) vaut √2/2.", reponse: false, justification: "Faux : cos(135°) vaut −√2/2, car le cosinus est négatif dans le deuxième quadrant." },
    { enonce: "tan(135°) vaut −1.", reponse: true, justification: "tan(135°)=sin(135°)/cos(135°)=(√2/2)/(−√2/2)=−1." },
    { enonce: "sin(210°) vaut 1/2.", reponse: false, justification: "Faux : 210° a pour angle de référence 30° et le sinus est négatif dans le troisième quadrant, donc sin(210°)=−1/2." },
    { enonce: "cos(210°) vaut −√3/2.", reponse: true, justification: "210° a pour angle de référence 30° et le cosinus est négatif dans le troisième quadrant : cos(210°)=−cos(30°)=−√3/2." },
    { enonce: "tan(240°) vaut −√3.", reponse: false, justification: "Faux : dans le troisième quadrant la tangente est positive (sinus et cosinus tous deux négatifs), donc tan(240°)=√3." },
    { enonce: "sin(300°) vaut −√3/2.", reponse: true, justification: "300° a pour angle de référence 60° et le sinus est négatif dans le quatrième quadrant : sin(300°)=−sin(60°)=−√3/2." },
    { enonce: "cos(300°) vaut −1/2.", reponse: false, justification: "Faux : le cosinus est positif dans le quatrième quadrant, donc cos(300°)=cos(60°)=1/2." },
    { enonce: "tan(330°) vaut −√3/3 (ou −1/√3).", reponse: true, justification: "330° a pour angle de référence 30° et la tangente est négative dans le quatrième quadrant : tan(330°)=−tan(30°)=−√3/3." },
    { enonce: "sin(0°) et sin(360°) sont différents.", reponse: false, justification: "Faux : sin(0°)=sin(360°)=0, un tour complet ramène au même point." },
    { enonce: "cos(0°) et cos(360°) sont égaux, tous deux égaux à 1.", reponse: true, justification: "Un tour complet ramène exactement au même point du cercle." },
    { enonce: "Il existe un angle remarquable entre 0° et 90° pour lequel sinus et cosinus sont tous deux strictement supérieurs à √2/2.", reponse: false, justification: "Faux : à 45° ils sont égaux à √2/2 (pas strictement supérieurs), et de part et d'autre de 45° l'un des deux descend en dessous de √2/2 pendant que l'autre monte." },
    { enonce: "Parmi les angles remarquables 0°, 30°, 45°, 60°, 90°, c'est à 90° que le sinus est maximal.", reponse: true, justification: "sin(90°)=1, la valeur maximale possible pour un sinus." },
    { enonce: "tan(45°) est strictement supérieur à tan(60°).", reponse: false, justification: "Faux : tan(45°)=1 alors que tan(60°)=√3≈1,73, donc tan(45°) est inférieur." },
    { enonce: "sin(30°) + cos(60°) vaut 1.", reponse: true, justification: "sin(30°)=1/2 et cos(60°)=1/2, leur somme vaut 1." },
  ],
  identiteFondamentale: [
    { enonce: "Pour tout angle θ, on a l'égalité cos²(θ) + sin²(θ) = 1.", reponse: true, justification: "C'est l'identité trigonométrique fondamentale." },
    { enonce: "L'identité fondamentale s'écrit cos(θ) + sin(θ) = 1.", reponse: false, justification: "Faux : ce sont les carrés du cosinus et du sinus qui s'additionnent pour donner 1, pas le cosinus et le sinus eux-mêmes." },
    { enonce: "Si cos(θ) = 3/5, alors sin²(θ) = 16/25.", reponse: true, justification: "sin²(θ)=1−cos²(θ)=1−(3/5)²=1−9/25=16/25." },
    { enonce: "Connaître uniquement la valeur de sin(θ) suffit toujours à déterminer le signe de cos(θ) sans autre information.", reponse: false, justification: "Faux : sin(θ) ne détermine que |cos(θ)|, il faut connaître le quadrant (ou un intervalle) pour fixer le signe." },
    { enonce: "Si sin(θ) = −1/2 et que θ appartient au troisième quadrant, alors cos(θ) est négatif.", reponse: true, justification: "Dans le troisième quadrant, cosinus et sinus sont tous deux négatifs." },
    { enonce: "cos²(θ) peut être strictement supérieur à 1.", reponse: false, justification: "Faux : puisque sin²(θ)≥0, on a toujours cos²(θ)=1−sin²(θ)≤1." },
    { enonce: "tan(θ) peut se calculer une fois connus sin(θ) et cos(θ), par le quotient sin(θ)/cos(θ).", reponse: true, justification: "C'est la définition de la tangente, valable dès que cos(θ)≠0." },
    { enonce: "Si cos(θ) = 1, alors sin(θ) peut valoir 1 ou −1.", reponse: false, justification: "Faux : si cos(θ)=1, l'identité donne sin²(θ)=0, donc sin(θ)=0 nécessairement." },
    { enonce: "sin(θ) et cos(θ) sont toujours compris entre −1 et 1.", reponse: true, justification: "Ce sont les coordonnées d'un point du cercle trigonométrique, de rayon 1." },
    { enonce: "sin(θ)=4/5 et cos(θ)=−3/5 correspond forcément à un angle du premier quadrant.", reponse: false, justification: "Faux : cosinus négatif et sinus positif signifient que θ appartient au deuxième quadrant." },
    { enonce: "Si l'on connaît sin(θ) et le quadrant de θ, on peut toujours en déduire la valeur exacte de cos(θ).", reponse: true, justification: "L'identité donne |cos(θ)|, et le quadrant en fixe le signe : la valeur est donc entièrement déterminée." },
    { enonce: "L'identité cos²(θ)+sin²(θ)=1 n'est vraie que pour les angles remarquables.", reponse: false, justification: "Faux : elle est vraie pour absolument tout angle θ, c'est une identité universelle." },
    { enonce: "Si θ appartient au premier ou au quatrième quadrant, alors cos(θ) est positif ou nul.", reponse: true, justification: "L'abscisse est positive ou nulle dans ces deux quadrants." },
    { enonce: "Il est possible d'avoir simultanément sin(θ) = 0,8 et cos(θ) = 0,7.", reponse: false, justification: "Faux : 0,8²+0,7²=0,64+0,49=1,13≠1, ce couple ne peut pas correspondre à un même angle." },
    { enonce: "Si θ est dans le deuxième quadrant, alors tan(θ) est négative.", reponse: true, justification: "Cosinus négatif et sinus positif donnent un quotient négatif." },
    { enonce: "Si cos(θ) = 0, alors tan(θ) vaut 0.", reponse: false, justification: "Faux : si cos(θ)=0, la tangente n'est pas définie (division par 0)." },
    { enonce: "Connaissant sin(θ) = 0,6 et sachant que θ appartient au deuxième quadrant, on peut affirmer cos(θ) = −0,8.", reponse: true, justification: "sin²+cos²=1 donne cos²=1−0,36=0,64, donc |cos(θ)|=0,8 ; dans le deuxième quadrant le cosinus est négatif, donc cos(θ)=−0,8." },
    { enonce: "sin(θ)² + cos(θ)² dépend de la valeur de θ.", reponse: false, justification: "Faux : cette somme vaut toujours exactement 1, quel que soit θ." },
    { enonce: "Si θ appartient au deuxième quadrant, alors sin(θ) et cos(θ) sont de signes contraires.", reponse: true, justification: "Dans ce quadrant, le sinus est positif et le cosinus est négatif." },
    { enonce: "Si l'on sait que cos(θ) = 1/2, cela suffit à connaître la valeur exacte de sin(θ) sans savoir dans quel quadrant se trouve θ.", reponse: false, justification: "Faux : sin(θ) pourrait valoir √3/2 ou −√3/2 selon le quadrant, l'information sur le quadrant est indispensable." },
    { enonce: "Si sin(θ) = 5/13, alors cos²(θ) = 144/169.", reponse: true, justification: "cos²(θ)=1−sin²(θ)=1−25/169=144/169." },
    { enonce: "Si cos(θ) = −0,6, alors sin(θ) = 0,4 nécessairement.", reponse: false, justification: "Faux : sin²(θ)=1−0,36=0,64, donc sin(θ)=0,8 ou sin(θ)=−0,8, jamais 0,4." },
    { enonce: "Si θ appartient au premier quadrant, alors sin(θ) et cos(θ) sont tous deux positifs.", reponse: true, justification: "Les deux coordonnées du point sont positives dans ce quadrant." },
    { enonce: "cos(θ) + sin(θ) peut dépasser 2 pour un certain angle θ.", reponse: false, justification: "Faux : cos(θ) et sin(θ) valent chacun au plus 1, leur somme ne peut donc pas dépasser 2 (elle ne peut même pas atteindre 2, cela exigerait sin(θ)=cos(θ)=1 simultanément, ce qui contredirait l'identité)." },
    { enonce: "Si sin(θ) = 0, alors cos(θ) vaut 1 ou −1.", reponse: true, justification: "cos²(θ)=1−sin²(θ)=1−0=1, donc cos(θ)=1 ou cos(θ)=−1." },
    { enonce: "sin(θ) = −0,9 et cos(θ) = 0,5 peuvent correspondre à un même angle θ.", reponse: false, justification: "Faux : (−0,9)²+0,5²=0,81+0,25=1,06≠1, ce couple ne peut pas correspondre à un même angle." },
    { enonce: "Si θ appartient au troisième ou au quatrième quadrant, alors sin(θ) est négatif.", reponse: true, justification: "L'ordonnée du point est négative dans ces deux quadrants." },
    { enonce: "Si l'on connaît cos(θ) et que θ appartient au premier quadrant, il existe deux valeurs possibles pour sin(θ).", reponse: false, justification: "Faux : dans le premier quadrant, sin(θ) est nécessairement positif, une seule des deux racines de l'identité est donc valable." },
    { enonce: "sin²(θ) est toujours compris entre 0 et 1 (bornes incluses).", reponse: true, justification: "Puisque sin(θ) est toujours compris entre −1 et 1, son carré est toujours compris entre 0 et 1." },
    { enonce: "Si sin(θ) = cos(θ), alors nécessairement θ = 45°.", reponse: false, justification: "Faux : θ=225° convient aussi, puisque sin(225°)=cos(225°)=−√2/2." },
    { enonce: "Si cos(θ) = −1, alors sin(θ) = 0.", reponse: true, justification: "sin²(θ)=1−cos²(θ)=1−1=0, donc sin(θ)=0." },
    { enonce: "cos(θ) et sin(θ) peuvent être tous les deux négatifs sans que cos²(θ)+sin²(θ) vaille 1.", reponse: false, justification: "Faux : l'identité cos²(θ)+sin²(θ)=1 reste vraie quels que soient les signes de cos(θ) et sin(θ), puisqu'elle porte sur leurs carrés." },
    { enonce: "Connaître le signe de cos(θ) et le signe de sin(θ) permet de déterminer dans quel quadrant se situe θ.", reponse: true, justification: "Chaque combinaison de signes correspond à un unique quadrant." },
    { enonce: "sin(θ) − cos(θ) vaut toujours 0, quel que soit θ.", reponse: false, justification: "Faux : ce n'est le cas que pour certains angles particuliers (comme 45° ou 225°), pas pour tout θ." },
    { enonce: "Si sin(θ) = 12/13 et que θ appartient au premier quadrant, alors cos(θ) = 5/13.", reponse: true, justification: "cos²(θ)=1−144/169=25/169, donc |cos(θ)|=5/13 ; dans le premier quadrant le cosinus est positif, donc cos(θ)=5/13." },
  ],
  anglesAssocies: [
    { enonce: "L'angle supplémentaire de θ est 180° − θ.", reponse: true, justification: "C'est la définition de l'angle supplémentaire." },
    { enonce: "L'angle complémentaire de θ est 180° − θ.", reponse: false, justification: "Faux : l'angle complémentaire est 90°−θ ; 180°−θ est l'angle supplémentaire." },
    { enonce: "sin(180° − θ) = sin(θ).", reponse: true, justification: "C'est la relation de l'angle supplémentaire pour le sinus." },
    { enonce: "cos(180° − θ) = cos(θ).", reponse: false, justification: "Faux : cos(180°−θ) = −cos(θ)." },
    { enonce: "cos(−θ) = cos(θ).", reponse: true, justification: "Le cosinus est une fonction paire." },
    { enonce: "sin(−θ) = sin(θ).", reponse: false, justification: "Faux : sin(−θ) = −sin(θ), le sinus est une fonction impaire." },
    { enonce: "sin(90° − θ) = cos(θ).", reponse: true, justification: "C'est la relation de l'angle complémentaire." },
    { enonce: "cos(90° − θ) = cos(θ).", reponse: false, justification: "Faux : cos(90°−θ) = sin(θ), pas cos(θ)." },
    { enonce: "tan(180° + θ) = tan(θ).", reponse: true, justification: "La tangente est périodique, de période 180°." },
    { enonce: "sin(180° + θ) = sin(θ).", reponse: false, justification: "Faux : sin(180°+θ) = −sin(θ)." },
    { enonce: "cos(180° + θ) = −cos(θ).", reponse: true, justification: "C'est la relation de l'angle anti-supplémentaire pour le cosinus." },
    { enonce: "tan(−θ) = tan(θ).", reponse: false, justification: "Faux : tan(−θ) = −tan(θ), la tangente est une fonction impaire." },
    { enonce: "Si sin(θ) = 0,4, alors sin(180° − θ) vaut aussi 0,4.", reponse: true, justification: "Application directe de sin(180°−θ)=sin(θ)." },
    { enonce: "Si cos(θ) = 0,6, alors cos(180° − θ) vaut aussi 0,6.", reponse: false, justification: "Faux : cos(180°−θ) = −cos(θ) = −0,6." },
    { enonce: "L'angle opposé de θ est −θ.", reponse: true, justification: "C'est la définition de l'angle opposé." },
    { enonce: "tan(90° − θ) = tan(θ).", reponse: false, justification: "Faux : tan(90°−θ) = 1/tan(θ) (l'inverse), pas tan(θ) lui-même." },
    { enonce: "tan(θ)·tan(90° − θ) = 1, pour tout angle θ où ces deux tangentes sont définies et non nulles.", reponse: true, justification: "Puisque tan(90°−θ)=1/tan(θ), leur produit vaut 1." },
    { enonce: "Deux angles supplémentaires ont toujours le même cosinus.", reponse: false, justification: "Faux : leurs cosinus sont opposés, cos(180°−θ)=−cos(θ)." },
    { enonce: "Les formules d'angles associés permettent de retrouver la valeur exacte de sin, cos ou tan d'un angle quelconque à partir d'un angle du premier quadrant.", reponse: true, justification: "C'est le principe même de la réduction au premier quadrant via les angles associés." },
    { enonce: "cos(−θ) et cos(180° + θ) sont toujours égaux.", reponse: false, justification: "Faux : cos(−θ)=cos(θ) alors que cos(180°+θ)=−cos(θ) — ils sont opposés, sauf si cos(θ)=0." },
    { enonce: "Si cos(θ) = 0,7, alors cos(−θ) vaut aussi 0,7.", reponse: true, justification: "Le cosinus est une fonction paire : cos(−θ)=cos(θ)." },
    { enonce: "Si sin(θ) = 0,3, alors sin(−θ) vaut aussi 0,3.", reponse: false, justification: "Faux : sin(−θ)=−sin(θ)=−0,3." },
    { enonce: "Si sin(θ) = 0,9, alors sin(180° + θ) vaut −0,9.", reponse: true, justification: "sin(180°+θ)=−sin(θ)=−0,9." },
    { enonce: "Si cos(θ) = −0,2, alors cos(180° + θ) vaut aussi −0,2.", reponse: false, justification: "Faux : cos(180°+θ)=−cos(θ)=0,2." },
    { enonce: "tan(θ) et tan(180° − θ) sont toujours opposés (l'un est l'opposé de l'autre).", reponse: true, justification: "tan(180°−θ)=sin(180°−θ)/cos(180°−θ)=sin(θ)/(−cos(θ))=−tan(θ)." },
    { enonce: "sin(θ) et sin(90° − θ) sont toujours égaux, quel que soit θ.", reponse: false, justification: "Faux : sin(90°−θ)=cos(θ), qui n'est égal à sin(θ) que pour des angles particuliers (comme 45°)." },
    { enonce: "cos(θ) et cos(−θ) désignent toujours le même nombre, quel que soit θ.", reponse: true, justification: "Le cosinus est une fonction paire." },
    { enonce: "tan(180° − θ) est égal à tan(θ).", reponse: false, justification: "Faux : tan(180°−θ)=−tan(θ)." },
    { enonce: "Si tan(θ) = 2, alors tan(180° + θ) = 2 également.", reponse: true, justification: "La tangente est périodique de période 180°." },
    { enonce: "sin(90° − θ) et cos(90° − θ) sont toujours égaux, quel que soit θ.", reponse: false, justification: "Faux : sin(90°−θ)=cos(θ) et cos(90°−θ)=sin(θ), qui ne sont égaux que pour des angles particuliers." },
    { enonce: "Si θ et φ sont deux angles supplémentaires (θ + φ = 180°), alors sin(θ) = sin(φ).", reponse: true, justification: "φ=180°−θ, donc sin(φ)=sin(180°−θ)=sin(θ)." },
    { enonce: "Si θ et φ sont deux angles opposés (φ = −θ), alors cos(θ) et cos(φ) sont opposés.", reponse: false, justification: "Faux : le cosinus étant pair, cos(φ)=cos(−θ)=cos(θ) : ils sont égaux, pas opposés." },
    { enonce: "L'angle anti-supplémentaire de θ est 180° + θ.", reponse: true, justification: "C'est la définition de l'angle anti-supplémentaire." },
    { enonce: "Deux angles complémentaires ont toujours le même sinus.", reponse: false, justification: "Faux : si θ+φ=90°, alors sin(φ)=sin(90°−θ)=cos(θ), qui n'égale sin(θ) que pour des angles particuliers." },
    { enonce: "tan(−θ) et tan(180° − θ) sont toujours égaux, quel que soit θ (là où ces tangentes sont définies).", reponse: true, justification: "tan(−θ)=−tan(θ) et tan(180°−θ)=−tan(θ) : les deux expressions coïncident toujours." },
  ],
  resoudreAngle: [
    { enonce: "L'équation sin(α) = 1/2 admet exactement deux solutions dans [0°;360°[.", reponse: true, justification: "Ce sont 30° et 150°, symétriques par rapport à 90°." },
    { enonce: "L'équation sin(α) = 1/2 admet une seule solution dans [0°;360°[.", reponse: false, justification: "Faux : elle en admet deux, 30° et 150°." },
    { enonce: "L'équation cos(α) = 1 admet une seule solution dans [0°;360°[, qui est 0°.", reponse: true, justification: "Le cosinus ne vaut 1 qu'en 0° sur cet intervalle." },
    { enonce: "L'équation cos(α) = 1 admet deux solutions dans [0°;360°[.", reponse: false, justification: "Faux : elle n'en admet qu'une, 0° (le maximum du cosinus n'est atteint qu'une fois par tour)." },
    { enonce: "L'équation tan(α) = 1 admet deux solutions dans [0°;360°[ : 45° et 225°.", reponse: true, justification: "225°=45°+180°, la seconde solution s'obtient en ajoutant la période 180° de la tangente." },
    { enonce: "L'équation tan(α) = 1 admet une seule solution dans [0°;360°[.", reponse: false, justification: "Faux : la tangente est périodique de période 180°, donc sur un intervalle de 360° elle prend chaque valeur exactement deux fois." },
    { enonce: "Pour résoudre sin(α) = k avec 0 < k < 1, les deux solutions de [0°;360°[ sont symétriques par rapport à 90°.", reponse: true, justification: "La deuxième solution vaut 180° moins la première." },
    { enonce: "Pour résoudre cos(α) = k avec 0 < k < 1, les deux solutions de [0°;360°[ sont symétriques par rapport à 90°.", reponse: false, justification: "Faux : elles sont symétriques par rapport à 0° (ou 360°) — la deuxième solution vaut 360° moins la première." },
    { enonce: "L'équation sin(α) = 0 admet deux solutions dans [0°;360°[ : 0° et 180°.", reponse: true, justification: "Ce sont les deux angles sur l'axe des abscisses." },
    { enonce: "L'équation sin(α) = 2 admet une solution dans [0°;360°[.", reponse: false, justification: "Faux : le sinus est toujours compris entre −1 et 1, donc sin(α)=2 n'a aucune solution." },
    { enonce: "L'équation cos(α) = −1 admet une seule solution dans [0°;360°[, qui est 180°.", reponse: true, justification: "Le cosinus ne vaut −1 qu'en 180° sur cet intervalle." },
    { enonce: "L'équation cos(α) = 0 admet une seule solution dans [0°;360°[.", reponse: false, justification: "Faux : elle en admet deux, 90° et 270°." },
    { enonce: "Pour résoudre tan(α) = k, on cherche d'abord un angle remarquable dont la tangente vaut k, puis on ajoute 180° pour obtenir la seconde solution.", reponse: true, justification: "C'est la méthode standard, exploitant la période 180° de la tangente." },
    { enonce: "Pour résoudre sin(α) = k avec k négatif, les deux solutions se trouvent dans le premier et le deuxième quadrant.", reponse: false, justification: "Faux : le sinus est négatif dans le troisième et le quatrième quadrant, c'est là que se trouvent les solutions." },
    { enonce: "L'équation cos(α) = k avec −1 < k < 0 admet deux solutions, situées dans le deuxième et le troisième quadrant.", reponse: true, justification: "Le cosinus est négatif exactement dans ces deux quadrants." },
    { enonce: "Résoudre sin(α)=k et résoudre cos(α)=k, pour un même k, donne toujours exactement les deux mêmes solutions.", reponse: false, justification: "Faux : les formules de symétrie diffèrent (par rapport à 90° pour le sinus, par rapport à 0°/360° pour le cosinus), les solutions sont donc en général différentes." },
    { enonce: "Une équation du type sin(α) = k, avec k une valeur remarquable, se résout en identifiant d'abord l'angle du premier quadrant qui convient.", reponse: true, justification: "C'est la méthode standard, avant d'utiliser les angles associés pour trouver les autres solutions." },
    { enonce: "L'équation tan(α) = 0 n'a aucune solution dans [0°;360°[.", reponse: false, justification: "Faux : elle en a deux, 0° et 180°, où le sinus s'annule." },
    { enonce: "Le nombre de solutions d'une équation sin(α)=k ou cos(α)=k sur [0°;360°[ peut être 0, 1 ou 2 selon la valeur de k.", reponse: true, justification: "0 solution si |k|>1, 1 solution si k=±1 (cas extrême), 2 solutions sinon." },
    { enonce: "Pour résoudre cos(α) = k avec k négatif, la première solution trouvée est toujours dans le premier quadrant.", reponse: false, justification: "Faux : si cos(α) est négatif, aucune solution ne peut être dans le premier quadrant (où le cosinus est positif) — les solutions sont dans le deuxième et le troisième quadrant." },
    { enonce: "L'équation sin(α) = √3/2 admet deux solutions dans [0°;360°[ : 60° et 120°.", reponse: true, justification: "sin(60°)=√3/2, et la seconde solution est 180°−60°=120°." },
    { enonce: "L'équation cos(α) = √2/2 admet pour solutions 45° et 135° dans [0°;360°[.", reponse: false, justification: "Faux : cos(135°)=−√2/2, pas √2/2. La bonne seconde solution est 360°−45°=315°." },
    { enonce: "L'équation sin(α) = −1 admet une seule solution dans [0°;360°[, qui est 270°.", reponse: true, justification: "C'est le minimum du sinus, atteint une seule fois par tour." },
    { enonce: "L'équation sin(α) = −1 admet deux solutions dans [0°;360°[.", reponse: false, justification: "Faux : elle n'en admet qu'une, 270°, car −1 est une valeur extrême du sinus." },
    { enonce: "L'équation tan(α) = −1 admet deux solutions dans [0°;360°[ : 135° et 315°.", reponse: true, justification: "tan(135°)=−1, et 135°+180°=315° est la seconde solution." },
    { enonce: "L'équation cos(α) = −√3/2 admet pour solutions 150° et 30° dans [0°;360°[.", reponse: false, justification: "Faux : cos(30°)=√3/2, positif, donc 30° n'est pas solution. La bonne seconde solution est 360°−150°=210°." },
    { enonce: "L'équation cos(α) = 0,5 admet deux solutions dans [0°;360°[, dont la somme vaut 360°.", reponse: true, justification: "Les solutions sont 60° et 300°, symétriques par rapport à 0°/360°, et 60°+300°=360°." },
    { enonce: "L'équation sin(α) = 0,5 admet deux solutions dans [0°;360°[, dont la somme vaut 360°.", reponse: false, justification: "Faux : les solutions sont 30° et 150°, symétriques par rapport à 90°, et leur somme vaut 180°, pas 360°." },
    { enonce: "L'équation tan(α) = k, quel que soit le réel k, admet toujours exactement deux solutions dans [0°;360°[.", reponse: true, justification: "La tangente parcourt tous les réels sur chaque intervalle de longueur 180°, et il y a exactement deux tels intervalles dans [0°;360°[." },
    { enonce: "L'équation cos(α) = 0 admet une solution unique dans [0°;360°[, qui est 90°.", reponse: false, justification: "Faux : elle en admet deux, 90° et 270°." },
    { enonce: "Pour résoudre sin(α) = −√2/2, on peut repérer que √2/2 correspond à l'angle remarquable 45°, puis chercher les quadrants où le sinus est négatif.", reponse: true, justification: "C'est la méthode standard : angle remarquable associé, puis choix des quadrants selon le signe voulu." },
    { enonce: "L'équation sin(α) = 1 admet deux solutions dans [0°;360°[.", reponse: false, justification: "Faux : elle n'en admet qu'une, 90°, car 1 est le maximum du sinus." },
    { enonce: "Les équations cos(α) = 1 et sin(α) = 1 admettent chacune une unique solution dans [0°;360°[, respectivement 0° et 90°.", reponse: true, justification: "Ce sont les valeurs maximales du cosinus et du sinus, chacune atteinte une seule fois par tour." },
    { enonce: "Pour résoudre une équation du type cos(α) = k, il faut d'abord connaître le quadrant de α, comme pour l'identité fondamentale.", reponse: false, justification: "Faux : résoudre cos(α)=k donne directement toutes les solutions de [0°;360°[ sans connaître le quadrant à l'avance ; c'est pour l'identité fondamentale (retrouver sin ou cos à partir de l'autre) qu'il faut connaître le quadrant." },
    { enonce: "L'équation tan(α) = √3/3 admet pour solutions 30° et 210°, qui diffèrent exactement de 180°.", reponse: true, justification: "tan(30°)=√3/3, et 30°+180°=210° est la seconde solution, conformément à la période de la tangente." },
  ],
  triangleQuelconque: [
    { enonce: "Dans tout triangle, la somme des trois angles vaut 180°.", reponse: true, justification: "C'est une propriété fondamentale de tout triangle." },
    { enonce: "La loi des sinus s'écrit a/sin(A) = b/sin(B) = c/sin(C), où a désigne le côté opposé à l'angle A.", reponse: true, justification: "C'est la formule exacte de la loi des sinus." },
    { enonce: "La loi des cosinus (formule d'Al-Kashi) s'écrit a² = b² + c² + 2bc·cos(A).", reponse: false, justification: "Faux : le signe devant le dernier terme est un moins, pas un plus — a² = b² + c² − 2bc·cos(A)." },
    { enonce: "L'aire d'un triangle peut se calculer par ½·a·b·sin(C), où C est l'angle formé entre les côtés a et b.", reponse: true, justification: "C'est la formule de l'aire à partir de deux côtés et de l'angle compris." },
    { enonce: "La loi des cosinus ne peut s'utiliser que si l'on connaît déjà un angle du triangle.", reponse: false, justification: "Faux : elle permet justement de trouver un angle inconnu à partir des trois côtés (cas SSS)." },
    { enonce: "Connaissant les 3 côtés d'un triangle (cas SSS), on peut retrouver ses 3 angles à l'aide de la loi des cosinus.", reponse: true, justification: "C'est exactement la méthode pour résoudre le cas SSS." },
    { enonce: "La loi des sinus permet toujours de retrouver un angle inconnu, même sans connaître aucun angle du triangle au départ.", reponse: false, justification: "Faux : la loi des sinus nécessite de connaître au moins un couple côté/angle opposé déjà complet pour démarrer." },
    { enonce: "Dans le cas SAS (deux côtés et l'angle compris entre eux connus), on utilise la loi des cosinus pour trouver le troisième côté.", reponse: true, justification: "C'est la méthode standard pour résoudre le cas SAS." },
    { enonce: "Le cas SSA (deux côtés et un angle non compris) donne toujours une solution unique.", reponse: false, justification: "Faux : c'est justement le cas ambigu, qui peut donner 0, 1 ou 2 triangles possibles selon les données." },
    { enonce: "Dans un triangle, le plus grand côté est toujours opposé au plus grand angle.", reponse: true, justification: "C'est une propriété générale de tout triangle." },
    { enonce: "L'aire d'un triangle ne peut se calculer qu'en connaissant sa base et sa hauteur.", reponse: false, justification: "Faux : elle peut aussi se calculer avec deux côtés et l'angle compris entre eux, sans connaître explicitement de hauteur." },
    { enonce: "Connaissant deux angles d'un triangle, on peut toujours en déduire le troisième par soustraction à 180°.", reponse: true, justification: "La somme des angles d'un triangle vaut toujours 180°." },
    { enonce: "La loi des cosinus ne s'applique qu'aux triangles rectangles.", reponse: false, justification: "Faux : elle s'applique à n'importe quel triangle quelconque ; dans un triangle rectangle, elle se réduit d'ailleurs au théorème de Pythagore." },
    { enonce: "Si un triangle a deux côtés égaux, alors les deux angles opposés à ces côtés sont également égaux.", reponse: true, justification: "C'est une propriété du triangle isocèle." },
    { enonce: "Le cas AAS (deux angles et un côté non compris) rend le triangle impossible à résoudre complètement.", reponse: false, justification: "Faux : connaître 2 angles permet de déduire le 3e (somme=180°), puis la loi des sinus permet de trouver les côtés restants." },
    { enonce: "Dans le cas SSA, il est possible qu'aucun triangle ne corresponde aux données fournies.", reponse: true, justification: "C'est le cas ambigu, qui peut donner 0 solution selon les données." },
    { enonce: "La loi des sinus s'exprime avec des carrés de côtés, comme la loi des cosinus.", reponse: false, justification: "Faux : la loi des sinus utilise les côtés (non élevés au carré) divisés par le sinus de l'angle opposé, contrairement à la loi des cosinus." },
    { enonce: "Le théorème de Pythagore est un cas particulier de la loi des cosinus, lorsque l'angle compris vaut 90°.", reponse: true, justification: "Quand A=90°, cos(A)=0, le terme −2bc·cos(A) s'annule et il reste a²=b²+c²." },
    { enonce: "Pour calculer l'aire d'un triangle avec la formule ½·a·b·sin(C), l'angle C doit obligatoirement être aigu.", reponse: false, justification: "Faux : la formule fonctionne pour n'importe quel angle C du triangle, aigu ou obtus." },
    { enonce: "Résoudre un triangle signifie déterminer tous ses côtés et tous ses angles inconnus.", reponse: true, justification: "C'est la définition de « résoudre un triangle »." },
    { enonce: "Dans un triangle équilatéral, les trois angles valent chacun 60°.", reponse: true, justification: "180°÷3=60°, et les trois angles sont égaux dans un triangle équilatéral." },
    { enonce: "La loi des sinus permet de calculer directement l'aire d'un triangle, sans passer par deux côtés et l'angle compris.", reponse: false, justification: "Faux : la loi des sinus relie côtés et angles opposés entre eux, elle ne donne pas directement une aire ; c'est la formule ½·a·b·sin(C) qui sert à cela." },
    { enonce: "Dans le cas SSA, si l'angle donné est obtus, il ne peut exister qu'au plus une solution.", reponse: true, justification: "Un triangle ne peut contenir qu'un seul angle obtus, ce qui élimine l'ambiguïté du second triangle possible." },
    { enonce: "Dans un triangle, le plus petit côté est toujours opposé à l'angle le plus grand.", reponse: false, justification: "Faux : c'est l'inverse — le plus petit côté est opposé au plus petit angle." },
    { enonce: "La somme de deux angles quelconques d'un triangle est toujours strictement inférieure à 180°.", reponse: true, justification: "Le troisième angle est toujours strictement positif, donc la somme des deux autres est strictement inférieure à 180°." },
    { enonce: "Si l'on connaît un seul côté et un seul angle d'un triangle, on peut toujours le résoudre entièrement.", reponse: false, justification: "Faux : un côté et un angle isolés ne suffisent pas, une infinité de triangles différents partagent ce côté et cet angle ; il faut au moins 3 informations indépendantes (SSS, SAS, ASA/AAS ou SSA)." },
    { enonce: "Dans le cas SSS, la loi des cosinus permet de trouver un premier angle, puis la loi des sinus permet de trouver les angles restants.", reponse: true, justification: "C'est la méthode standard pour résoudre le cas SSS." },
    { enonce: "La formule ½·a·b·sin(C) ne peut pas être utilisée pour calculer l'aire d'un triangle rectangle.", reponse: false, justification: "Faux : la formule reste valable pour tout triangle, y compris rectangle ; si C=90°, elle se réduit à ½·a·b, comme la formule base×hauteur habituelle." },
    { enonce: "Un triangle ayant un angle de 90° et un angle de 45° est nécessairement isocèle.", reponse: true, justification: "Le troisième angle vaut 180°−90°−45°=45° : deux angles égaux, donc deux côtés opposés égaux." },
    { enonce: "La loi des cosinus a² = b² + c² − 2bc·cos(A) ne peut pas être adaptée pour calculer b² ou c².", reponse: false, justification: "Faux : la même loi s'écrit aussi b²=a²+c²−2ac·cos(B) et c²=a²+b²−2ab·cos(C), en permutant les rôles des côtés et de l'angle compris." },
    { enonce: "Dans un triangle obtusangle, le côté opposé à l'angle obtus est le plus long des trois côtés.", reponse: true, justification: "L'angle obtus est le plus grand angle du triangle, donc le côté qui lui est opposé est le plus long." },
    { enonce: "Il existe des triangles ayant deux angles obtus.", reponse: false, justification: "Faux : deux angles obtus (chacun supérieur à 90°) dépasseraient déjà 180° à eux seuls, ce qui est impossible." },
    { enonce: "Si deux triangles ont leurs trois angles respectivement égaux, ils ne sont pas nécessairement superposables.", reponse: true, justification: "Ils sont semblables mais peuvent être de tailles différentes (l'un peut être un agrandissement de l'autre)." },
    { enonce: "Le cas ASA (deux angles et le côté compris connus) ne permet pas de déterminer les côtés restants du triangle.", reponse: false, justification: "Faux : le troisième angle se déduit par soustraction à 180°, puis la loi des sinus donne les côtés restants." },
    { enonce: "Dans le cas SSA, si le côté opposé à l'angle connu est plus grand que l'autre côté donné, la solution est unique.", reponse: true, justification: "L'ambiguïté du cas SSA n'apparaît que lorsque le côté opposé à l'angle connu est plus petit que l'autre côté donné." },
  ],
  trianglesLies: [
    { enonce: "La triangulation permet de calculer une distance ou une hauteur inaccessible en la reliant à un triangle que l'on peut résoudre entièrement.", reponse: true, justification: "C'est le principe général de la triangulation." },
    { enonce: "La triangulation ne fonctionne que si le triangle intermédiaire est rectangle.", reponse: false, justification: "Faux : le triangle « pont » peut être rectangle ou quelconque, il suffit qu'il soit résoluble." },
    { enonce: "Un côté partagé entre deux triangles permet de transférer une information calculée dans le premier triangle vers le second.", reponse: true, justification: "C'est le principe de la variante « côté partagé »." },
    { enonce: "Dans une chaîne de triangulation, chaque triangle doit être résolu indépendamment, sans lien avec les autres.", reponse: false, justification: "Faux : c'est justement le côté (ou l'angle) partagé entre deux triangles qui permet de faire le lien entre eux." },
    { enonce: "Pour mesurer la hauteur d'un objet inaccessible, on peut utiliser deux angles d'observation pris depuis deux points différents, alignés avec la base de l'objet.", reponse: true, justification: "C'est une méthode classique de triangulation." },
    { enonce: "La triangulation permet uniquement de calculer des longueurs, jamais des aires.", reponse: false, justification: "Faux : une fois le triangle cible résolu, on peut aussi en calculer l'aire avec la formule ½·a·b·sin(C)." },
    { enonce: "Dans la variante « angle partagé », c'est un angle commun (et non un côté) qui relie les deux triangles.", reponse: true, justification: "C'est la définition de cette variante." },
    { enonce: "La distance entre deux points inaccessibles ne peut jamais être calculée par triangulation.", reponse: false, justification: "Faux : c'est justement l'une des applications classiques de la triangulation (viser les deux points depuis des positions accessibles et résoudre les triangles obtenus)." },
    { enonce: "Pour résoudre le triangle « cible » d'une triangulation, on utilise généralement la loi des sinus, une fois qu'un côté et deux angles sont connus.", reponse: true, justification: "C'est la méthode standard pour un triangle du cas AAS." },
    { enonce: "Le triangle « pont » d'une triangulation sert uniquement à décorer le schéma, sans utilité pour le calcul final.", reponse: false, justification: "Faux : c'est justement la résolution du triangle « pont » qui fournit la donnée (côté ou angle) transférée vers le triangle « cible »." },
    { enonce: "Un problème de triangulation peut être résolu même si aucun des deux triangles n'est directement mesurable dans son intégralité au départ.", reponse: true, justification: "C'est justement l'intérêt de la méthode : combiner deux triangles partiellement connus." },
    { enonce: "Dans un problème de triangulation, il est toujours possible de mesurer directement la grandeur cherchée sans passer par aucun calcul.", reponse: false, justification: "Faux : c'est justement parce que la grandeur cherchée est inaccessible directement qu'on a recours à la triangulation." },
    { enonce: "Après avoir résolu le triangle pont, la grandeur transférée sert de donnée connue pour le triangle cible.", reponse: true, justification: "C'est l'enchaînement logique de la méthode." },
    { enonce: "La triangulation exige toujours de connaître au moins un côté du triangle cible dès le départ.", reponse: false, justification: "Faux : c'est justement le côté partagé, calculé à partir du triangle pont, qui fournit cette information — elle n'est pas connue au départ." },
    { enonce: "La méthode de triangulation repose fondamentalement sur les mêmes outils (lois des sinus et des cosinus) que la résolution d'un triangle quelconque isolé.", reponse: true, justification: "Elle réutilise le même outillage que la résolution d'un triangle isolé." },
    { enonce: "Deux triangulations menées avec des données différentes donnent toujours exactement le même résultat final.", reponse: false, justification: "Faux : le résultat dépend entièrement des mesures d'angles et de distances fournies dans l'énoncé, qui varient d'un problème à l'autre." },
    { enonce: "La triangulation est une méthode utilisée concrètement pour mesurer des hauteurs de bâtiments ou des largeurs de terrains sans les mesurer directement.", reponse: true, justification: "C'est une application réelle et classique de la méthode." },
    { enonce: "Il est impossible qu'un même schéma de triangulation permette à la fois de calculer un côté et une aire.", reponse: false, justification: "Faux : une fois le triangle cible entièrement résolu, on peut en tirer aussi bien un côté manquant qu'une aire." },
    { enonce: "Le choix entre variante « côté partagé » et variante « angle partagé » dépend des données fournies par l'énoncé sur la configuration des deux triangles.", reponse: true, justification: "C'est ce que précise l'énoncé de chaque problème." },
    { enonce: "La triangulation ne s'applique qu'à des situations purement théoriques, sans usage dans des contextes concrets comme les terrains ou les distances inaccessibles.", reponse: false, justification: "Faux : au contraire, la triangulation est justement utilisée pour des situations concrètes — terrains, hauteurs, distances inaccessibles." },
    { enonce: "Dans la variante « côté partagé », le côté commun aux deux triangles doit d'abord être calculé dans le premier triangle avant de pouvoir être réutilisé dans le second.", reponse: true, justification: "C'est l'enchaînement logique de la méthode : résoudre le pont, puis transférer la donnée." },
    { enonce: "Dans la variante « angle partagé », c'est un côté commun (et non un angle) qui relie les deux triangles.", reponse: false, justification: "Faux : c'est justement un angle commun qui relie les deux triangles dans cette variante, pas un côté." },
    { enonce: "Un problème de triangulation peut combiner un premier triangle résolu par la loi des sinus et un second résolu par la loi des cosinus.", reponse: true, justification: "Rien n'impose d'utiliser le même outil pour les deux triangles ; le choix dépend des données propres à chacun." },
    { enonce: "La triangulation ne permet de mesurer que des distances horizontales, jamais des hauteurs verticales.", reponse: false, justification: "Faux : mesurer une hauteur inaccessible (bâtiment, montagne) est justement une application classique de la triangulation." },
    { enonce: "Pour résoudre le triangle pont, il faut disposer d'assez de données pour appliquer directement la loi des sinus ou des cosinus, sans passer par le triangle cible.", reponse: true, justification: "Le triangle pont doit être résoluble par lui-même en premier, puisque c'est lui qui fournit la donnée transférée." },
    { enonce: "Le triangle cible doit toujours être résolu avant le triangle pont.", reponse: false, justification: "Faux : c'est l'inverse — le triangle pont est résolu en premier, car c'est lui qui fournit la donnée transférée au triangle cible." },
    { enonce: "Si l'angle ou le côté partagé entre deux triangles est mal identifié, le calcul du triangle cible sera faux même si le triangle pont est correctement résolu.", reponse: true, justification: "Une erreur dans l'identification de l'élément partagé fausse la donnée transférée, donc tout le calcul du triangle cible qui en dépend." },
    { enonce: "Un même problème de triangulation ne peut jamais combiner les deux variantes (côté partagé et angle partagé) dans une chaîne à plusieurs triangles.", reponse: false, justification: "Faux : rien n'empêche une chaîne de plus de deux triangles de combiner un lien par côté partagé et un lien par angle partagé à des endroits différents." },
    { enonce: "La triangulation est une application concrète des lois des sinus et des cosinus à des situations où la grandeur cherchée n'est pas mesurable directement sur le terrain.", reponse: true, justification: "C'est le principe même de la méthode." },
    { enonce: "Connaître seulement les trois côtés du triangle pont ne permet jamais d'en déduire un angle utile pour le triangle cible.", reponse: false, justification: "Faux : connaître les 3 côtés (cas SSS) permet justement de calculer n'importe quel angle du triangle pont grâce à la loi des cosinus." },
    { enonce: "La longueur du côté partagé, une fois calculée dans le triangle pont, devient une donnée d'entrée pour résoudre le triangle cible.", reponse: true, justification: "C'est l'enchaînement logique de la méthode." },
    { enonce: "La triangulation ne s'applique qu'à deux triangles à la fois, jamais à une chaîne de plus de deux triangles reliés successivement.", reponse: false, justification: "Faux : le même principe peut s'enchaîner sur plusieurs triangles successifs, chacun transmettant une donnée au suivant." },
    { enonce: "Repérer si les deux triangles d'un problème partagent un côté ou un angle est la première étape pour choisir la bonne méthode de résolution.", reponse: true, justification: "C'est ce que précise la configuration donnée par l'énoncé de chaque problème." },
    { enonce: "Le triangle cible peut être résolu sans aucune information provenant du triangle pont, du moment que l'on connaît un de ses angles.", reponse: false, justification: "Faux : par définition de la méthode, le triangle cible a besoin du côté ou de l'angle transféré depuis le triangle pont ; un seul angle isolé ne suffit pas à le résoudre." },
    { enonce: "La triangulation permet, à partir d'angles d'observation pris depuis deux positions distinctes et de la distance qui les sépare, de calculer la distance jusqu'à un point inaccessible.", reponse: true, justification: "C'est une application classique de la méthode (par exemple pour repérer un point depuis deux stations)." },
  ],
};
