import type { ContexteComparaisonSuites } from "../../core5e/comparaisonSuites.types";

/**
 * Bassin unique de 50 contextes narratifs, partagé par les 3 branches de 5gen18 (`villesCroissance`
 * = SA vs SG, `stockDemande` = SA vs SA, `epargneCroissance` = SG vs SG). `sujetA`/`sujetB` sont des
 * groupes nominaux complets et NEUTRES (aucun sens de variation figé dans le texte) pour la grande
 * majorité des entrées — la Couche présentation (`ui5e/formatComparaisonSuites.ts`) leur accole une
 * clause de tendance générique ("croît de X %/an", "croît de X unités/mois", "diminue de X
 * unités/mois") déterminée par le RÔLE mathématique de la branche, jamais par le contexte lui-même.
 *
 * `branchesAutorisees` restreint les 11 entrées dont l'identité narrative fige un sens de variation
 * incompatible avec certaines branches, au lieu de forcer une adaptation qui ne tiendrait pas :
 * - 5 contextes "un côté décroît, l'autre croît" par construction (dette remboursée/impayée,
 *   réservoir qui se vide/se remplit, batterie qui se décharge/se recharge, glacier qui fond,
 *   réserve de poissons pêchée/protégée) → réservés à `stockDemande`, seule branche à comporter un
 *   côté structurellement décroissant.
 * - 6 contextes dont la grandeur est un CUMUL (arbres plantés, points accumulés, victoires cumulées,
 *   minerai extrait cumulé, rendement cumulé, fonds collectés) → ne peuvent par nature jamais
 *   décroître, donc exclus de `stockDemande` (qui exigerait un côté décroissant).
 */
export const CONTEXTES_COMPARAISON_SUITES: ContexteComparaisonSuites[] = [
  { id: "villages", labelA: "Village A", labelB: "Village B", sujetA: "la population du village A", sujetB: "la population du village B", unite: "habitants", periode: "an" },
  {
    id: "prets",
    labelA: "Prêt A",
    labelB: "Prêt B",
    sujetA: "la dette restante du prêt A (remboursements réguliers)",
    sujetB: "la dette restante du prêt B (intérêts qui s'accumulent, sans remboursement)",
    unite: "€",
    periode: "mois",
    branchesAutorisees: ["stockDemande"],
  },
  { id: "usineProdConso", labelA: "Production", labelB: "Consommation", sujetA: "la production de l'usine", sujetB: "la consommation de l'usine", unite: "tonnes", periode: "mois" },
  { id: "entreprises", labelA: "Entreprise A", labelB: "Entreprise B", sujetA: "le chiffre d'affaires de l'entreprise A", sujetB: "le chiffre d'affaires de l'entreprise B", unite: "milliers d'€", periode: "an" },
  { id: "applis", labelA: "Appli A", labelB: "Appli B", sujetA: "le nombre d'utilisateurs de l'application A", sujetB: "le nombre d'utilisateurs de l'application B", unite: "utilisateurs", periode: "mois" },
  { id: "fondsPension", labelA: "Fonds A", labelB: "Fonds B", sujetA: "la valeur du fonds de pension A", sujetB: "la valeur du fonds de pension B", unite: "milliers d'€", periode: "an" },
  { id: "bacteries", labelA: "Colonie A", labelB: "Colonie B", sujetA: "le nombre de bactéries de la colonie A", sujetB: "le nombre de bactéries de la colonie B", unite: "bactéries", periode: "mois" },
  { id: "insectes", labelA: "Population A", labelB: "Population B", sujetA: "la population d'insectes de la zone A", sujetB: "la population d'insectes de la zone B", unite: "insectes", periode: "mois" },
  {
    id: "forets",
    labelA: "Forêt A",
    labelB: "Forêt B",
    sujetA: "le nombre cumulé d'arbres plantés dans la forêt A",
    sujetB: "le nombre cumulé d'arbres plantés dans la forêt B",
    unite: "arbres",
    periode: "an",
    branchesAutorisees: ["villesCroissance", "epargneCroissance"],
  },
  {
    id: "reservoirs",
    labelA: "Réservoir A",
    labelB: "Réservoir B",
    sujetA: "le volume d'eau du réservoir A (qui se vide)",
    sujetB: "le volume d'eau du réservoir B (qui se remplit)",
    unite: "litres",
    periode: "mois",
    branchesAutorisees: ["stockDemande"],
  },
  {
    id: "batteries",
    labelA: "Batterie A",
    labelB: "Batterie B",
    sujetA: "la capacité restante de la batterie A (qui se dégrade)",
    sujetB: "la capacité restaurée de la batterie B (reconditionnement progressif)",
    unite: "mAh",
    periode: "mois",
    branchesAutorisees: ["stockDemande"],
  },
  {
    id: "fidelite",
    labelA: "Compte A",
    labelB: "Compte B",
    sujetA: "le nombre de points accumulés sur le compte de fidélité A",
    sujetB: "le nombre de points accumulés sur le compte de fidélité B",
    unite: "points",
    periode: "mois",
    branchesAutorisees: ["villesCroissance", "epargneCroissance"],
  },
  { id: "streaming", labelA: "Service A", labelB: "Service B", sujetA: "le nombre d'abonnés du service de streaming A", sujetB: "le nombre d'abonnés du service de streaming B", unite: "abonnés", periode: "mois" },
  {
    id: "equipesSportives",
    labelA: "Équipe A",
    labelB: "Équipe B",
    sujetA: "le nombre cumulé de victoires de l'équipe A",
    sujetB: "le nombre cumulé de victoires de l'équipe B",
    unite: "victoires",
    periode: "an",
    branchesAutorisees: ["villesCroissance", "epargneCroissance"],
  },
  { id: "bourse", labelA: "Investissement A", labelB: "Investissement B", sujetA: "la valeur de l'investissement boursier A", sujetB: "la valeur de l'investissement boursier B", unite: "milliers d'€", periode: "an" },
  { id: "crypto", labelA: "Crypto A", labelB: "Crypto B", sujetA: "la valeur de la cryptomonnaie A", sujetB: "la valeur de la cryptomonnaie B", unite: "€", periode: "mois" },
  { id: "solaire", labelA: "Ferme A", labelB: "Ferme B", sujetA: "la production d'énergie de la ferme solaire A", sujetB: "la production d'énergie de la ferme solaire B", unite: "MWh", periode: "an" },
  { id: "eolien", labelA: "Parc A", labelB: "Parc B", sujetA: "la production d'énergie du parc éolien A", sujetB: "la production d'énergie du parc éolien B", unite: "MWh", periode: "an" },
  { id: "betail", labelA: "Troupeau A", labelB: "Troupeau B", sujetA: "le nombre de têtes de bétail du troupeau A", sujetB: "le nombre de têtes de bétail du troupeau B", unite: "têtes", periode: "an" },
  { id: "ruches", labelA: "Ruche A", labelB: "Ruche B", sujetA: "la population d'abeilles de la ruche A", sujetB: "la population d'abeilles de la ruche B", unite: "abeilles", periode: "mois" },
  { id: "reserveNaturelle", labelA: "Réserve A", labelB: "Réserve B", sujetA: "la population de l'espèce suivie dans la réserve A", sujetB: "la population de l'espèce suivie dans la réserve B", unite: "individus", periode: "an" },
  { id: "quartiers", labelA: "Quartier A", labelB: "Quartier B", sujetA: "le nombre de logements du quartier A", sujetB: "le nombre de logements du quartier B", unite: "logements", periode: "an" },
  { id: "ecoles", labelA: "École A", labelB: "École B", sujetA: "le nombre d'élèves inscrits à l'école A", sujetB: "le nombre d'élèves inscrits à l'école B", unite: "élèves", periode: "an" },
  { id: "hopitaux", labelA: "Hôpital A", labelB: "Hôpital B", sujetA: "le nombre de lits disponibles de l'hôpital A", sujetB: "le nombre de lits disponibles de l'hôpital B", unite: "lits", periode: "mois" },
  { id: "usines", labelA: "Usine A", labelB: "Usine B", sujetA: "la production journalière de l'usine A", sujetB: "la production journalière de l'usine B", unite: "unités", periode: "mois" },
  {
    id: "mines",
    labelA: "Mine A",
    labelB: "Mine B",
    sujetA: "le volume cumulé de minerai extrait de la mine A",
    sujetB: "le volume cumulé de minerai extrait de la mine B",
    unite: "tonnes",
    periode: "an",
    branchesAutorisees: ["villesCroissance", "epargneCroissance"],
  },
  { id: "compagniesAeriennes", labelA: "Compagnie A", labelB: "Compagnie B", sujetA: "le nombre de passagers de la compagnie aérienne A", sujetB: "le nombre de passagers de la compagnie aérienne B", unite: "passagers", periode: "an" },
  { id: "restaurants", labelA: "Chaîne A", labelB: "Chaîne B", sujetA: "le nombre de franchises de la chaîne de restaurants A", sujetB: "le nombre de franchises de la chaîne de restaurants B", unite: "franchises", periode: "an" },
  { id: "covoiturage", labelA: "Plateforme A", labelB: "Plateforme B", sujetA: "le nombre de trajets mensuels de la plateforme de covoiturage A", sujetB: "le nombre de trajets mensuels de la plateforme de covoiturage B", unite: "trajets", periode: "mois" },
  { id: "reseauxSociaux", labelA: "Réseau A", labelB: "Réseau B", sujetA: "le nombre d'utilisateurs actifs du réseau social A", sujetB: "le nombre d'utilisateurs actifs du réseau social B", unite: "utilisateurs", periode: "mois" },
  { id: "vignobles", labelA: "Vignoble A", labelB: "Vignoble B", sujetA: "la production annuelle de bouteilles du vignoble A", sujetB: "la production annuelle de bouteilles du vignoble B", unite: "bouteilles", periode: "an" },
  {
    id: "glaciers",
    labelA: "Glacier",
    labelB: "Lac glaciaire",
    sujetA: "le volume de glace du glacier (en fonte)",
    sujetB: "le volume d'eau du lac glaciaire (alimenté par la fonte)",
    unite: "millions de m³",
    periode: "an",
    branchesAutorisees: ["stockDemande"],
  },
  { id: "lacs", labelA: "Lac A", labelB: "Lac B", sujetA: "le niveau d'eau du lac A", sujetB: "le niveau d'eau du lac B", unite: "cm", periode: "mois" },
  { id: "barrages", labelA: "Barrage A", labelB: "Barrage B", sujetA: "la production d'électricité du barrage A", sujetB: "la production d'électricité du barrage B", unite: "MWh", periode: "an" },
  { id: "dataCenters", labelA: "Data center A", labelB: "Data center B", sujetA: "la capacité de stockage du data center A", sujetB: "la capacité de stockage du data center B", unite: "To", periode: "an" },
  { id: "startups", labelA: "Start-up A", labelB: "Start-up B", sujetA: "la valorisation de la start-up A", sujetB: "la valorisation de la start-up B", unite: "milliers d'€", periode: "an" },
  { id: "musees", labelA: "Musée A", labelB: "Musée B", sujetA: "le nombre de visiteurs annuels du musée A", sujetB: "le nombre de visiteurs annuels du musée B", unite: "visiteurs", periode: "an" },
  { id: "bibliotheques", labelA: "Bibliothèque A", labelB: "Bibliothèque B", sujetA: "le nombre d'ouvrages de la bibliothèque A", sujetB: "le nombre d'ouvrages de la bibliothèque B", unite: "ouvrages", periode: "an" },
  { id: "clubsSport", labelA: "Club A", labelB: "Club B", sujetA: "le nombre de licenciés du club de sport A", sujetB: "le nombre de licenciés du club de sport B", unite: "licenciés", periode: "an" },
  { id: "immobilier", labelA: "Fonds A", labelB: "Fonds B", sujetA: "la valeur du fonds d'investissement immobilier A", sujetB: "la valeur du fonds d'investissement immobilier B", unite: "milliers d'€", periode: "an" },
  { id: "assurance", labelA: "Compagnie A", labelB: "Compagnie B", sujetA: "le nombre de clients de la compagnie d'assurance A", sujetB: "le nombre de clients de la compagnie d'assurance B", unite: "clients", periode: "an" },
  { id: "eauPotable", labelA: "Réseau A", labelB: "Réseau B", sujetA: "la population desservie par le réseau de distribution d'eau potable A", sujetB: "la population desservie par le réseau de distribution d'eau potable B", unite: "habitants", periode: "an" },
  { id: "centresCommerciaux", labelA: "Centre A", labelB: "Centre B", sujetA: "la fréquentation mensuelle du centre commercial A", sujetB: "la fréquentation mensuelle du centre commercial B", unite: "visiteurs", periode: "mois" },
  { id: "parcsAttractions", labelA: "Parc A", labelB: "Parc B", sujetA: "le nombre de visiteurs annuels du parc d'attractions A", sujetB: "le nombre de visiteurs annuels du parc d'attractions B", unite: "visiteurs", periode: "an" },
  { id: "flottesElectriques", labelA: "Flotte A", labelB: "Flotte B", sujetA: "le nombre de véhicules de la flotte électrique A", sujetB: "le nombre de véhicules de la flotte électrique B", unite: "véhicules", periode: "an" },
  {
    id: "exploitationsAgricoles",
    labelA: "Exploitation A",
    labelB: "Exploitation B",
    sujetA: "le rendement cumulé de l'exploitation agricole A",
    sujetB: "le rendement cumulé de l'exploitation agricole B",
    unite: "tonnes",
    periode: "an",
    branchesAutorisees: ["villesCroissance", "epargneCroissance"],
  },
  {
    id: "associationsCaritatives",
    labelA: "Association A",
    labelB: "Association B",
    sujetA: "le montant cumulé des fonds collectés par l'association A",
    sujetB: "le montant cumulé des fonds collectés par l'association B",
    unite: "€",
    periode: "mois",
    branchesAutorisees: ["villesCroissance", "epargneCroissance"],
  },
  { id: "youtube", labelA: "Chaîne A", labelB: "Chaîne B", sujetA: "le nombre d'abonnés de la chaîne YouTube A", sujetB: "le nombre d'abonnés de la chaîne YouTube B", unite: "abonnés", periode: "mois" },
  { id: "vtc", labelA: "Compagnie A", labelB: "Compagnie B", sujetA: "le nombre de courses mensuelles de la compagnie de VTC A", sujetB: "le nombre de courses mensuelles de la compagnie de VTC B", unite: "courses", periode: "mois" },
  {
    id: "reservesPoissons",
    labelA: "Réserve pêchée",
    labelB: "Réserve protégée",
    sujetA: "la population de poissons de la réserve pêchée (en déclin)",
    sujetB: "la population de poissons de la réserve protégée (en expansion)",
    unite: "poissons",
    periode: "an",
    branchesAutorisees: ["stockDemande"],
  },
];
