/**
 * Couche A — banque de contextes pour "Inégalité de Bienaymé-Tchebychev" (chapitre 5), voir
 * `promptgen37refonte.md`, section "Banque de contextes". Un tirage aléatoire dans cette banque
 * habille chaque exercice (population, caractère, unité, plage réaliste pour x̄/σ).
 *
 * Chaque entrée reste un SUJET GRAMMATICAL SINGULIER (jamais un pluriel comme "les précipitations")
 * pour que les phrases d'énoncé, écrites une seule fois pour les 30 entrées (`formatBienaymeTchebychev.ts`),
 * n'aient jamais à gérer une conjugaison "sont" à la place de "est" — l'entrée "stations météo/
 * précipitations" de la spec est ainsi reformulée en "le niveau de précipitations mensuelles"
 * (singulier), jamais "les précipitations mensuelles" (pluriel).
 *
 * `plageXBar`/`plageSigma` : deux plages INDÉPENDANTES, jamais confondues — `plageXBar` borne la
 * valeur de x̄ tirée pour UN exercice donné (un sous-intervalle raisonnable de la bande réaliste
 * donnée par la spec) ; `plageSigma` borne σ, toujours NETTEMENT inférieur à la largeur totale de
 * cette bande réaliste (jamais une simple fraction de `plageXBar`, qui ne représente que la
 * variabilité de la moyenne d'un exercice à l'autre, pas la dispersion réelle du caractère).
 * Le type `ContexteBienaymeTchebychev` lui-même vit dans `src/core/bienaymeTchebychev.types.ts` —
 * ce fichier n'importe jamais depuis `src/generateurs/`, jamais l'inverse (règle d'architecture
 * non négociable).
 */
import type { ContexteBienaymeTchebychev } from "../../core/bienaymeTchebychev.types";

export const CONTEXTES: ContexteBienaymeTchebychev[] = [
  {
    population: "étudiants",
    caractereDefini: "la taille",
    caractereIndefini: "une taille",
    caractereComplement: "taille",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "cm",
    plageXBar: [165, 188],
    plageSigma: [5, 12],
  },
  {
    population: "étudiants",
    caractereDefini: "le poids",
    caractereIndefini: "un poids",
    caractereComplement: "poids",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "kg",
    plageXBar: [58, 82],
    plageSigma: [5, 10],
  },
  {
    population: "étudiants",
    caractereDefini: "la durée de sommeil",
    caractereIndefini: "une durée de sommeil",
    caractereComplement: "durée de sommeil",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "h",
    plageXBar: [6, 8],
    plageSigma: [1, 2],
  },
  {
    population: "athlètes",
    caractereDefini: "la taille",
    caractereIndefini: "une taille",
    caractereComplement: "taille",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "cm",
    plageXBar: [172, 195],
    plageSigma: [5, 12],
  },
  {
    population: "athlètes",
    caractereDefini: "le poids",
    caractereIndefini: "un poids",
    caractereComplement: "poids",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "kg",
    plageXBar: [62, 92],
    plageSigma: [6, 12],
  },
  {
    population: "athlètes",
    caractereDefini: "la fréquence cardiaque au repos",
    caractereIndefini: "une fréquence cardiaque au repos",
    caractereComplement: "fréquence cardiaque au repos",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "bpm",
    plageXBar: [48, 68],
    plageSigma: [4, 10],
  },
  {
    population: "athlètes",
    caractereDefini: "le temps sur 100 m",
    caractereIndefini: "un temps sur 100 m",
    caractereComplement: "temps sur 100 m",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "s",
    plageXBar: [11, 15],
    plageSigma: [1, 2],
  },
  {
    population: "athlètes",
    caractereDefini: "le temps sur 1500 m",
    caractereIndefini: "un temps sur 1500 m",
    caractereComplement: "temps sur 1500 m",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "min",
    plageXBar: [4, 6],
    plageSigma: [1, 2],
  },
  {
    population: "athlètes",
    caractereDefini: "le nombre d'heures d'entraînement par semaine",
    caractereIndefini: "un nombre d'heures d'entraînement par semaine",
    caractereComplement: "nombre d'heures d'entraînement par semaine",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "h",
    plageXBar: [6, 16],
    plageSigma: [2, 5],
  },
  {
    population: "athlètes",
    caractereDefini: "la distance au saut en longueur",
    caractereIndefini: "une distance au saut en longueur",
    caractereComplement: "distance au saut en longueur",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "cm",
    plageXBar: [380, 650],
    plageSigma: [30, 80],
  },
  {
    population: "salariés",
    caractereDefini: "le salaire mensuel",
    caractereIndefini: "un salaire mensuel",
    caractereComplement: "salaire mensuel",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "€",
    plageXBar: [2200, 4800],
    plageSigma: [300, 900],
  },
  {
    population: "salariés",
    caractereDefini: "l'ancienneté",
    caractereIndefini: "une ancienneté",
    caractereComplement: "ancienneté",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "ans",
    plageXBar: [3, 20],
    plageSigma: [2, 6],
  },
  {
    population: "salariés",
    caractereDefini: "le temps de trajet domicile-travail",
    caractereIndefini: "un temps de trajet domicile-travail",
    caractereComplement: "temps de trajet domicile-travail",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "min",
    plageXBar: [15, 60],
    plageSigma: [5, 15],
  },
  {
    population: "clients d'un magasin",
    caractereDefini: "le montant du panier",
    caractereIndefini: "un montant de panier",
    caractereComplement: "montant du panier",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "€",
    plageXBar: [20, 180],
    plageSigma: [5, 40],
  },
  {
    population: "clients d'un site e-commerce",
    caractereDefini: "le temps passé sur le site",
    caractereIndefini: "un temps passé sur le site",
    caractereComplement: "temps passé sur le site",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "min",
    plageXBar: [3, 30],
    plageSigma: [2, 10],
  },
  {
    population: "employés d'un centre d'appels",
    caractereDefini: "la durée d'un appel",
    caractereIndefini: "une durée d'appel",
    caractereComplement: "durée d'un appel",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "min",
    plageXBar: [3, 15],
    plageSigma: [1, 4],
  },
  {
    population: "animaux d'un zoo",
    caractereDefini: "l'âge",
    caractereIndefini: "un âge",
    caractereComplement: "âge",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "ans",
    plageXBar: [3, 25],
    plageSigma: [2, 8],
  },
  {
    population: "chiens d'un refuge",
    caractereDefini: "le poids",
    caractereIndefini: "un poids",
    caractereComplement: "poids",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "kg",
    plageXBar: [8, 35],
    plageSigma: [3, 10],
  },
  {
    population: "poissons d'un aquarium",
    caractereDefini: "la longueur",
    caractereIndefini: "une longueur",
    caractereComplement: "longueur",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "cm",
    plageXBar: [5, 25],
    plageSigma: [2, 6],
  },
  {
    population: "véhicules d'un parc automobile",
    caractereDefini: "le kilométrage",
    caractereIndefini: "un kilométrage",
    caractereComplement: "kilométrage",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "km",
    plageXBar: [30000, 180000],
    plageSigma: [10000, 40000],
  },
  {
    population: "véhicules d'un parc automobile",
    caractereDefini: "la consommation",
    caractereIndefini: "une consommation",
    caractereComplement: "consommation",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "L/100km",
    plageXBar: [5, 10],
    plageSigma: [1, 2],
  },
  {
    population: "véhicules d'un parc automobile",
    caractereDefini: "l'âge",
    caractereIndefini: "un âge",
    caractereComplement: "âge",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "ans",
    plageXBar: [2, 15],
    plageSigma: [1, 4],
  },
  {
    population: "vélos en location",
    caractereDefini: "le nombre de trajets par mois",
    caractereIndefini: "un nombre de trajets par mois",
    caractereComplement: "nombre de trajets par mois",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "trajets",
    plageXBar: [10, 50],
    plageSigma: [4, 15],
  },
  {
    population: "smartphones",
    caractereDefini: "le prix",
    caractereIndefini: "un prix",
    caractereComplement: "prix",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "€",
    plageXBar: [200, 1200],
    plageSigma: [80, 300],
  },
  {
    population: "smartphones",
    caractereDefini: "l'autonomie de la batterie",
    caractereIndefini: "une autonomie de batterie",
    caractereComplement: "autonomie de batterie",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "h",
    plageXBar: [14, 35],
    plageSigma: [3, 8],
  },
  {
    population: "plantes d'une exploitation",
    caractereDefini: "la hauteur",
    caractereIndefini: "une hauteur",
    caractereComplement: "hauteur",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "cm",
    plageXBar: [20, 250],
    plageSigma: [10, 50],
  },
  {
    population: "arbres d'une forêt",
    caractereDefini: "le diamètre du tronc",
    caractereIndefini: "un diamètre de tronc",
    caractereComplement: "diamètre du tronc",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "cm",
    plageXBar: [15, 120],
    plageSigma: [5, 25],
  },
  {
    population: "fruits d'un verger",
    caractereDefini: "le poids",
    caractereIndefini: "un poids",
    caractereComplement: "poids",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "g",
    plageXBar: [70, 260],
    plageSigma: [15, 50],
  },
  {
    population: "champs d'une région",
    caractereDefini: "le rendement",
    caractereIndefini: "un rendement",
    caractereComplement: "rendement",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "t/ha",
    plageXBar: [3, 10],
    plageSigma: [1, 3],
  },
  {
    population: "villes d'une région",
    caractereDefini: "la température moyenne",
    caractereIndefini: "une température moyenne",
    caractereComplement: "température moyenne",
    moyenAccord: "moyenne",
    comprisAccord: "comprise",
    unite: "°C",
    plageXBar: [2, 28],
    plageSigma: [2, 6],
  },
  {
    population: "stations météo",
    caractereDefini: "le niveau de précipitations mensuelles",
    caractereIndefini: "un niveau de précipitations mensuelles",
    caractereComplement: "niveau de précipitations mensuelles",
    moyenAccord: "moyen",
    comprisAccord: "compris",
    unite: "mm",
    plageXBar: [30, 180],
    plageSigma: [15, 50],
  },
];
