/**
 * Couche A — banque de questions vrai/faux pour "Caractéristiques d'une fonction & fonctions de
 * référence" (chapitre 2, nommage propre à sa spec). 245 affirmations pré-écrites (jamais générées
 * procéduralement), 7 thèmes de 35 questions chacun (20 initiales, transcrites depuis l'artefact
 * validé par l'utilisateur, puis 15 par thème ajoutées ultérieurement pour enrichir la banque).
 * Chaque affirmation vérifiée mathématiquement à la rédaction.
 */
import type { QuestionVraiFaux, VarianteQuizFonctionsReference } from "../../core/quizFonctionsReference.types";

export const BANQUE_QUIZ_FONCTIONS_REFERENCE: Record<VarianteQuizFonctionsReference, QuestionVraiFaux[]> = {
  vocabulaire: [
    { enonce: "Le domaine de définition d'une fonction est l'ensemble des valeurs de x pour lesquelles la fonction est définie.", reponse: true, justification: "C'est la définition même du domaine de définition." },
    { enonce: "Un zéro d'une fonction est une valeur de x telle que f(x)=0.", reponse: true, justification: "Définition du mot « zéro », aussi appelé racine." },
    { enonce: "L'ordonnée à l'origine d'une fonction est la valeur de f(0), lorsqu'elle existe.", reponse: true, justification: "Par définition, c'est l'ordonnée du point d'intersection avec l'axe des ordonnées." },
    { enonce: "Une fonction ne peut avoir qu'un seul zéro.", reponse: false, justification: "Faux : une fonction peut avoir 0, 1, plusieurs, voire une infinité de zéros (ex. f(x)=x²-1 a deux zéros : -1 et 1)." },
    { enonce: "Si une fonction est strictement croissante sur un intervalle, alors pour tous réels a<b de cet intervalle, f(a)<f(b).", reponse: true, justification: "C'est exactement la définition de la stricte croissance." },
    { enonce: "Une fonction constante sur un intervalle n'admet ni maximum ni minimum sur cet intervalle.", reponse: false, justification: "Faux : elle admet à la fois un maximum et un minimum sur cet intervalle, tous deux égaux à sa valeur constante." },
    { enonce: "Une asymptote horizontale peut être coupée par la courbe en un ou plusieurs points, contrairement à une asymptote verticale.", reponse: true, justification: "Une asymptote horizontale décrit un comportement à l'infini : la courbe peut la croiser pour des valeurs finies de x." },
    { enonce: "Une asymptote verticale correspond en général à une valeur de x exclue du domaine de définition.", reponse: true, justification: "C'est la façon dont elle apparaît dans les fonctions étudiées dans ce chapitre." },
    { enonce: "Le maximum d'une fonction sur un intervalle est nécessairement atteint en un unique point.", reponse: false, justification: "Faux : si la fonction est constante sur un palier au sommet, le maximum peut être atteint en plusieurs points, voire sur tout un intervalle." },
    { enonce: "Si f(3)=0, alors 3 est un zéro de f.", reponse: true, justification: "C'est exactement la définition d'un zéro." },
    { enonce: "Le graphe d'une fonction peut couper l'axe des ordonnées en plusieurs points.", reponse: false, justification: "Faux : une fonction associe une seule image à chaque x, donc son graphe coupe l'axe des ordonnées (x=0) en au plus un point." },
    { enonce: "Si une fonction n'est pas définie en x=2, alors 2 n'appartient pas au domaine de définition.", reponse: true, justification: "Vrai, par définition du domaine." },
    { enonce: "Une fonction peut être croissante sur un intervalle et décroissante sur un autre intervalle.", reponse: true, justification: "Vrai — c'est même le cas général pour la plupart des fonctions étudiées dans ce chapitre." },
    { enonce: "L'image d'une fonction est toujours égale à ℝ tout entier.", reponse: false, justification: "Faux : l'image dépend de la fonction (ex. l'image de x² est [0;+∞[)." },
    { enonce: "Deux zéros distincts d'une fonction peuvent avoir des ordonnées différentes.", reponse: false, justification: "Faux : par définition, un zéro est un point où f(x)=0, donc tous les zéros ont pour ordonnée 0." },
    { enonce: "Une fonction peut ne posséder aucun zéro.", reponse: true, justification: "Vrai, par exemple si son image ne contient jamais la valeur 0." },
    { enonce: "Sur un intervalle où une fonction est croissante, plus x augmente, plus f(x) diminue.", reponse: false, justification: "Faux : c'est l'inverse — sur un intervalle de croissance, f(x) augmente quand x augmente." },
    { enonce: "Toute valeur exclue du domaine de définition correspond forcément à une asymptote verticale.", reponse: false, justification: "Faux : une valeur peut être exclue sans qu'il y ait d'asymptote (par exemple un simple « trou », un point isolé manquant sur la courbe)." },
    { enonce: "f(a) désigne l'ordonnée du point de la courbe d'abscisse a, lorsque a appartient au domaine de définition.", reponse: true, justification: "Vrai, c'est la lecture graphique de f(a)." },
    { enonce: "Un minimum local d'une fonction est toujours inférieur à tous les maximums locaux de cette même fonction.", reponse: false, justification: "Faux : un minimum local à un endroit peut très bien être supérieur à un maximum local situé ailleurs sur la courbe." },
    { enonce: "Une fonction strictement décroissante sur un intervalle vérifie : pour tous réels a et b de cet intervalle tels que a<b, on a f(a)>f(b).", reponse: true, justification: "C'est exactement la définition de la stricte décroissance." },
    { enonce: "L'ensemble des valeurs prises par une fonction, c'est-à-dire l'ensemble de ses ordonnées possibles, s'appelle son image.", reponse: true, justification: "Définition même de l'image d'une fonction." },
    { enonce: "Un maximum local d'une fonction est nécessairement la plus grande valeur prise par cette fonction sur tout son domaine.", reponse: false, justification: "Faux : un maximum local n'est le plus grand que localement, au voisinage du point considéré — il peut être dépassé ailleurs sur la courbe." },
    { enonce: "Une fonction constante sur un intervalle est à la fois croissante au sens large et décroissante au sens large sur cet intervalle.", reponse: true, justification: "Vrai : pour a<b de cet intervalle, f(a)=f(b), ce qui vérifie à la fois f(a)≤f(b) et f(a)≥f(b)." },
    { enonce: "Deux fonctions ayant le même domaine de définition ont nécessairement la même image.", reponse: false, justification: "Faux : le domaine ne détermine pas l'image — deux fonctions peuvent partager exactement le même domaine tout en prenant des valeurs totalement différentes." },
    { enonce: "Sur un graphique, l'axe des abscisses porte les valeurs de x, et l'axe des ordonnées porte les valeurs de f(x).", reponse: true, justification: "Convention universelle de lecture d'un repère." },
    { enonce: "Un point où la courbe d'une fonction coupe l'axe des abscisses correspond à un zéro de cette fonction.", reponse: true, justification: "En ce point, l'ordonnée vaut 0, donc f(x)=0 : c'est bien la définition d'un zéro." },
    { enonce: "Si f(2)=5, alors le point (5;2) appartient à la courbe représentative de f.", reponse: false, justification: "Faux : c'est le point (2;5) qui appartient à la courbe — l'abscisse est 2, l'ordonnée (l'image) est 5, pas l'inverse." },
    { enonce: "Une fonction peut être strictement croissante sur son domaine tout entier sans jamais atteindre de maximum global.", reponse: true, justification: "Vrai, par exemple une fonction dont les valeurs augmentent indéfiniment sans jamais plafonner." },
    { enonce: "Lire graphiquement le domaine de définition d'une fonction revient à projeter sa courbe sur l'axe des abscisses.", reponse: true, justification: "C'est la technique standard de lecture graphique du domaine." },
    { enonce: "Lire graphiquement l'image d'une fonction revient à projeter sa courbe sur l'axe des ordonnées.", reponse: true, justification: "C'est la technique standard de lecture graphique de l'image." },
    { enonce: "Si une fonction admet un minimum global, cette valeur minimale est nécessairement atteinte en un seul point de son domaine.", reponse: false, justification: "Faux : une fonction constante, par exemple, atteint sa valeur minimale (qui est aussi son maximum) en tous les points de son domaine." },
    { enonce: "Le domaine de définition d'une fonction est toujours un intervalle.", reponse: false, justification: "Faux : le domaine peut être une réunion de plusieurs intervalles, par exemple ℝ privé d'une valeur." },
    { enonce: "L'image d'une fonction ne peut jamais contenir de valeurs négatives.", reponse: false, justification: "Faux : cela dépend entièrement de la fonction — de nombreuses fonctions prennent des valeurs négatives." },
    { enonce: "Si une fonction est croissante sur [1;5] puis croissante sur [5;9], alors elle est croissante sur [1;9] tout entier.", reponse: true, justification: "Vrai : les deux morceaux se raccordent en x=5, la croissance se transmet par transitivité sur l'intervalle réuni." },
  ],
  sixFonctions: [
    { enonce: "La fonction carrée x↦x² est définie sur ℝ tout entier.", reponse: true, justification: "Aucune valeur de x n'est exclue pour élever au carré." },
    { enonce: "La fonction racine carrée x↦√x n'est définie que pour x≥0.", reponse: true, justification: "La racine carrée d'un nombre négatif n'existe pas dans ℝ." },
    { enonce: "La fonction cube x↦x³ n'est définie que pour x≥0.", reponse: false, justification: "Faux : elle est définie sur ℝ tout entier (ex. (-2)³=-8)." },
    { enonce: "La fonction racine cubique x↦∛x est définie pour tout réel x, y compris les négatifs.", reponse: true, justification: "Ex. ∛(-8)=-2, car (-2)³=-8." },
    { enonce: "La fonction inverse x↦1/x n'est pas définie en x=0.", reponse: true, justification: "Diviser par 0 est impossible." },
    { enonce: "La fonction valeur absolue n'est définie que pour x≥0.", reponse: false, justification: "Faux : elle est définie sur ℝ tout entier — |x| a un sens pour tout réel x, y compris négatif." },
    { enonce: "L'image de la fonction carrée est ℝ tout entier.", reponse: false, justification: "Faux : un carré n'est jamais négatif, l'image est [0;+∞[." },
    { enonce: "L'image de la fonction cube est ℝ tout entier.", reponse: true, justification: "x³ peut prendre n'importe quelle valeur réelle, positive comme négative." },
    { enonce: "L'image de la fonction valeur absolue est [0;+∞[.", reponse: true, justification: "|x| n'est jamais négatif." },
    { enonce: "La fonction inverse s'annule en x=0.", reponse: false, justification: "Faux : 1/x n'est jamais nulle (aucun zéro) et n'est même pas définie en 0." },
    { enonce: "La fonction carrée est une fonction paire.", reponse: true, justification: "f(-x)=f(x) : (-x)²=x²." },
    { enonce: "La fonction cube est une fonction paire.", reponse: false, justification: "Faux, elle est impaire : (-x)³=-(x³)." },
    { enonce: "La fonction valeur absolue est une fonction paire.", reponse: true, justification: "|-x|=|x| pour tout réel x." },
    { enonce: "La fonction inverse est une fonction impaire.", reponse: true, justification: "1/(-x) = -1/x pour tout x≠0." },
    { enonce: "La fonction racine carrée est une fonction impaire.", reponse: false, justification: "Faux : son domaine [0;+∞[ n'est même pas symétrique par rapport à 0, elle ne peut donc être ni paire ni impaire." },
    { enonce: "La fonction racine cubique est une fonction impaire.", reponse: true, justification: "∛(-x) = -∛x pour tout réel x." },
    { enonce: "Les fonctions carrée, cube, racine carrée, racine cubique et valeur absolue ont toutes un zéro strictement positif.", reponse: false, justification: "Faux : leur unique zéro se situe en x=0, qui n'est pas strictement positif." },
    { enonce: "La fonction inverse possède un unique zéro, en x=0.", reponse: false, justification: "Faux : elle n'a aucun zéro (1/x ne s'annule jamais) et n'est même pas définie en 0." },
    { enonce: "Les fonctions carrée et valeur absolue ont toutes deux un minimum global valant 0, atteint uniquement en x=0.", reponse: true, justification: "x²=0 et |x|=0 uniquement lorsque x=0." },
    { enonce: "La fonction cube admet un minimum global sur ℝ.", reponse: false, justification: "Faux : x³ n'est ni majorée ni minorée sur ℝ (elle tend vers -∞ et vers +∞), elle n'a donc pas d'extremum global." },
    { enonce: "La fonction racine carrée est strictement croissante sur ℝ tout entier.", reponse: false, justification: "Faux : elle n'est même pas définie pour x<0 — elle est strictement croissante seulement sur son domaine [0;+∞[, pas sur ℝ tout entier." },
    { enonce: "Les fonctions cube et racine cubique sont toutes deux strictement croissantes sur ℝ tout entier.", reponse: true, justification: "Vrai : x³ et ∛x augmentent continûment sur tout leur domaine, qui est ℝ pour les deux." },
    { enonce: "La fonction carrée et la fonction valeur absolue ont exactement la même allure : toutes deux dessinent un V.", reponse: false, justification: "Faux : la fonction carrée dessine une parabole (courbe lisse, arrondie au sommet), la fonction valeur absolue dessine un V à point anguleux — deux allures différentes malgré des propriétés communes (parité, minimum 0 en x=0)." },
    { enonce: "Parmi les 6 fonctions de référence, seule la fonction inverse possède des asymptotes (une verticale et une horizontale).", reponse: true, justification: "Vrai : aucune des cinq autres familles (carré, cube, racine carrée, racine cubique, valeur absolue) n'admet d'asymptote." },
    { enonce: "Parmi les 6 fonctions de référence, la fonction carrée est la seule dont le domaine de définition n'est pas ℝ tout entier.", reponse: false, justification: "Faux : le domaine de la fonction carrée est ℝ tout entier (c'est son image qui est restreinte à [0;+∞[, pas son domaine) — ce sont plutôt la racine carrée ([0;+∞[) et l'inverse (ℝ\\{0}) qui ont un domaine restreint." },
    { enonce: "Parmi les 6 fonctions de référence, exactement trois sont impaires : la fonction cube, la fonction racine cubique et la fonction inverse.", reponse: true, justification: "Vrai : parmi les 3 fonctions restantes, carré et valeur absolue sont paires, et racine carrée n'est ni paire ni impaire." },
    { enonce: "Parmi les 6 fonctions de référence, exactement deux sont paires : la fonction carrée et la fonction racine carrée.", reponse: false, justification: "Faux : la racine carrée n'est ni paire ni impaire (son domaine [0;+∞[ n'est pas symétrique par rapport à 0) — les deux fonctions paires sont en réalité la fonction carrée et la fonction valeur absolue." },
    { enonce: "Parmi les 6 fonctions de référence, quatre ont pour image ℝ tout entier : le cube, la racine cubique, l'inverse et la racine carrée.", reponse: false, justification: "Faux : l'image de l'inverse est ℝ privé de 0 (1/x ne s'annule jamais) et l'image de la racine carrée est [0;+∞[ — seules le cube et la racine cubique ont réellement pour image ℝ tout entier." },
    { enonce: "Parmi les 6 fonctions de référence, exactement deux ont pour image ℝ tout entier : la fonction cube et la fonction racine cubique.", reponse: true, justification: "Vrai : x³ et ∛x peuvent prendre n'importe quelle valeur réelle, contrairement aux 4 autres familles dont l'image est restreinte." },
    { enonce: "∛8=2 et 2³=8 : la fonction racine cubique et la fonction cube sont réciproques l'une de l'autre.", reponse: true, justification: "Vrai : appliquer l'une puis l'autre à un nombre le redonne inchangé, c'est la définition de deux fonctions réciproques." },
    { enonce: "La fonction carrée est la fonction réciproque de la fonction racine carrée, pour tout réel x.", reponse: false, justification: "Faux : ce n'est vrai que pour x≥0 — par exemple (√4)²=4 fonctionne, mais √((-2)²)=√4=2 et non -2, donc la réciprocité ne vaut pas pour tout réel x." },
    { enonce: "Les fonctions cube, racine cubique et inverse ont chacune une courbe passant par les points (1;1) et (-1;-1).", reponse: true, justification: "Vrai : 1³=1 et (-1)³=-1 ; ∛1=1 et ∛(-1)=-1 ; 1/1=1 et 1/(-1)=-1 — les trois vérifient ces deux points." },
    { enonce: "Les 6 fonctions de référence passent toutes par l'origine du repère (0;0).", reponse: false, justification: "Faux : la fonction inverse n'est même pas définie en x=0, sa courbe ne passe donc jamais par l'origine — les 5 autres, elles, y passent bien." },
    { enonce: "Parmi les 6 fonctions de référence, l'inverse est la seule qui ne soit pas définie en x=0.", reponse: true, justification: "Vrai : carré, cube, racine carrée, racine cubique et valeur absolue valent toutes 0 en x=0 ; seule l'inverse n'y est pas définie." },
    { enonce: "La fonction carrée est la seule, parmi les 6 fonctions de référence, dont le domaine est ℝ tout entier et l'image ne contient aucune valeur négative.", reponse: false, justification: "Faux : la fonction valeur absolue partage exactement les deux mêmes propriétés (domaine ℝ, image [0;+∞[)." },
  ],
  carreCube: [
    { enonce: "0²=0 et 0³=0 : les deux courbes passent par l'origine du repère.", reponse: true, justification: "Calcul direct." },
    { enonce: "Pour tout réel x, on a (-x)²=x² : la courbe de la fonction carrée est symétrique par rapport à l'axe des ordonnées.", reponse: true, justification: "C'est la traduction géométrique de la parité de la fonction carrée." },
    { enonce: "Pour tout réel x, on a (-x)³=x³.", reponse: false, justification: "Faux : (-x)³=-(x³), ce qui n'est égal à x³ que si x=0." },
    { enonce: "La courbe de la fonction cube est symétrique par rapport à l'origine du repère.", reponse: true, justification: "Conséquence directe de son imparité." },
    { enonce: "(-2)²=4 alors que (-2)³=-8.", reponse: true, justification: "Calcul direct : 4 et -8." },
    { enonce: "x² est toujours strictement positif, quel que soit le réel x.", reponse: false, justification: "Faux : x²=0 lorsque x=0, ce n'est donc pas strictement positif en ce point précis." },
    { enonce: "x³ peut être négatif, contrairement à x².", reponse: true, justification: "Ex. (-1)³=-1<0, alors que tout carré est toujours ≥0." },
    { enonce: "Pour 0<x<1, on a x³<x².", reponse: true, justification: "Ex. x=0,5 : x³=0,125 et x²=0,25." },
    { enonce: "Pour tout x>1, on a x³<x².", reponse: false, justification: "Faux : c'est l'inverse pour x>1, ex. x=2 : x³=8>x²=4." },
    { enonce: "Les points (1;1) et (-1;1) appartiennent tous deux à la courbe de la fonction carrée.", reponse: true, justification: "1²=1 et (-1)²=1." },
    { enonce: "Le point (-1;1) appartient à la courbe de la fonction cube.", reponse: false, justification: "Faux : (-1)³=-1, donc le point de la courbe d'abscisse -1 est (-1;-1), pas (-1;1)." },
    { enonce: "La fonction cube est strictement croissante sur ℝ tout entier, sans aucune portion décroissante.", reponse: true, justification: "x³ croît continûment sur tout son domaine." },
    { enonce: "La fonction carrée est strictement croissante sur ℝ tout entier.", reponse: false, justification: "Faux : elle décroît sur ]-∞;0] puis croît sur [0;+∞[, jamais croissante sur tout ℝ." },
    { enonce: "La fonction carrée admet un minimum global qui vaut 0.", reponse: true, justification: "Atteint en x=0." },
    { enonce: "La fonction cube admet un minimum global.", reponse: false, justification: "Faux : comme vu au thème précédent, x³ n'est pas minorée sur ℝ." },
    { enonce: "Pour x=1, la fonction carrée et la fonction cube prennent exactement la même valeur.", reponse: true, justification: "1²=1³=1." },
    { enonce: "Pour tout réel x, x² est toujours supérieur ou égal à x³.", reponse: false, justification: "Faux : pour x>1 (ex. x=2), x³=8>x²=4." },
    { enonce: "La fonction carrée est paire, la fonction cube est impaire.", reponse: true, justification: "Conséquence directe des égalités (-x)²=x² et (-x)³=-(x³)." },
    { enonce: "Sur l'intervalle [0;+∞[, la fonction carrée est décroissante.", reponse: false, justification: "Faux : elle y est au contraire strictement croissante." },
    { enonce: "Sur l'intervalle ]-∞;0], la fonction cube est décroissante.", reponse: false, justification: "Faux : x³ est strictement croissante partout, y compris sur cet intervalle." },
    { enonce: "Pour tout réel x strictement négatif, x² est strictement positif alors que x³ est strictement négatif.", reponse: true, justification: "Vrai : un carré de nombre non nul est toujours positif, alors qu'un cube conserve le signe de x." },
    { enonce: "Pour tout réel x, l'égalité x²=x³ n'est vérifiée que pour x=1.", reponse: false, justification: "Faux : x²=x³ équivaut à x²(x-1)=0, donc à x=0 ou x=1 — x=0 est aussi solution, pas seulement x=1." },
    { enonce: "Les courbes des fonctions carrée et cube se coupent exactement aux points (0;0) et (1;1).", reponse: true, justification: "Vrai : x²=x³ équivaut à x²(x-1)=0, dont les seules solutions sont x=0 et x=1." },
    { enonce: "La fonction carrée est bijective sur ℝ tout entier.", reponse: false, justification: "Faux : elle n'est pas injective — par exemple f(-2)=f(2)=4, deux abscisses distinctes donnent la même image." },
    { enonce: "La fonction cube est bijective de ℝ vers ℝ.", reponse: true, justification: "Vrai : elle est strictement croissante sur ℝ (donc injective) et son image est ℝ tout entier (donc surjective)." },
    { enonce: "Pour tout réel x, (x²)³=(x³)².", reponse: true, justification: "Vrai : les deux expressions valent x⁶." },
    { enonce: "La fonction carrée transforme deux nombres opposés x et -x en la même image.", reponse: true, justification: "Conséquence directe de sa parité : (-x)²=x²." },
    { enonce: "La fonction cube transforme deux nombres opposés x et -x en la même image.", reponse: false, justification: "Faux : elle les transforme en deux images opposées, (-x)³=-(x³), pas en la même image." },
    { enonce: "Sur l'intervalle [0;1], on a x³≤x² pour tout x de cet intervalle.", reponse: true, justification: "Vrai : x²(x-1)≤0 sur [0;1] car x²≥0 et x-1≤0, donc x³-x²≤0." },
    { enonce: "Sur l'intervalle [1;+∞[, on a x³≤x² pour tout x de cet intervalle.", reponse: false, justification: "Faux : dès que x>1 (ex. x=2), x³=8>x²=4 — l'inégalité ne vaut que pour x=1 (égalité) et s'inverse au-delà." },
    { enonce: "La droite d'équation y=x coupe la courbe de la fonction cube en trois points, d'abscisses -1, 0 et 1.", reponse: true, justification: "Vrai : x³=x équivaut à x(x²-1)=0, dont les solutions sont -1, 0 et 1." },
    { enonce: "La droite d'équation y=x coupe la courbe de la fonction carrée en trois points.", reponse: false, justification: "Faux : x²=x équivaut à x(x-1)=0, qui n'a que deux solutions, x=0 et x=1." },
    { enonce: "Sur l'intervalle [-2;1], la fonction cube atteint sa plus grande valeur en x=1.", reponse: true, justification: "Vrai : la fonction cube est strictement croissante sur ℝ, son maximum sur un intervalle fermé est donc toujours atteint à l'extrémité droite." },
    { enonce: "Sur l'intervalle [-1;2], la fonction carrée atteint son maximum en x=0.", reponse: false, justification: "Faux : x=0 donne au contraire le minimum (0) sur cet intervalle ; le maximum est atteint en x=2, où x²=4." },
    { enonce: "La courbe de la fonction cube est toujours située au-dessus de la courbe de la fonction carrée, pour tout réel x.", reponse: false, justification: "Faux : par exemple pour x=0,5, x³=0,125<x²=0,25 — la fonction cube n'est au-dessus que pour x>1." },
  ],
  racines: [
    { enonce: "√9=3.", reponse: true, justification: "Car 3²=9." },
    { enonce: "√(-4) est un nombre réel.", reponse: false, justification: "Faux : la racine carrée n'est définie que pour des nombres positifs ou nuls, √(-4) n'existe pas dans ℝ." },
    { enonce: "∛(-8)=-2, car (-2)³=-8.", reponse: true, justification: "Calcul direct." },
    { enonce: "La fonction racine cubique est définie pour tout réel, y compris les négatifs, contrairement à la fonction racine carrée.", reponse: true, justification: "∛x accepte les négatifs, √x non." },
    { enonce: "La fonction racine carrée est définie sur ℝ tout entier.", reponse: false, justification: "Faux : uniquement sur [0;+∞[." },
    { enonce: "√0=0 et ∛0=0 : les deux courbes passent par l'origine.", reponse: true, justification: "Calcul direct." },
    { enonce: "La fonction racine carrée est strictement croissante sur tout son domaine de définition.", reponse: true, justification: "√x augmente quand x augmente, sur [0;+∞[." },
    { enonce: "La fonction racine cubique est strictement croissante sur ℝ tout entier.", reponse: true, justification: "∛x augmente quand x augmente, sur tout ℝ." },
    { enonce: "Pour tout x>1, on a √x>x.", reponse: false, justification: "Faux : pour x>1, √x<x (ex. √4=2<4)." },
    { enonce: "Pour 0<x<1, on a √x>x.", reponse: true, justification: "Ex. √0,25=0,5>0,25." },
    { enonce: "L'image de la fonction racine carrée contient des valeurs négatives.", reponse: false, justification: "Faux : √x≥0 pour tout x du domaine, l'image est [0;+∞[." },
    { enonce: "L'image de la fonction racine cubique est ℝ tout entier.", reponse: true, justification: "∛x peut prendre n'importe quelle valeur réelle." },
    { enonce: "∛27 vaut 9.", reponse: false, justification: "Faux : ∛27=3 (car 3³=27), pas 9." },
    { enonce: "La fonction racine carrée admet un unique zéro, en x=0.", reponse: true, justification: "√0=0, et √x>0 pour tout x>0." },
    { enonce: "La fonction racine cubique admet un unique zéro, en x=0.", reponse: true, justification: "∛0=0, et ∛x est du même signe que x sinon." },
    { enonce: "La fonction racine carrée est une fonction paire, tout comme la fonction carrée.", reponse: false, justification: "Faux : son domaine [0;+∞[ n'est même pas symétrique par rapport à 0, elle ne peut donc être ni paire ni impaire — pas plus paire qu'impaire." },
    { enonce: "√16=8.", reponse: false, justification: "Faux : √16=4 (car 4²=16), pas 8." },
    { enonce: "La fonction racine cubique est une fonction paire, car ∛(-x)=∛x.", reponse: false, justification: "Faux : elle est impaire — ∛(-x)=-∛x, et non ∛x (sauf pour x=0)." },
    { enonce: "Ni la fonction racine carrée ni la fonction racine cubique n'admettent d'asymptote : toutes deux tendent vers l'infini sans jamais se stabiliser.", reponse: true, justification: "Aucune valeur exclue ni aucun comportement borné à l'infini pour ces deux familles." },
    { enonce: "La fonction racine carrée possède une asymptote verticale en x=0.", reponse: false, justification: "Faux : elle est parfaitement définie et continue en x=0 (où elle vaut 0), il n'y a ni asymptote ni discontinuité à cet endroit." },
    { enonce: "Pour tout réel x, √(x²)=x.", reponse: false, justification: "Faux : √(x²)=|x|, pas x — par exemple √((-3)²)=√9=3, et non -3." },
    { enonce: "Pour tout réel x, √(x²)=|x|.", reponse: true, justification: "Vrai : élever au carré efface le signe, la racine carrée rétablit ensuite une valeur positive ou nulle." },
    { enonce: "Pour tout réel x, ∛(x³)=|x|.", reponse: false, justification: "Faux : ∛(x³)=x pour tout réel x (la racine cubique conserve le signe) — par exemple ∛((-2)³)=∛(-8)=-2, et non |-2|=2." },
    { enonce: "Pour tout réel x, ∛(x³)=x.", reponse: true, justification: "Vrai : contrairement à la racine carrée, la racine cubique restitue exactement x, signe compris." },
    { enonce: "√25=5 et non -5, bien que (-5)² vale également 25.", reponse: true, justification: "Vrai : par convention, le symbole √ désigne toujours la racine positive ou nulle." },
    { enonce: "L'équation x²=25 admet √25=5 comme unique solution.", reponse: false, justification: "Faux : l'équation x²=25 a deux solutions, x=5 et x=-5 — √25, lui, ne désigne qu'un seul nombre, 5." },
    { enonce: "Pour tout x≥0, on a (√x)²=x.", reponse: true, justification: "Vrai, par définition de la racine carrée sur son domaine." },
    { enonce: "Pour tout réel x, on a (√x)²=x.", reponse: false, justification: "Faux : cette égalité n'a de sens que pour x≥0, car √x n'est pas définie pour x<0." },
    { enonce: "∛64=4, car 4³=64.", reponse: true, justification: "Calcul direct." },
    { enonce: "∛(-27)=3.", reponse: false, justification: "Faux : ∛(-27)=-3, car (-3)³=-27, et non 3." },
    { enonce: "√1=1 et ∛1=1 : les courbes des fonctions racine carrée et racine cubique se croisent au point (1;1).", reponse: true, justification: "Calcul direct." },
    { enonce: "Pour tout x compris strictement entre 0 et 1, on a ∛x<x.", reponse: false, justification: "Faux : c'est l'inverse — pour 0<x<1, ∛x>x (ex. ∛0,5≈0,79>0,5)." },
    { enonce: "Pour tout x>1, on a ∛x<x.", reponse: true, justification: "Vrai, ex. ∛8=2<8 — la racine cubique croît beaucoup plus lentement que x au-delà de 1." },
    { enonce: "La fonction racine cubique croît plus vite que la fonction x↦x pour x>1.", reponse: false, justification: "Faux : c'est l'inverse, elle croît plus lentement (ex. ∛1000=10, bien moins que 1000)." },
    { enonce: "√4+√9=5, mais √(4+9)=√13≠5 : la racine carrée d'une somme n'est pas la somme des racines carrées.", reponse: true, justification: "Vrai : √13≈3,61, différent de 5 — un piège classique à éviter." },
  ],
  inverse: [
    { enonce: "La fonction inverse n'est pas définie en x=0.", reponse: true, justification: "Diviser par 0 est impossible." },
    { enonce: "x=0 est une asymptote verticale de la fonction inverse.", reponse: true, justification: "La courbe s'en approche indéfiniment sans jamais l'atteindre." },
    { enonce: "y=0 (l'axe des abscisses) est une asymptote horizontale de la fonction inverse.", reponse: true, justification: "1/x se rapproche de 0 quand x tend vers ±∞." },
    { enonce: "La courbe de la fonction inverse coupe l'axe des abscisses en x=0.", reponse: false, justification: "Faux : la fonction n'est même pas définie en 0, et 1/x n'est de toute façon jamais nulle — la courbe ne coupe jamais l'axe des abscisses." },
    { enonce: "1/(-2)=-0,5.", reponse: true, justification: "Calcul direct." },
    { enonce: "La fonction inverse est une fonction paire.", reponse: false, justification: "Faux, elle est impaire : 1/(-x)=-1/x, et non 1/x." },
    { enonce: "La fonction inverse est strictement décroissante sur ℝ\\\\{0} tout entier.", reponse: false, justification: "Faux : elle est décroissante sur ]-∞;0[ ET décroissante sur ]0;+∞[ séparément, mais pas globalement (ex. f(-1)=-1<f(1)=1 alors que -1<1)." },
    { enonce: "La fonction inverse est strictement décroissante sur l'intervalle ]0;+∞[.", reponse: true, justification: "Sur cet intervalle pris isolément, 1/x diminue bien quand x augmente." },
    { enonce: "Quand x tend vers 0 par valeurs positives, 1/x tend vers +∞.", reponse: true, justification: "Comportement classique au voisinage de l'asymptote verticale." },
    { enonce: "Quand x tend vers +∞, 1/x tend vers +∞.", reponse: false, justification: "Faux : 1/x tend au contraire vers 0 (par valeurs positives) quand x tend vers +∞." },
    { enonce: "La fonction inverse n'admet aucun zéro.", reponse: true, justification: "1/x n'est jamais égal à 0, quel que soit x≠0." },
    { enonce: "La courbe de la fonction inverse passe par le point (0;1).", reponse: false, justification: "Faux : la fonction n'est pas définie en x=0, ce point n'existe pas sur la courbe." },
    { enonce: "Pour x>0, 1/x est toujours strictement positif.", reponse: true, justification: "Le quotient de deux nombres positifs est positif." },
    { enonce: "Pour x<0, 1/x est toujours strictement négatif.", reponse: true, justification: "Le quotient de deux nombres de même signe négatif reste négatif." },
    { enonce: "La courbe de la fonction inverse touche son asymptote horizontale pour une grande valeur de x.", reponse: false, justification: "Faux : la courbe se rapproche indéfiniment de l'asymptote sans jamais la toucher, aussi grand que x devienne." },
    { enonce: "La courbe de la fonction inverse est symétrique par rapport à l'origine du repère.", reponse: true, justification: "Conséquence directe de son imparité." },
    { enonce: "1/4=4.", reponse: false, justification: "Faux : 1/4=0,25." },
    { enonce: "Dans une expression du type k/(x-a), la valeur x=-a doit être exclue du domaine de définition.", reponse: false, justification: "Faux : c'est x=a qui annule le dénominateur et doit être exclue, pas x=-a." },
    { enonce: "Quand x tend vers 0 par valeurs négatives, 1/x tend vers +∞.", reponse: false, justification: "Faux : elle tend vers -∞ dans ce cas (et vers +∞ seulement par valeurs positives)." },
    { enonce: "Les deux branches de la courbe de la fonction inverse sont situées dans les 1er et 3e quadrants du repère (mêmes signes pour x et 1/x).", reponse: true, justification: "Si x>0 alors 1/x>0 (1er quadrant) ; si x<0 alors 1/x<0 (3e quadrant)." },
    { enonce: "La fonction inverse est strictement décroissante sur l'intervalle ]-∞;0[.", reponse: true, justification: "Vrai : sur cette branche aussi, 1/x diminue quand x augmente." },
    { enonce: "Quand x tend vers -∞, 1/x tend vers -∞.", reponse: false, justification: "Faux : 1/x tend au contraire vers 0, par valeurs négatives, quand x tend vers -∞." },
    { enonce: "Quand x tend vers -∞, 1/x tend vers 0 par valeurs négatives.", reponse: true, justification: "Vrai : plus x est grand en valeur absolue, plus 1/x se rapproche de 0 tout en restant négatif." },
    { enonce: "Pour tout réel x non nul, 1/(1/x)=x : la fonction inverse est sa propre réciproque.", reponse: true, justification: "Vrai : appliquer deux fois la fonction inverse redonne le nombre de départ." },
    { enonce: "La fonction inverse est strictement croissante sur l'intervalle ]-∞;0[.", reponse: false, justification: "Faux : elle y est au contraire strictement décroissante, tout comme sur ]0;+∞[." },
    { enonce: "Pour x=10, on a 1/x=0,1 : plus x devient grand, plus 1/x se rapproche de 0.", reponse: true, justification: "Calcul direct, illustrant le comportement asymptotique." },
    { enonce: "Plus x se rapproche de 0 par valeurs positives, plus 1/x se rapproche lui aussi de 0.", reponse: false, justification: "Faux : c'est l'inverse — 1/x tend vers +∞ quand x se rapproche de 0 par valeurs positives." },
    { enonce: "Le graphe de la fonction inverse est une hyperbole formée de deux branches symétriques par rapport à l'origine du repère.", reponse: true, justification: "Vocabulaire standard pour décrire l'allure de cette courbe." },
    { enonce: "Les deux branches de l'hyperbole de la fonction inverse sont symétriques par rapport à l'axe des ordonnées.", reponse: false, justification: "Faux : elles sont symétriques par rapport à l'origine du repère (imparité), pas par rapport à l'axe des ordonnées (qui correspondrait à une fonction paire)." },
    { enonce: "1/0,5=2.", reponse: true, justification: "Calcul direct : 0,5=1/2, donc son inverse vaut 2." },
    { enonce: "1/(-0,25)=0,25.", reponse: false, justification: "Faux : 1/(-0,25)=-4, pas 0,25." },
    { enonce: "À mesure que x augmente sur l'intervalle ]0;+∞[, la courbe de la fonction inverse se rapproche de l'axe des abscisses sans jamais le toucher.", reponse: true, justification: "Comportement asymptotique classique au voisinage de l'asymptote horizontale y=0." },
    { enonce: "La fonction inverse admet une infinité de zéros, tous compris entre -1 et 1.", reponse: false, justification: "Faux : la fonction inverse n'admet aucun zéro — 1/x n'est jamais égal à 0, quel que soit x." },
    { enonce: "L'expression 5/(x+3) n'est pas définie lorsque x=-3.", reponse: true, justification: "Vrai : x=-3 annule le dénominateur x+3." },
    { enonce: "L'expression 5/(x+3) n'est pas définie lorsque x=3.", reponse: false, justification: "Faux : c'est x=-3 qui annule le dénominateur, pas x=3 (qui donne au contraire 5/6, une valeur bien définie)." },
  ],
  valeurAbsolue: [
    { enonce: "|x|=x lorsque x≥0.", reponse: true, justification: "Définition de la valeur absolue pour un nombre positif ou nul." },
    { enonce: "|x|=-x lorsque x<0.", reponse: true, justification: "Définition de la valeur absolue pour un nombre négatif (on prend son opposé, qui est alors positif)." },
    { enonce: "|-5|=5.", reponse: true, justification: "Calcul direct." },
    { enonce: "|-5|=-5.", reponse: false, justification: "Faux : la valeur absolue est toujours positive ou nulle, |-5|=5 et non -5." },
    { enonce: "La fonction valeur absolue est définie sur ℝ tout entier.", reponse: true, justification: "Aucune valeur de x n'est exclue." },
    { enonce: "L'image de la fonction valeur absolue contient des valeurs négatives.", reponse: false, justification: "Faux : |x|≥0 pour tout réel x, l'image est [0;+∞[." },
    { enonce: "Pour deux réels a et b, |a-b| représente la distance entre a et b sur une droite graduée.", reponse: true, justification: "C'est l'interprétation géométrique standard de la valeur absolue d'une différence." },
    { enonce: "La fonction valeur absolue est une fonction impaire.", reponse: false, justification: "Faux, elle est paire : |-x|=|x|, et non -|x|." },
    { enonce: "Le graphe de la fonction valeur absolue a la forme d'un U arrondi, comme celui de la fonction carrée.", reponse: false, justification: "Faux : c'est un V avec un point anguleux (pas arrondi) à l'origine, très différent de la parabole lisse de la fonction carrée." },
    { enonce: "La fonction valeur absolue est strictement décroissante sur ]-∞;0] et strictement croissante sur [0;+∞[.", reponse: true, justification: "C'est exactement la forme en V de sa courbe." },
    { enonce: "La fonction valeur absolue est strictement croissante sur ℝ tout entier.", reponse: false, justification: "Faux : elle décroît d'abord sur ]-∞;0], puis croît seulement sur [0;+∞[." },
    { enonce: "La fonction valeur absolue admet un minimum global qui vaut 0, atteint uniquement en x=0.", reponse: true, justification: "|x|=0 si et seulement si x=0." },
    { enonce: "La fonction valeur absolue admet un maximum global.", reponse: false, justification: "Faux : elle n'est pas majorée, |x| peut être aussi grand que l'on veut." },
    { enonce: "|0|=0 : la fonction valeur absolue admet un unique zéro, en x=0.", reponse: true, justification: "C'est le seul point où |x| s'annule." },
    { enonce: "La fonction valeur absolue admet une asymptote verticale.", reponse: false, justification: "Faux : elle est définie et continue sur ℝ tout entier, sans aucune asymptote." },
    { enonce: "|-3|=|3|=3.", reponse: true, justification: "Calcul direct." },
    { enonce: "Si x<0, alors |x|=x.", reponse: false, justification: "Faux : si x<0, |x|=-x (l'opposé de x, qui est alors positif), pas x lui-même." },
    { enonce: "La courbe de la fonction valeur absolue est symétrique par rapport à l'axe des ordonnées.", reponse: true, justification: "Conséquence directe de sa parité." },
    { enonce: "Il existe des valeurs de x pour lesquelles la fonction valeur absolue n'est pas définie.", reponse: false, justification: "Faux : elle est définie pour tout réel x, sans aucune exception." },
    { enonce: "|x|≥0 pour tout réel x, avec égalité si et seulement si x=0.", reponse: true, justification: "Propriété fondamentale de la valeur absolue." },
    { enonce: "|3-7|=4.", reponse: true, justification: "Calcul direct : |-4|=4." },
    { enonce: "|3-7|=-4.", reponse: false, justification: "Faux : une valeur absolue n'est jamais négative, |3-7|=|-4|=4, pas -4." },
    { enonce: "Pour deux réels a et b, |a-b|=|b-a|.", reponse: true, justification: "Vrai : la distance entre deux nombres est la même dans les deux sens." },
    { enonce: "Pour deux réels a et b, |a-b|=|a|-|b| en général.", reponse: false, justification: "Faux : ce n'est pas une identité générale — par exemple |1-5|=4 alors que |1|-|5|=-4." },
    { enonce: "|x-2|=0 si et seulement si x=2.", reponse: true, justification: "Vrai : une valeur absolue s'annule uniquement quand son contenu est nul." },
    { enonce: "L'équation |x|=3 admet une unique solution, x=3.", reponse: false, justification: "Faux : elle admet deux solutions, x=3 et x=-3, puisque |3|=|-3|=3." },
    { enonce: "L'équation |x|=3 admet deux solutions : x=3 et x=-3.", reponse: true, justification: "Vrai, comme vu ci-dessus." },
    { enonce: "L'équation |x|=-2 admet une solution.", reponse: false, justification: "Faux : une valeur absolue n'est jamais négative, cette équation n'a donc aucune solution." },
    { enonce: "Pour tout réel x, |x|²=x².", reponse: true, justification: "Vrai : élever au carré efface le signe dans les deux cas, le résultat est identique." },
    { enonce: "Pour tout réel x, |x|³=x³.", reponse: false, justification: "Faux : par exemple pour x=-2, |x|³=8 alors que x³=-8 — le cube, contrairement au carré, ne détruit pas le signe." },
    { enonce: "Le point anguleux de la courbe de la fonction valeur absolue se situe à l'origine du repère, en (0;0).", reponse: true, justification: "Vrai : c'est exactement là que la courbe change brusquement de direction." },
    { enonce: "La courbe de la fonction valeur absolue a son point anguleux au point (0;1).", reponse: false, justification: "Faux : le point anguleux se situe en (0;0), pas en (0;1)." },
    { enonce: "|-8|>|-3|.", reponse: true, justification: "Calcul direct : 8>3." },
    { enonce: "Si a<b, alors |a|<|b| pour tous réels a et b.", reponse: false, justification: "Faux : par exemple a=-5 et b=1 vérifient a<b, mais |a|=5>|b|=1 — la valeur absolue ne conserve pas l'ordre." },
    { enonce: "|x+5| représente la distance entre x et -5 sur une droite graduée.", reponse: true, justification: "Vrai, car |x+5|=|x-(-5)|, la distance entre x et -5." },
  ],
  transformations: [
    { enonce: "Dans la formule générale des transformations, TH est toujours soustrait à x : c'est une translation horizontale pure.", reponse: true, justification: "Convention utilisée systématiquement sur cette plateforme." },
    { enonce: "TV est toujours ajouté en tout dernier dans la formule : c'est une translation verticale pure.", reponse: true, justification: "TV s'ajoute après toutes les autres transformations." },
    { enonce: "Le point caractéristique de la courbe (sommet, coin, pôle ou borne de domaine selon la famille) se situe toujours en x=TH, quels que soient les autres paramètres.", reponse: true, justification: "C'est précisément l'objectif de l'ordre choisi pour la formule : isoler l'effet de TH." },
    { enonce: "Le point caractéristique de la courbe dépend à la fois de TH et de CH/EH.", reponse: false, justification: "Faux : grâce à l'ordre des transformations utilisé sur cette plateforme, ce point ne dépend que de TH, jamais de CH ni de EH." },
    { enonce: "SOX et SOY sont chacun égaux à -1 ou à 1, et peuvent varier indépendamment l'un de l'autre.", reponse: true, justification: "Deux réflexions indépendantes, chacune à 2 valeurs possibles." },
    { enonce: "CH signifie « compression horizontale » et EH signifie « compression verticale ».", reponse: false, justification: "Faux : CH signifie bien compression horizontale, mais EH signifie étirement horizontal — la compression verticale, elle, se note CV." },
    { enonce: "CV signifie « compression verticale » et EV signifie « étirement vertical ».", reponse: true, justification: "Nommage cohérent et symétrique avec CH/EH." },
    { enonce: "Dans la forme canonique f(x)=a(x-p)²+q de la fonction carrée, le sommet de la parabole est le point (q;p).", reponse: false, justification: "Faux : les coordonnées sont inversées — le sommet est le point (p;q), pas (q;p)." },
    { enonce: "TH et TV sont toujours des entiers strictement positifs sur cette plateforme.", reponse: false, justification: "Faux : TH et TV sont des entiers signés (négatifs, nuls ou positifs), contrairement à CH/EH/EV/CV qui sont, eux, toujours strictement positifs." },
    { enonce: "Pour la famille des fonctions inverses, l'asymptote verticale de la courbe transformée se situe en x=TH.", reponse: true, justification: "Le pôle de l'hyperbole, comme tout point caractéristique, se translate en x=TH." },
    { enonce: "Pour la famille des fonctions inverses, l'asymptote horizontale de la courbe transformée se situe en y=TV.", reponse: true, justification: "TV s'ajoutant en dernier, il fixe la nouvelle valeur vers laquelle la courbe tend." },
    { enonce: "Pour la famille des fonctions racine carrée, la borne du domaine de définition ne dépend jamais de TH.", reponse: false, justification: "Faux : la borne du domaine se translate elle aussi exactement en x=TH, comme le point caractéristique de toutes les autres familles." },
    { enonce: "La valeur par défaut de TH et de TV, en l'absence de translation, est 0.", reponse: true, justification: "Une translation nulle laisse la courbe inchangée." },
    { enonce: "La valeur par défaut de CH, EH, EV et CV, en l'absence de mise à l'échelle, est 0.", reponse: false, justification: "Faux : leur valeur par défaut est 1 (facteur neutre de mise à l'échelle) — une valeur 0 annulerait complètement la fonction." },
    { enonce: "Une translation horizontale déplace la courbe vers la droite ou vers la gauche, sans changer sa forme.", reponse: true, justification: "Propriété générale de toute translation horizontale." },
    { enonce: "Une translation verticale déplace la courbe vers le haut ou vers le bas, sans changer sa forme.", reponse: true, justification: "Propriété générale de toute translation verticale." },
    { enonce: "SOX et SOY produisent exactement le même effet géométrique sur la courbe.", reponse: false, justification: "Faux : SOX réfléchit le résultat global (verticalement), tandis que SOY réfléchit à l'intérieur, avant l'application de la fonction de référence — deux effets géométriques distincts." },
    { enonce: "Une réflexion (symétrie) laisse toujours inchangé le sens de variation d'une fonction.", reponse: false, justification: "Faux : une réflexion inverse au contraire le sens de variation sur l'intervalle concerné (une portion croissante devient décroissante, et inversement)." },
    { enonce: "Sur cette plateforme, CH, EH, EV et CV peuvent être négatifs.", reponse: false, justification: "Faux : ce sont des facteurs d'échelle, toujours des entiers strictement positifs — le signe est porté séparément par SOX et SOY." },
    { enonce: "Combiner plusieurs transformations (translation, mise à l'échelle, réflexion) permet de déplacer et déformer la courbe d'une fonction de référence tout en conservant son allure générale (V, parabole, hyperbole, etc.).", reponse: true, justification: "C'est le principe même des transformations de fonctions de référence." },
    { enonce: "Si CH=1 et EH=4, la courbe subit une compression horizontale.", reponse: false, justification: "Faux : avec CH/EH=1/4<1, c'est au contraire un étirement horizontal — la compression suppose CH/EH>1." },
    { enonce: "Si CH=4 et EH=1, la courbe subit une compression horizontale.", reponse: true, justification: "Vrai : CH/EH=4>1, l'argument (x-TH) est multiplié par un facteur supérieur à 1, ce qui resserre la courbe horizontalement." },
    { enonce: "Si EV=3 et CV=1, la courbe subit un étirement vertical.", reponse: true, justification: "Vrai : EV/CV=3>1, le résultat de g(...) est multiplié par un facteur supérieur à 1, ce qui étire la courbe verticalement." },
    { enonce: "Si EV=1 et CV=5, la courbe subit un étirement vertical.", reponse: false, justification: "Faux : EV/CV=1/5<1, c'est au contraire une compression verticale." },
    { enonce: "Le facteur qui multiplie g(...) tout entier dans la formule est SOX·(EV/CV) : il combine la mise à l'échelle verticale et la réflexion SOX.", reponse: true, justification: "Conforme à la formule unifiée f(x)=SOX·(EV/CV)·g(SOY·(CH/EH)·(x-TH))+TV." },
    { enonce: "Le facteur qui multiplie (x-TH) à l'intérieur de g est SOX·(CH/EH).", reponse: false, justification: "Faux : c'est SOY·(CH/EH) qui multiplie (x-TH) à l'intérieur de g — SOX intervient à l'extérieur, avec EV/CV." },
    { enonce: "Le facteur qui multiplie (x-TH) à l'intérieur de g est SOY·(CH/EH).", reponse: true, justification: "Conforme à la formule unifiée de la plateforme." },
    { enonce: "TH représente une translation verticale et TV une translation horizontale.", reponse: false, justification: "Faux : c'est l'inverse — TH est la translation horizontale, TV la translation verticale." },
    { enonce: "Si TH=0, le point caractéristique de la courbe de la fonction transformée reste sur l'axe des ordonnées (abscisse nulle).", reponse: true, justification: "Vrai : le point caractéristique se situe toujours en x=TH, donc en x=0 si TH=0." },
    { enonce: "Si TH=5, le point caractéristique de la courbe se situe en x=-5.", reponse: false, justification: "Faux : le point caractéristique se situe en x=TH, donc en x=5, pas en x=-5." },
    { enonce: "Le point caractéristique de la courbe ne dépend jamais de SOY, quelle que soit sa valeur.", reponse: true, justification: "Vrai : SOY est un facteur multiplicatif non nul à l'intérieur de g, il ne change jamais l'endroit où (x-TH) s'annule." },
    { enonce: "Le point caractéristique de la courbe dépend de EV et de CV, en plus de TH.", reponse: false, justification: "Faux : grâce à l'ordre des transformations utilisé sur cette plateforme, ce point ne dépend que de TH, jamais de EV ni de CV." },
    { enonce: "Pour la famille valeur absolue, le point anguleux de la courbe transformée se situe en x=TH, comme le point caractéristique de toutes les autres familles.", reponse: true, justification: "Vrai : le coin de la courbe en V se translate exactement comme le sommet, le pôle ou la borne de domaine des autres familles." },
    { enonce: "Pour la famille inverse, avec TH=2 et TV=-3, l'asymptote verticale de la courbe transformée est x=2 et l'asymptote horizontale est y=-3.", reponse: true, justification: "Application directe des règles générales : asymptote verticale en x=TH, asymptote horizontale en y=TV." },
    { enonce: "Pour la famille racine carrée, avec TH=-4 et SOY=1 (aucune réflexion), le domaine de définition de la fonction transformée est ]-∞;-4].", reponse: false, justification: "Faux : le domaine est [-4;+∞[, pas ]-∞;-4] — la borne du domaine se translate en x=TH, mais reste orientée vers +∞ tant qu'il n'y a pas de réflexion (SOY=1)." },
  ],
};
