/**
 * Couche A — banque de questions vrai/faux pour "Géométrie analytique plane" (gen65). 13 thèmes
 * (un par générateur, gen42-54), 35 affirmations chacune (18 vraies, 17 fausses) — mêmes conventions
 * exactes que `core/droite.types.ts`/`core/equationCercle*.types.ts`/`core/equationParabole*.types.ts`
 * (formes de droite, signe de p, k identique pour un cercle, etc.), jamais réinventées ici.
 */
import type { QuestionVraiFaux, VarianteQuizGeometrieAnalytique } from "../../core/quizGeometrieAnalytique.types";

const EQUATION_DROITE: QuestionVraiFaux[] = [
  { enonce: "La forme implicite d'une équation de droite s'écrit toujours ax+by+c=0.", reponse: true, justification: "C'est la définition de la forme implicite — toujours calculable, quelle que soit la droite." },
  { enonce: "La forme paramétrique x=x0+ta, y=y0+tb est toujours possible, quelle que soit la droite.", reponse: true, justification: "Un point et un vecteur directeur existent toujours, donc la forme paramétrique aussi." },
  { enonce: "Une droite verticale n'a pas de forme explicite y=mx+p, car sa pente n'est pas définie.", reponse: true, justification: "Une droite verticale a un vecteur directeur (0;b) : la pente Δy/Δx diviserait par 0." },
  { enonce: "Une droite horizontale n'a pas de forme explicite x=ny+q.", reponse: true, justification: "Une droite horizontale a un vecteur directeur (a;0) : x=ny+q diviserait par 0." },
  { enonce: "Le vecteur directeur d'une droite n'est jamais unique : tout multiple non nul du vecteur directeur convient aussi.", reponse: true, justification: "Colinéaire et non nul suffit — la direction est ce qui compte, pas la norme." },
  { enonce: "La droite passant par A(1;2) et B(3;6) a pour équation y=2x.", reponse: true, justification: "Pente m=(6-2)/(3-1)=2 ; en A(1;2) : 2=2×1+p donne p=0, donc y=2x." },
  { enonce: "Le point (0;4) et le vecteur directeur (1;-2) donnent l'équation implicite 2x+y-4=0.", reponse: true, justification: "x=t, y=4-2t → t=x → y=4-2x → 2x+y-4=0." },
  { enonce: "Une droite passant par un point avec un angle de 45° par rapport à Ox a une pente m=1.", reponse: true, justification: "m=tan(45°)=1." },
  { enonce: "Le point (2;3) et la pente m=-1 donnent l'équation y=-x+5.", reponse: true, justification: "y-3=-1(x-2) → y=-x+2+3=-x+5." },
  { enonce: "Pour la droite d'équation 3x+2y-6=0, le vecteur (2;-3) est un vecteur directeur valide.", reponse: true, justification: "Le vecteur normal est (3;2) ; (2;-3) lui est perpendiculaire (3×2+2×(-3)=0), donc directeur valide." },
  { enonce: "La forme explicite y=mx+p existe pour toute droite, y compris les droites verticales.", reponse: false, justification: "Impossible pour une droite verticale, dont la pente n'est pas définie." },
  { enonce: "La droite passant par A(1;2) et B(3;6) a pour vecteur directeur (1;-2).", reponse: false, justification: "Le vecteur AB=(3-1;6-2)=(2;4), colinéaire à (1;2), jamais à (1;-2)." },
  { enonce: "Pour la droite d'équation 3x+2y-6=0, le vecteur (3;2) est un vecteur directeur valide.", reponse: false, justification: "(3;2) est le vecteur NORMAL à cette droite, pas un vecteur directeur." },
  { enonce: "Le point (1;1) et le vecteur directeur (0;3) donnent une droite horizontale.", reponse: false, justification: "Un vecteur directeur (0;3) est vertical (Δx=0) : la droite obtenue est verticale (x=1)." },
  { enonce: "Le point (0;4) et le vecteur directeur (1;-2) donnent l'équation implicite y=2x+4.", reponse: false, justification: "La bonne équation est y=-2x+4 (pente négative, car le vecteur descend)." },
  { enonce: "Le vecteur directeur de la droite d'équation y=3x-1 est (3;1).", reponse: false, justification: "Pour y=mx+p, un vecteur directeur est (1;m), donc ici (1;3), jamais (3;1)." },
  { enonce: "Une droite formant un angle de 60° avec l'axe Ox a une pente rationnelle.", reponse: false, justification: "tan(60°)=√3, un nombre irrationnel." },
  { enonce: "Le point (2;3) et la pente m=-1 donnent l'équation y=-x+1.", reponse: false, justification: "Le calcul correct donne y=-x+5, pas y=-x+1." },
  { enonce: "À partir de deux points distincts, il n'existe qu'une seule forme d'équation possible pour la droite qu'ils déterminent.", reponse: false, justification: "Implicite et paramétrique sont toujours possibles, et souvent une des deux formes explicites aussi." },
  { enonce: "La forme implicite d'une équation de droite ne peut pas s'écrire pour une droite verticale.", reponse: false, justification: "Une droite verticale x=k s'écrit très bien x-k=0, une forme implicite valide (b=0)." },
  { enonce: "La droite passant par A(2;1) et B(5;7) a pour équation y=2x-3.", reponse: true, justification: "m=(7-1)/(5-2)=2 ; en A(2;1) : 1=2×2+p donne p=-3, donc y=2x-3." },
  { enonce: "Le point (-1;3) et le vecteur directeur (2;5) donnent l'équation implicite 5x-2y+11=0.", reponse: true, justification: "x=-1+2t, y=3+5t → t=(x+1)/2 → y=3+5(x+1)/2=2,5x+5,5, soit 5x-2y+11=0." },
  { enonce: "La droite d'équation implicite 5x-2y+11=0 admet (2;5) comme vecteur directeur.", reponse: true, justification: "Le vecteur normal est (5;-2) ; (2;5) lui est perpendiculaire (5×2-2×5=0), donc directeur valide." },
  { enonce: "Le vecteur (-2;-4) est aussi un vecteur directeur valide de la droite passant par C(2;-1) et D(6;7).", reponse: true, justification: "CD=(4;8) ; (-2;-4)=-0,5×(4;8), donc colinéaire à CD." },
  { enonce: "La droite d'équation x=5 (verticale) admet (0;1) comme vecteur directeur.", reponse: true, justification: "Un vecteur directeur d'une droite verticale a toujours la forme (0;b), et (0;1) convient." },
  { enonce: "La droite d'équation y=-2 (horizontale) admet (1;0) comme vecteur directeur.", reponse: true, justification: "Un vecteur directeur d'une droite horizontale a toujours la forme (a;0), et (1;0) convient." },
  { enonce: "Le point (3;-2) et la pente m=2/3 donnent l'équation explicite y=(2/3)x-4.", reponse: true, justification: "y-(-2)=(2/3)(x-3) → y=(2/3)x-2-2=(2/3)x-4." },
  { enonce: "Une droite dont l'équation implicite se réduit à by+c=0 (a=0) est une droite horizontale.", reponse: true, justification: "by+c=0 équivaut à y=-c/b, une équation où y est constant : c'est une droite horizontale." },
  { enonce: "La droite passant par A(2;1) et B(5;7) a pour équation y=2x+3.", reponse: false, justification: "L'ordonnée à l'origine correcte est p=-3, pas +3 (calcul : 1=2×2+p)." },
  { enonce: "Le point (-1;3) et le vecteur directeur (2;5) donnent l'équation implicite 3x-2y+3=0.", reponse: false, justification: "Ce point ne vérifie même pas cette équation (3×(-1)-2×3+3=-6≠0) ; la bonne équation est 5x-2y+11=0." },
  { enonce: "La droite d'équation implicite 5x-2y+11=0 admet (5;-2) comme vecteur directeur.", reponse: false, justification: "(5;-2) est le vecteur NORMAL de cette droite, pas un vecteur directeur." },
  { enonce: "Le vecteur (4;1) est un vecteur directeur valide de la droite passant par C(2;-1) et D(6;7).", reponse: false, justification: "CD=(4;8) ; (4;1) n'est pas colinéaire à (4;8) (4×8≠1×4)." },
  { enonce: "La droite d'équation x=5 (verticale) admet (1;0) comme vecteur directeur.", reponse: false, justification: "(1;0) est un vecteur horizontal : il ne peut pas diriger une droite verticale." },
  { enonce: "La droite d'équation y=-2 (horizontale) admet (0;1) comme vecteur directeur.", reponse: false, justification: "(0;1) est un vecteur vertical : il ne peut pas diriger une droite horizontale." },
  { enonce: "Le point (3;-2) et la pente m=2/3 donnent l'équation explicite y=(2/3)x-2.", reponse: false, justification: "Le calcul correct donne y=(2/3)x-4, pas y=(2/3)x-2." },
];

const LECTURE_GRAPHIQUE_DROITE: QuestionVraiFaux[] = [
  { enonce: "Pour lire l'équation d'une droite sur un graphe, il suffit de repérer 2 points à coordonnées entières situés sur la droite.", reponse: true, justification: "2 points suffisent à déterminer entièrement une droite." },
  { enonce: "Si une droite passe par les points entiers (0;1) et (2;5) lus sur le graphe, son équation cartésienne est y=2x+1.", reponse: true, justification: "Pente=(5-1)/(2-0)=2 ; en (0;1), p=1, donc y=2x+1." },
  { enonce: "Le vecteur directeur d'une droite lue sur un graphe peut se lire directement en comptant les carreaux entre deux points entiers de la droite.", reponse: true, justification: "Les composantes du vecteur sont les écarts de coordonnées entre les deux points, lisibles sur la grille." },
  { enonce: "Une droite passant par (1;0) et (1;4) sur le graphe est une droite verticale d'équation x=1.", reponse: true, justification: "Même abscisse pour les deux points → droite verticale x=1." },
  { enonce: "La forme paramétrique d'une droite lue sur un graphe s'écrit x=x0+ta, y=y0+tb à partir d'un point et du vecteur directeur repérés.", reponse: true, justification: "C'est la définition même de la forme paramétrique." },
  { enonce: "Une droite passant par (-2;3) et (2;-1) sur le graphe a une pente m=-1.", reponse: true, justification: "m=(-1-3)/(2-(-2))=-4/4=-1." },
  { enonce: "Le vecteur directeur d'une droite passant par (0;0) et (3;2) sur le graphe est (3;2).", reponse: true, justification: "Le vecteur va du premier point au second : (3-0;2-0)=(3;2)." },
  { enonce: "La droite passant par (2;1) et (4;1) sur le graphe est horizontale, d'équation y=1.", reponse: true, justification: "Même ordonnée pour les deux points → droite horizontale y=1." },
  { enonce: "Pour deux points entiers donnés sur le graphe, l'équation implicite ax+by+c=0 de la droite qu'ils déterminent est toujours calculable.", reponse: true, justification: "La forme implicite existe toujours, quels que soient les deux points distincts." },
  { enonce: "Une droite passant par (0;-2) avec un vecteur directeur (1;3) lu sur le graphe a pour équation y=3x-2.", reponse: true, justification: "Pente=3/1=3 ; en (0;-2), p=-2, donc y=3x-2." },
  { enonce: "Pour lire l'équation d'une droite sur un graphe, un seul point suffit.", reponse: false, justification: "Un seul point ne détermine pas une direction : il faut un second point ou un vecteur directeur." },
  { enonce: "Si une droite passe par les points entiers (0;1) et (2;5) lus sur le graphe, son équation cartésienne est y=2x+2.", reponse: false, justification: "L'ordonnée à l'origine correcte est 1 (le point (0;1) est déjà sur l'axe Oy), pas 2." },
  { enonce: "Une droite passant par (1;0) et (1;4) sur le graphe est horizontale.", reponse: false, justification: "Même abscisse pour les deux points : la droite est verticale, pas horizontale." },
  { enonce: "Une droite passant par (-2;3) et (2;-1) sur le graphe a une pente m=1.", reponse: false, justification: "Le calcul correct donne m=-1, pas m=1." },
  { enonce: "Le vecteur directeur d'une droite passant par (0;0) et (3;2) sur le graphe est (2;3).", reponse: false, justification: "Le vecteur correct est (3;2) : abscisses en premier, jamais inversé." },
  { enonce: "La droite passant par (2;1) et (4;1) sur le graphe est verticale.", reponse: false, justification: "Même ordonnée pour les deux points : la droite est horizontale, pas verticale." },
  { enonce: "Une droite passant par (0;-2) avec un vecteur directeur (1;3) lu sur le graphe a pour équation y=3x+2.", reponse: false, justification: "L'ordonnée à l'origine correcte est -2 (donnée par le point), pas +2." },
  { enonce: "Sur un graphe, la pente d'une droite se lit toujours directement sans avoir besoin de deux points.", reponse: false, justification: "Il faut toujours au moins deux points (ou un point et un vecteur directeur) pour calculer une pente." },
  { enonce: "Une droite passant par deux points entiers distincts sur le graphe n'a pas toujours une forme paramétrique.", reponse: false, justification: "La forme paramétrique existe toujours, dès qu'on connaît un point et un vecteur directeur." },
  { enonce: "Le vecteur directeur lu sur un graphe doit toujours être réduit à sa forme la plus simple pour que l'équation soit correcte.", reponse: false, justification: "N'importe quel vecteur directeur non nul, réduit ou non, donne une équation correcte." },
  { enonce: "Une droite passant par (1;-3) et (4;3) lus sur le graphe a une pente m=2.", reponse: true, justification: "m=(3-(-3))/(4-1)=6/3=2." },
  { enonce: "Une droite passant par (1;-3) et (4;3) lus sur le graphe a pour équation y=2x-5.", reponse: true, justification: "Pente=2 ; en (1;-3) : -3=2×1+p donne p=-5, donc y=2x-5." },
  { enonce: "Le vecteur directeur d'une droite passant par (-3;-1) et (2;4) lus sur le graphe est (5;5).", reponse: true, justification: "(2-(-3);4-(-1))=(5;5)." },
  { enonce: "Une droite passant par (0;5) et (0;-2) sur le graphe est verticale, d'équation x=0.", reponse: true, justification: "Même abscisse (0) pour les deux points → droite verticale x=0." },
  { enonce: "La droite passant par (-1;4) et (3;4) sur le graphe est horizontale, d'équation y=4.", reponse: true, justification: "Même ordonnée (4) pour les deux points → droite horizontale y=4." },
  { enonce: "Le vecteur directeur d'une droite passant par (2;-3) et (2;5) lu sur le graphe est de la forme (0;b), vertical.", reponse: true, justification: "Même abscisse (2) pour les deux points : le vecteur (0;5-(-3))=(0;8) est bien vertical." },
  { enonce: "Une droite passant par (-4;2) et (0;0) sur le graphe a pour équation y=-x/2.", reponse: true, justification: "m=(0-2)/(0-(-4))=-1/2 ; en (0;0), p=0, donc y=-x/2." },
  { enonce: "Sur un graphe, si deux points lus sur une droite ont la même abscisse, cette droite est nécessairement verticale.", reponse: true, justification: "Même abscisse pour deux points distincts signifie que la droite ne varie qu'en y : elle est verticale." },
  { enonce: "Une droite passant par (1;-3) et (4;3) lus sur le graphe a une pente m=1/2.", reponse: false, justification: "Le calcul correct donne m=(3-(-3))/(4-1)=2, pas 1/2." },
  { enonce: "Une droite passant par (1;-3) et (4;3) lus sur le graphe a pour équation y=2x+5.", reponse: false, justification: "L'ordonnée à l'origine correcte est p=-5 (calcul : -3=2×1+p), pas +5." },
  { enonce: "Le vecteur directeur d'une droite passant par (-3;-1) et (2;4) lus sur le graphe est (5;-5).", reponse: false, justification: "Le vecteur correct est (5;5) (même signe pour Δx et Δy), pas (5;-5)." },
  { enonce: "Une droite passant par (0;5) et (0;-2) sur le graphe est horizontale.", reponse: false, justification: "Même abscisse pour les deux points : la droite est verticale, pas horizontale." },
  { enonce: "La droite passant par (-1;4) et (3;4) sur le graphe est verticale.", reponse: false, justification: "Même ordonnée pour les deux points : la droite est horizontale, pas verticale." },
  { enonce: "Une droite passant par (-4;2) et (0;0) sur le graphe a pour équation y=2x.", reponse: false, justification: "La pente correcte est -1/2 (calcul : m=(0-2)/(0-(-4))), pas 2." },
  { enonce: "Sur un graphe, si deux points lus sur une droite ont la même ordonnée, cette droite est nécessairement verticale.", reponse: false, justification: "Même ordonnée pour deux points signifie au contraire une droite HORIZONTALE, pas verticale." },
];

const CONSTRUCTION_DROITE: QuestionVraiFaux[] = [
  { enonce: "Pour tracer une droite depuis son équation, il suffit de trouver 2 points distincts qui lui appartiennent.", reponse: true, justification: "2 points distincts déterminent entièrement une droite." },
  { enonce: "La droite d'équation y=2x-1 passe par les points (0;-1) et (1;1).", reponse: true, justification: "En x=0 : y=-1. En x=1 : y=2-1=1. Les deux points vérifient l'équation." },
  { enonce: "La droite d'équation x=3 est une droite verticale, tous ses points ont pour abscisse 3.", reponse: true, justification: "C'est la définition même d'une droite verticale d'équation x=k." },
  { enonce: "La droite paramétrique x=1+2t, y=-1+t passe par le point (1;-1) pour t=0.", reponse: true, justification: "En t=0 : x=1, y=-1." },
  { enonce: "La droite paramétrique x=1+2t, y=-1+t passe par le point (3;0) pour t=1.", reponse: true, justification: "En t=1 : x=1+2=3, y=-1+1=0." },
  { enonce: "La droite d'équation implicite 2x-y+1=0 passe par le point (0;1).", reponse: true, justification: "2(0)-1+1=0. L'équation est vérifiée." },
  { enonce: "La droite d'équation implicite 2x-y+1=0 passe par le point (1;3).", reponse: true, justification: "2(1)-3+1=0. L'équation est vérifiée." },
  { enonce: "La droite d'équation x=2y+1 passe par le point (1;0).", reponse: true, justification: "1=2(0)+1=1. L'équation est vérifiée." },
  { enonce: "Deux points quelconques appartenant à une même droite suffisent toujours à la tracer entièrement.", reponse: true, justification: "Une droite est entièrement déterminée par deux de ses points distincts." },
  { enonce: "La droite d'équation y=-3 est une droite horizontale.", reponse: true, justification: "y est constant (=-3) quel que soit x : c'est une droite horizontale." },
  { enonce: "Pour tracer une droite depuis son équation, un seul point suffit.", reponse: false, justification: "Un seul point ne fixe pas de direction : il en faut au moins deux." },
  { enonce: "La droite d'équation y=2x-1 passe par les points (0;1) et (1;1).", reponse: false, justification: "En x=0, l'équation donne y=-1, pas y=1." },
  { enonce: "La droite d'équation x=3 est une droite horizontale.", reponse: false, justification: "x=3 est une droite verticale (abscisse constante), pas horizontale." },
  { enonce: "La droite paramétrique x=1+2t, y=-1+t passe par le point (1;-1) pour t=1.", reponse: false, justification: "En t=1, le point est (3;0), pas (1;-1) (obtenu pour t=0)." },
  { enonce: "La droite d'équation implicite 2x-y+1=0 passe par le point (0;0).", reponse: false, justification: "2(0)-0+1=1≠0 : le point n'appartient pas à la droite." },
  { enonce: "La droite d'équation x=2y+1 passe par le point (0;0).", reponse: false, justification: "0≠2(0)+1=1 : le point n'appartient pas à la droite." },
  { enonce: "La droite d'équation y=-3 est une droite verticale.", reponse: false, justification: "y=-3 est une droite horizontale (ordonnée constante), pas verticale." },
  { enonce: "Il est impossible de tracer une droite verticale à partir de son équation x=k.", reponse: false, justification: "Une droite verticale se trace très facilement : tous les points d'abscisse k." },
  { enonce: "La droite paramétrique x=1+2t, y=-1+t passe par le point (5;2) pour t=2.", reponse: false, justification: "En t=2 : x=5, y=1, pas y=2." },
  { enonce: "La droite d'équation 2x-y+1=0 a pour vecteur directeur (1;-2).", reponse: false, justification: "Le vecteur normal est (2;-1) ; un vecteur directeur valide est (1;2), pas (1;-2)." },
  { enonce: "La droite d'équation y=-3x+4 passe par les points (0;4) et (1;1).", reponse: true, justification: "En x=0 : y=4. En x=1 : y=-3+4=1. Les deux points vérifient l'équation." },
  { enonce: "La droite d'équation x=-2 est une droite verticale, tous ses points ont pour abscisse -2.", reponse: true, justification: "C'est la définition même d'une droite verticale d'équation x=k." },
  { enonce: "La droite paramétrique x=-2+3t, y=1-2t passe par le point (-2;1) pour t=0.", reponse: true, justification: "En t=0 : x=-2, y=1." },
  { enonce: "La droite paramétrique x=-2+3t, y=1-2t passe par le point (1;-1) pour t=1.", reponse: true, justification: "En t=1 : x=-2+3=1, y=1-2=-1." },
  { enonce: "La droite d'équation implicite 3x+y-2=0 passe par le point (1;-1).", reponse: true, justification: "3(1)+(-1)-2=0. L'équation est vérifiée." },
  { enonce: "La droite d'équation implicite 3x+y-2=0 passe par le point (0;2).", reponse: true, justification: "3(0)+2-2=0. L'équation est vérifiée." },
  { enonce: "La droite d'équation x=3y-2 passe par le point (1;1).", reponse: true, justification: "1=3(1)-2=1. L'équation est vérifiée." },
  { enonce: "La droite d'équation y=7 est une droite horizontale.", reponse: true, justification: "y est constant (=7) quel que soit x : c'est une droite horizontale." },
  { enonce: "La droite d'équation y=-3x+4 passe par les points (0;4) et (1;-1).", reponse: false, justification: "En x=1, l'équation donne y=1, pas y=-1." },
  { enonce: "La droite d'équation x=-2 est une droite horizontale.", reponse: false, justification: "x=-2 est une droite verticale (abscisse constante), pas horizontale." },
  { enonce: "La droite paramétrique x=-2+3t, y=1-2t passe par le point (-2;1) pour t=1.", reponse: false, justification: "En t=1, le point est (1;-1), pas (-2;1) (obtenu pour t=0)." },
  { enonce: "La droite paramétrique x=-2+3t, y=1-2t passe par le point (4;-4) pour t=2.", reponse: false, justification: "En t=2 : x=-2+6=4, y=1-4=-3, pas y=-4." },
  { enonce: "La droite d'équation implicite 3x+y-2=0 passe par le point (2;0).", reponse: false, justification: "3(2)+0-2=4≠0 : le point n'appartient pas à la droite." },
  { enonce: "La droite d'équation x=3y-2 passe par le point (0;1).", reponse: false, justification: "0≠3(1)-2=1 : le point n'appartient pas à la droite." },
  { enonce: "La droite d'équation y=7 est une droite verticale.", reponse: false, justification: "y=7 est une droite horizontale (ordonnée constante), pas verticale." },
];

const RELATIONS_DROITES: QuestionVraiFaux[] = [
  { enonce: "Deux droites sont parallèles si et seulement si leurs vecteurs directeurs sont colinéaires.", reponse: true, justification: "C'est la définition même du parallélisme entre deux droites." },
  { enonce: "Deux droites sont perpendiculaires si et seulement si le produit de leurs pentes vaut -1 (quand les deux pentes existent).", reponse: true, justification: "C'est la condition classique de perpendicularité entre deux droites non verticales." },
  { enonce: "Si une droite a pour pente m=2, la droite perpendiculaire a pour pente m'=-1/2.", reponse: true, justification: "m×m'=-1 → m'=-1/2." },
  { enonce: "Si une droite a pour pente m=3, toute droite parallèle a aussi pour pente m=3.", reponse: true, justification: "Des droites parallèles ont exactement la même pente." },
  { enonce: "Une droite verticale et une droite horizontale sont toujours perpendiculaires.", reponse: true, justification: "Leurs vecteurs directeurs (0;b) et (a;0) ont un produit scalaire nul." },
  { enonce: "Le vecteur directeur (2;3) et le vecteur directeur (4;6) sont colinéaires, donc les deux droites associées sont parallèles.", reponse: true, justification: "(4;6)=2×(2;3) : les deux vecteurs sont colinéaires." },
  { enonce: "Le vecteur directeur (1;2) et le vecteur directeur (-2;1) sont perpendiculaires (leur produit scalaire est nul).", reponse: true, justification: "1×(-2)+2×1=-2+2=0." },
  { enonce: "La droite parallèle à y=-x+4 passant par (0;0) a pour équation y=-x.", reponse: true, justification: "Même pente (-1), et p=0 car elle passe par l'origine." },
  { enonce: "La droite perpendiculaire à y=2x+1 passant par (0;3) a pour équation y=-0,5x+3.", reponse: true, justification: "Pente perpendiculaire=-1/2 ; en (0;3), p=3." },
  { enonce: "Deux droites parallèles distinctes n'ont aucun point commun.", reponse: true, justification: "C'est la définition même de deux droites parallèles non confondues." },
  { enonce: "Deux droites sont parallèles si et seulement si leurs vecteurs directeurs sont perpendiculaires.", reponse: false, justification: "Des vecteurs perpendiculaires correspondent à des droites perpendiculaires, pas parallèles." },
  { enonce: "Deux droites sont perpendiculaires si et seulement si leurs pentes sont égales.", reponse: false, justification: "Des pentes égales correspondent à des droites parallèles, pas perpendiculaires." },
  { enonce: "Si une droite a pour pente m=2, la droite perpendiculaire a pour pente m'=2.", reponse: false, justification: "m'=-1/2, pas 2 (m'=2 donnerait une droite parallèle, pas perpendiculaire)." },
  { enonce: "Le vecteur directeur (2;3) et le vecteur directeur (4;6) sont perpendiculaires.", reponse: false, justification: "Ils sont colinéaires (4;6)=2×(2;3), donc parallèles, pas perpendiculaires." },
  { enonce: "Le vecteur directeur (1;2) et le vecteur directeur (-2;1) sont colinéaires.", reponse: false, justification: "1×1-2×(-2)=1+4=5≠0 : ils ne sont pas colinéaires (ils sont perpendiculaires)." },
  { enonce: "La droite parallèle à y=-x+4 passant par (0;0) a pour équation y=x.", reponse: false, justification: "La pente doit rester -1 (parallélisme), pas devenir 1." },
  { enonce: "La droite perpendiculaire à y=2x+1 passant par (0;3) a pour équation y=2x+3.", reponse: false, justification: "Cette droite a la même pente que l'originale : elle est parallèle, pas perpendiculaire." },
  { enonce: "Deux droites verticales distinctes sont toujours perpendiculaires entre elles.", reponse: false, justification: "Deux droites verticales sont toujours parallèles entre elles, jamais perpendiculaires." },
  { enonce: "Deux droites parallèles distinctes ont toujours un unique point commun.", reponse: false, justification: "Des droites parallèles distinctes n'ont justement AUCUN point commun." },
  { enonce: "La perpendicularité entre deux vecteurs directeurs (u_x;u_y) et (v_x;v_y) se teste avec la formule u_x·v_x-u_y·v_y=0.", reponse: false, justification: "La bonne formule est u_x·v_x+u_y·v_y=0 (produit scalaire), avec un signe +, pas -." },
  { enonce: "Si une droite a pour pente m=-3, la droite perpendiculaire a pour pente m'=1/3.", reponse: true, justification: "m×m'=-1 → m'=-1/(-3)=1/3." },
  { enonce: "Le vecteur directeur (3;-2) et le vecteur directeur (2;3) sont perpendiculaires (leur produit scalaire est nul).", reponse: true, justification: "3×2+(-2)×3=6-6=0." },
  { enonce: "Le vecteur directeur (6;9) et le vecteur directeur (2;3) sont colinéaires, donc les droites associées sont parallèles.", reponse: true, justification: "(6;9)=3×(2;3) : les deux vecteurs sont colinéaires." },
  { enonce: "La droite parallèle à y=3x-2 passant par (1;5) a pour équation y=3x+2.", reponse: true, justification: "Même pente (3) ; en (1;5) : 5=3×1+p donne p=2." },
  { enonce: "La droite perpendiculaire à y=-2x+1 passant par (4;0) a pour équation y=0,5x-2.", reponse: true, justification: "Pente perpendiculaire=1/2 ; en (4;0) : 0=0,5×4+p donne p=-2." },
  { enonce: "Deux droites confondues ont nécessairement la même pente (quand elle est définie).", reponse: true, justification: "Deux droites confondues sont en réalité la même droite : leur pente est forcément identique." },
  { enonce: "Deux droites verticales distinctes sont toujours parallèles entre elles.", reponse: true, justification: "Leurs vecteurs directeurs (0;b) sont tous colinéaires entre eux : elles sont parallèles." },
  { enonce: "Le vecteur directeur (4;-1) et le vecteur directeur (1;4) sont perpendiculaires.", reponse: true, justification: "4×1+(-1)×4=4-4=0." },
  { enonce: "Si une droite a pour pente m=-3, la droite perpendiculaire a pour pente m'=3.", reponse: false, justification: "La bonne pente perpendiculaire est m'=1/3, pas 3 (oubli de l'inverse)." },
  { enonce: "Le vecteur directeur (3;-2) et le vecteur directeur (2;3) sont colinéaires.", reponse: false, justification: "3×3-(-2)×2=9+4=13≠0 : ils ne sont pas colinéaires (ils sont perpendiculaires)." },
  { enonce: "Le vecteur directeur (6;9) et le vecteur directeur (2;3) sont perpendiculaires.", reponse: false, justification: "6×2+9×3=12+27=39≠0 : ils ne sont pas perpendiculaires (ils sont colinéaires)." },
  { enonce: "La droite parallèle à y=3x-2 passant par (1;5) a pour équation y=3x-2.", reponse: false, justification: "Cette équation ne passe pas par (1;5) (elle donne y=1) ; la bonne ordonnée à l'origine est p=2." },
  { enonce: "La droite perpendiculaire à y=-2x+1 passant par (4;0) a pour équation y=-2x+8.", reponse: false, justification: "Cette droite a la même pente que l'originale (-2) : elle est parallèle, pas perpendiculaire." },
  { enonce: "Deux droites confondues peuvent avoir des pentes différentes.", reponse: false, justification: "Deux droites confondues sont la même droite : leur pente est nécessairement la même." },
  { enonce: "Deux droites verticales distinctes sont sécantes en un point unique.", reponse: false, justification: "Deux droites verticales distinctes sont toujours parallèles, elles ne se coupent jamais." },
];

const CARACTERISTIQUES_DROITE: QuestionVraiFaux[] = [
  { enonce: "La pente d'une droite d'équation y=mx+p est le coefficient m.", reponse: true, justification: "C'est la définition même de la forme explicite y=mx+p." },
  { enonce: "L'ordonnée à l'origine d'une droite d'équation y=mx+p est p.", reponse: true, justification: "p est la valeur de y quand x=0 : c'est l'ordonnée à l'origine." },
  { enonce: "Une droite verticale n'a pas de pente définie.", reponse: true, justification: "La pente Δy/Δx diviserait par 0 pour un déplacement purement vertical." },
  { enonce: "L'angle que fait une droite de pente m=1 avec l'axe Ox est 45°.", reponse: true, justification: "tan(45°)=1." },
  { enonce: "L'angle que fait une droite de pente m=0 avec l'axe Ox est 0°.", reponse: true, justification: "tan(0°)=0 : une droite horizontale ne fait aucun angle avec Ox." },
  { enonce: "Une droite verticale fait un angle de 90° avec l'axe Ox.", reponse: true, justification: "Une droite verticale est perpendiculaire à Ox." },
  { enonce: "La pente d'une droite se calcule par m=tan(angle), où angle est l'angle formé avec l'axe Ox.", reponse: true, justification: "C'est la relation trigonométrique reliant pente et angle d'inclinaison." },
  { enonce: "Pour la droite implicite 2x-y+3=0, la pente est m=2.", reponse: true, justification: "2x-y+3=0 → y=2x+3, donc m=2." },
  { enonce: "Pour la droite implicite 2x-y+3=0, l'ordonnée à l'origine est p=3.", reponse: true, justification: "y=2x+3, donc p=3." },
  { enonce: "Une droite verticale n'a pas d'ordonnée à l'origine, sauf si elle est confondue avec l'axe Oy.", reponse: true, justification: "Une droite x=k avec k≠0 ne croise jamais Oy ; seule x=0 (l'axe Oy lui-même) fait exception." },
  { enonce: "La pente d'une droite d'équation y=mx+p est le coefficient p.", reponse: false, justification: "p est l'ordonnée à l'origine, pas la pente : c'est m qui est la pente." },
  { enonce: "Une droite verticale a une pente définie, égale à 0.", reponse: false, justification: "Une droite verticale n'a justement AUCUNE pente définie (0 est la pente d'une horizontale)." },
  { enonce: "L'angle que fait une droite de pente m=1 avec l'axe Ox est 90°.", reponse: false, justification: "tan(45°)=1, pas tan(90°) (qui n'est même pas définie)." },
  { enonce: "L'angle que fait une droite de pente m=0 avec l'axe Ox est 90°.", reponse: false, justification: "Une pente nulle correspond à un angle de 0°, pas 90°." },
  { enonce: "Une droite verticale fait un angle de 0° avec l'axe Ox.", reponse: false, justification: "Une droite verticale fait un angle de 90° avec Ox, pas 0°." },
  { enonce: "Pour la droite implicite 2x-y+3=0, la pente est m=-2.", reponse: false, justification: "La pente correcte est m=2 (positif), pas -2." },
  { enonce: "Pour la droite implicite 2x-y+3=0, l'ordonnée à l'origine est p=-3.", reponse: false, justification: "L'ordonnée à l'origine correcte est p=3 (positif), pas -3." },
  { enonce: "L'angle d'une droite avec l'axe Oy est toujours égal à l'angle qu'elle fait avec l'axe Ox.", reponse: false, justification: "Les deux angles sont complémentaires en général (leur somme fait 90°), pas égaux." },
  { enonce: "Une droite horizontale n'a pas de pente définie.", reponse: false, justification: "Une droite horizontale a une pente parfaitement définie : m=0." },
  { enonce: "Toute droite verticale possède une ordonnée à l'origine, quelle que soit son abscisse.", reponse: false, justification: "Une droite verticale x=k avec k≠0 ne croise jamais l'axe Oy : elle n'a pas d'ordonnée à l'origine." },
  { enonce: "Pour la droite implicite 4x-2y+6=0, la pente est m=2.", reponse: true, justification: "4x-2y+6=0 → y=2x+3, donc m=2." },
  { enonce: "Pour la droite implicite 4x-2y+6=0, l'ordonnée à l'origine est p=3.", reponse: true, justification: "y=2x+3, donc p=3." },
  { enonce: "L'angle que fait une droite de pente m=√3 avec l'axe Ox est 60°.", reponse: true, justification: "tan(60°)=√3." },
  { enonce: "La pente d'une droite faisant un angle de 135° avec l'axe Ox est négative.", reponse: true, justification: "tan(135°)=-1, une valeur négative." },
  { enonce: "Pour la droite implicite -x+3y-6=0, la pente est m=1/3.", reponse: true, justification: "-x+3y-6=0 → y=x/3+2, donc m=1/3." },
  { enonce: "Pour la droite implicite -x+3y-6=0, l'ordonnée à l'origine est p=2.", reponse: true, justification: "y=x/3+2, donc p=2." },
  { enonce: "Le coefficient m dans y=mx+p peut être négatif, nul ou positif selon l'inclinaison de la droite.", reponse: true, justification: "m est négatif si la droite descend, nul si elle est horizontale, positif si elle monte." },
  { enonce: "Une droite de pente m=0 est une droite horizontale.", reponse: true, justification: "m=0 signifie que y ne varie jamais avec x : c'est une droite horizontale." },
  { enonce: "Pour la droite implicite 4x-2y+6=0, la pente est m=4.", reponse: false, justification: "La pente correcte est m=2 (calcul : y=2x+3), pas 4." },
  { enonce: "Pour la droite implicite 4x-2y+6=0, l'ordonnée à l'origine est p=6.", reponse: false, justification: "L'ordonnée à l'origine correcte est p=3 (calcul : y=2x+3), pas 6." },
  { enonce: "L'angle que fait une droite de pente m=√3 avec l'axe Ox est 30°.", reponse: false, justification: "tan(30°)=1/√3≠√3 ; l'angle correct est 60°." },
  { enonce: "La pente d'une droite faisant un angle de 135° avec l'axe Ox est positive.", reponse: false, justification: "tan(135°)=-1 : la pente est négative, pas positive." },
  { enonce: "Pour la droite implicite -x+3y-6=0, la pente est m=-1/3.", reponse: false, justification: "La pente correcte est m=1/3 (positive), pas -1/3." },
  { enonce: "Pour la droite implicite -x+3y-6=0, l'ordonnée à l'origine est p=-2.", reponse: false, justification: "L'ordonnée à l'origine correcte est p=2 (positive), pas -2." },
  { enonce: "Le coefficient p dans y=mx+p correspond à l'angle que fait la droite avec l'axe Ox.", reponse: false, justification: "p est l'ordonnée à l'origine, sans lien direct avec l'angle ; c'est m qui détermine l'angle." },
];

const DISTANCE_POINT_DROITE: QuestionVraiFaux[] = [
  { enonce: "La distance d'un point à une droite est la longueur du segment perpendiculaire reliant le point à la droite.", reponse: true, justification: "C'est la définition géométrique de la distance point-droite (le plus court chemin)." },
  { enonce: "Pour construire la perpendiculaire à une droite de pente m passant par un point donné, on utilise la pente -1/m.", reponse: true, justification: "C'est la condition de perpendicularité entre deux droites (m×m'=-1)." },
  { enonce: "Le pied de la perpendiculaire est le point d'intersection entre la droite donnée et sa perpendiculaire passant par le point.", reponse: true, justification: "C'est la définition même du pied de la perpendiculaire." },
  { enonce: "La distance entre deux droites parallèles est la même, quel que soit le point choisi sur l'une des deux droites.", reponse: true, justification: "C'est une propriété géométrique des droites parallèles : l'écartement est constant." },
  { enonce: "La distance entre un point de la droite elle-même et cette droite vaut toujours 0.", reponse: true, justification: "Un point de la droite est déjà sur la droite : la distance est nulle." },
  { enonce: "Si le pied de la perpendiculaire est Q(2;1) et le point donné est P(5;5), la distance PQ vaut 5 (triangle 3-4-5).", reponse: true, justification: "Δx=3, Δy=4, distance=√(9+16)=√25=5." },
  { enonce: "Pour trouver la distance entre deux droites parallèles, il suffit de choisir un point sur l'une et de calculer sa distance à l'autre.", reponse: true, justification: "Puisque l'écartement entre parallèles est constant, un seul point suffit." },
  { enonce: "Deux droites parallèles distinctes n'ont jamais de point commun, donc leur distance est strictement positive.", reponse: true, justification: "Aucun point commun signifie un écartement non nul entre les deux droites." },
  { enonce: "La perpendiculaire à une droite verticale est toujours une droite horizontale.", reponse: true, justification: "Une droite verticale et une droite horizontale ont des vecteurs directeurs orthogonaux." },
  { enonce: "La perpendiculaire à une droite d'équation y=3x+1 passant par un point donné a pour pente -1/3.", reponse: true, justification: "m×m'=-1 avec m=3 donne m'=-1/3." },
  { enonce: "La distance d'un point à une droite se mesure toujours le long d'une droite horizontale reliant le point à la droite.", reponse: false, justification: "Elle se mesure le long de la PERPENDICULAIRE à la droite, pas d'une horizontale." },
  { enonce: "Pour construire la perpendiculaire à une droite de pente m, on utilise la même pente m.", reponse: false, justification: "La même pente donnerait une droite parallèle, pas perpendiculaire ; il faut -1/m." },
  { enonce: "Le pied de la perpendiculaire est un point choisi librement sur la droite donnée, indépendant de la perpendiculaire tracée.", reponse: false, justification: "Le pied est déterminé : c'est l'intersection entre la droite donnée et la perpendiculaire, pas un choix libre." },
  { enonce: "La distance entre deux droites parallèles dépend du point choisi sur l'une des deux droites.", reponse: false, justification: "L'écartement entre deux parallèles est constant, quel que soit le point choisi." },
  { enonce: "La distance entre un point situé sur la droite et cette droite vaut toujours 1.", reponse: false, justification: "Elle vaut toujours 0, puisque le point appartient déjà à la droite." },
  { enonce: "Si le pied de la perpendiculaire est Q(2;1) et le point donné est P(5;5), la distance PQ vaut 7.", reponse: false, justification: "Le calcul correct (triangle 3-4-5) donne une distance de 5, pas 7." },
  { enonce: "La perpendiculaire à une droite verticale est toujours une autre droite verticale.", reponse: false, justification: "La perpendiculaire à une verticale est une HORIZONTALE, pas une autre verticale." },
  { enonce: "La perpendiculaire à une droite d'équation y=3x+1 passant par un point donné a pour pente 3.", reponse: false, justification: "Une pente de 3 donnerait une droite parallèle ; la perpendiculaire a pour pente -1/3." },
  { enonce: "Deux droites parallèles distinctes peuvent parfois se couper en un point.", reponse: false, justification: "Par définition, deux droites parallèles distinctes ne se coupent jamais." },
  { enonce: "La distance entre un point et une droite peut se mesurer le long de n'importe quel segment reliant le point à un point de la droite, pas seulement le segment perpendiculaire.", reponse: false, justification: "Seul le segment perpendiculaire donne la distance minimale, qui est LA distance point-droite." },
  { enonce: "Si le pied de la perpendiculaire est Q(1;2) et le point donné est P(4;-2), la distance PQ vaut 5.", reponse: true, justification: "Δx=3, Δy=-4, distance=√(9+16)=√25=5." },
  { enonce: "La perpendiculaire à une droite d'équation y=-4x+2 passant par un point donné a pour pente 1/4.", reponse: true, justification: "m×m'=-1 avec m=-4 donne m'=1/4." },
  { enonce: "Si une droite a pour pente m=2/3, sa perpendiculaire a pour pente -3/2.", reponse: true, justification: "(2/3)×(-3/2)=-1." },
  { enonce: "Le pied de la perpendiculaire abaissée d'un point P sur une droite d appartient toujours à la droite d.", reponse: true, justification: "C'est la définition même du pied de la perpendiculaire : le point d'intersection avec d." },
  { enonce: "La distance d'un point à une droite est toujours positive ou nulle (nulle seulement si le point est sur la droite).", reponse: true, justification: "Une distance est toujours ≥0, et elle vaut 0 exactement quand le point appartient à la droite." },
  { enonce: "Si P(0;0) et le pied de la perpendiculaire sur une droite d est Q(3;4), alors la distance de P à d vaut 5.", reponse: true, justification: "Δx=3, Δy=4, distance=√(9+16)=√25=5." },
  { enonce: "La perpendiculaire à une droite horizontale est toujours une droite verticale.", reponse: true, justification: "Une droite horizontale (vecteur (a;0)) et une droite verticale (vecteur (0;b)) ont des vecteurs orthogonaux." },
  { enonce: "Si un point appartient à une droite parallèle à une droite d mais distincte de d, sa distance à d est strictement positive.", reponse: true, justification: "Le point n'appartenant pas à d (parallèles distinctes), sa distance à d ne peut pas être nulle." },
  { enonce: "Si le pied de la perpendiculaire est Q(1;2) et le point donné est P(4;-2), la distance PQ vaut 25.", reponse: false, justification: "25 est le CARRÉ de la distance (5²) ; la distance elle-même vaut 5." },
  { enonce: "La perpendiculaire à une droite d'équation y=-4x+2 passant par un point donné a pour pente 4.", reponse: false, justification: "Une pente de 4 est différente de -4 : ni parallèle ni perpendiculaire ; la bonne pente perpendiculaire est 1/4." },
  { enonce: "Si une droite a pour pente m=2/3, sa perpendiculaire a pour pente 3/2.", reponse: false, justification: "Il manque le signe négatif : la bonne pente perpendiculaire est -3/2, pas 3/2." },
  { enonce: "Le pied de la perpendiculaire abaissée d'un point P sur une droite d n'appartient jamais à d.", reponse: false, justification: "Le pied de la perpendiculaire appartient au contraire TOUJOURS à d, par définition." },
  { enonce: "La distance d'un point à une droite peut être négative si le point est situé \"en-dessous\" de la droite.", reponse: false, justification: "Une distance est toujours positive ou nulle, quelle que soit la position du point." },
  { enonce: "Si P(0;0) et le pied de la perpendiculaire sur une droite d est Q(3;4), alors la distance de P à d vaut 7.", reponse: false, justification: "Le calcul correct (triangle 3-4-5) donne une distance de 5, pas 7." },
  { enonce: "La perpendiculaire à une droite horizontale est toujours une autre droite horizontale.", reponse: false, justification: "La perpendiculaire à une horizontale est une VERTICALE, pas une autre horizontale." },
];

const INTERSECTION_DROITES: QuestionVraiFaux[] = [
  { enonce: "Deux droites sont sécantes si et seulement si leurs vecteurs directeurs ne sont pas colinéaires.", reponse: true, justification: "Des vecteurs directeurs non colinéaires garantissent un unique point d'intersection." },
  { enonce: "Si deux droites ont des vecteurs directeurs colinéaires, elles sont soit parallèles distinctes, soit confondues.", reponse: true, justification: "La colinéarité des directions exclut les droites sécantes : il ne reste que ces deux cas." },
  { enonce: "Deux droites confondues ont une infinité de points communs.", reponse: true, justification: "Deux droites confondues sont en réalité la même droite : tous ses points sont communs." },
  { enonce: "Deux droites parallèles distinctes n'ont aucun point commun.", reponse: true, justification: "C'est la définition même de deux droites parallèles non confondues." },
  { enonce: "Deux droites sécantes ont exactement un point commun.", reponse: true, justification: "C'est la définition même de deux droites sécantes." },
  { enonce: "Pour savoir si deux droites de vecteurs directeurs colinéaires sont parallèles distinctes ou confondues, il suffit de vérifier si un point de l'une appartient à l'autre.", reponse: true, justification: "Si un point de la première appartient à la seconde, les droites sont confondues, sinon parallèles distinctes." },
  { enonce: "Les droites d'équations y=2x+1 et y=2x+5 sont parallèles distinctes (même pente, ordonnées différentes).", reponse: true, justification: "Même pente (2) mais ordonnées à l'origine différentes (1 et 5) : parallèles distinctes." },
  { enonce: "Les droites d'équations y=2x+1 et 2y=4x+2 sont confondues.", reponse: true, justification: "2y=4x+2 équivaut à y=2x+1 : c'est exactement la même droite." },
  { enonce: "Les droites d'équations y=x et y=-x+4 sont sécantes, et se coupent au point (2;2).", reponse: true, justification: "x=-x+4 → 2x=4 → x=2, y=2 : le point (2;2) vérifie les deux équations." },
  { enonce: "La colinéarité de deux vecteurs directeurs se teste avec le déterminant u_x·v_y-u_y·v_x=0.", reponse: true, justification: "C'est la formule standard du déterminant nul pour tester la colinéarité." },
  { enonce: "Deux droites sont sécantes si et seulement si leurs vecteurs directeurs sont colinéaires.", reponse: false, justification: "C'est l'inverse : des vecteurs directeurs colinéaires empêchent les droites d'être sécantes." },
  { enonce: "Si deux droites ont des vecteurs directeurs colinéaires, elles sont nécessairement sécantes.", reponse: false, justification: "Des vecteurs colinéaires donnent des droites parallèles distinctes ou confondues, jamais sécantes." },
  { enonce: "Deux droites confondues n'ont aucun point commun.", reponse: false, justification: "Deux droites confondues sont la même droite : elles ont TOUS leurs points en commun." },
  { enonce: "Deux droites parallèles distinctes ont exactement un point commun.", reponse: false, justification: "Elles n'en ont justement AUCUN — c'est ce qui les définit comme parallèles distinctes." },
  { enonce: "Deux droites sécantes n'ont jamais de point commun.", reponse: false, justification: "Deux droites sécantes ont, par définition, exactement un point commun." },
  { enonce: "Les droites d'équations y=2x+1 et y=2x+5 sont sécantes.", reponse: false, justification: "Elles ont la même pente (2) : elles sont parallèles, jamais sécantes." },
  { enonce: "Les droites d'équations y=2x+1 et 2y=4x+2 sont parallèles distinctes (jamais confondues).", reponse: false, justification: "Ces deux équations décrivent exactement la même droite : elles sont confondues." },
  { enonce: "Les droites d'équations y=x et y=-x+4 sont parallèles.", reponse: false, justification: "Leurs pentes (1 et -1) sont différentes : elles sont sécantes, pas parallèles." },
  { enonce: "Les droites d'équations y=x et y=-x+4 se coupent au point (1;3).", reponse: false, justification: "Le point (1;3) ne vérifie pas y=x (1≠3) ; le vrai point d'intersection est (2;2)." },
  { enonce: "Deux droites de vecteurs directeurs non colinéaires sont nécessairement parallèles.", reponse: false, justification: "Des vecteurs directeurs non colinéaires garantissent au contraire que les droites sont sécantes." },
  { enonce: "Les droites d'équations y=-x+3 et y=x-1 sont sécantes, et se coupent au point (2;1).", reponse: true, justification: "-x+3=x-1 → 4=2x → x=2, y=1 : le point (2;1) vérifie les deux équations." },
  { enonce: "Les droites d'équations y=3x-2 et 3x-y-2=0 sont confondues.", reponse: true, justification: "3x-y-2=0 équivaut à y=3x-2 : c'est exactement la même droite." },
  { enonce: "Les droites d'équations y=-2x+5 et y=-2x-1 sont parallèles distinctes.", reponse: true, justification: "Même pente (-2) mais ordonnées à l'origine différentes (5 et -1) : parallèles distinctes." },
  { enonce: "Les droites de vecteurs directeurs (2;-1) et (1;3) sont sécantes, car leurs vecteurs ne sont pas colinéaires.", reponse: true, justification: "Le déterminant 2×3-(-1)×1=7≠0 : les vecteurs ne sont pas colinéaires, les droites sont sécantes." },
  { enonce: "Le déterminant des vecteurs directeurs (4;2) et (2;1) est nul, donc ces deux droites (si distinctes) sont parallèles.", reponse: true, justification: "4×1-2×2=0 : le déterminant est nul, les vecteurs sont colinéaires." },
  { enonce: "Les droites d'équations implicites 2x+3y-6=0 et 4x+6y-12=0 sont confondues.", reponse: true, justification: "4x+6y-12=0 s'obtient en multipliant 2x+3y-6=0 par 2 : c'est la même droite." },
  { enonce: "Les droites d'équations implicites 2x+3y-6=0 et 4x+6y+5=0 sont parallèles distinctes.", reponse: true, justification: "Les coefficients de x et y sont proportionnels (4;6)=2×(2;3), mais 2×(-6)=-12≠5 : parallèles, non confondues." },
  { enonce: "Les droites paramétriques (x=1+2t, y=-1+4t) et (x=3-t, y=5-2t) sont parallèles.", reponse: true, justification: "Vecteurs directeurs (2;4) et (-1;-2) : déterminant 2×(-2)-4×(-1)=0, donc colinéaires." },
  { enonce: "Les droites d'équations y=-x+3 et y=x-1 sont parallèles.", reponse: false, justification: "Leurs pentes (-1 et 1) sont différentes : elles sont sécantes, pas parallèles." },
  { enonce: "Les droites d'équations y=3x-2 et 3x-y-2=0 sont parallèles distinctes (jamais confondues).", reponse: false, justification: "Ces deux équations décrivent exactement la même droite : elles sont confondues." },
  { enonce: "Les droites d'équations y=-2x+5 et y=-2x-1 sont confondues.", reponse: false, justification: "Même pente mais ordonnées à l'origine différentes : elles sont parallèles distinctes, pas confondues." },
  { enonce: "Les droites de vecteurs directeurs (2;-1) et (1;3) sont parallèles, car leurs vecteurs sont colinéaires.", reponse: false, justification: "Le déterminant 2×3-(-1)×1=7≠0 : les vecteurs ne sont PAS colinéaires, les droites sont sécantes." },
  { enonce: "Le déterminant des vecteurs directeurs (4;2) et (2;1) vaut 8, donc les droites sont sécantes.", reponse: false, justification: "Le déterminant correct est 4×1-2×2=0 : il est nul, les droites sont parallèles ou confondues." },
  { enonce: "Les droites d'équations implicites 2x+3y-6=0 et 4x+6y-12=0 sont parallèles distinctes (jamais confondues).", reponse: false, justification: "4x+6y-12=0 s'obtient en multipliant la première par 2 : ces droites sont confondues." },
  { enonce: "Les droites paramétriques (x=1+2t, y=-1+4t) et (x=3-t, y=5-2t) sont sécantes.", reponse: false, justification: "Leurs vecteurs directeurs (2;4) et (-1;-2) sont colinéaires (déterminant nul) : elles sont parallèles, pas sécantes." },
];

const EQUATION_CERCLE_GRAPHE: QuestionVraiFaux[] = [
  { enonce: "L'équation d'un cercle de centre (x0;y0) et de rayon r s'écrit (x-x0)²+(y-y0)²=r².", reponse: true, justification: "C'est la définition même de l'équation cartésienne non développée d'un cercle." },
  { enonce: "Un cercle de centre (2;3) et de rayon 4 a pour équation (x-2)²+(y-3)²=16.", reponse: true, justification: "r²=4²=16." },
  { enonce: "Si le point marqué sur le cercle est aligné horizontalement avec le centre, le rayon se lit directement en comptant les carreaux.", reponse: true, justification: "L'écart horizontal entre les deux points est alors directement égal au rayon." },
  { enonce: "Si le point marqué sur le cercle est décalé en diagonale par rapport au centre, il faut utiliser la formule de distance pour retrouver le rayon.", reponse: true, justification: "Le rayon est alors l'hypoténuse d'un triangle rectangle : il faut calculer la distance centre-point." },
  { enonce: "Un cercle de centre (0;0) passant par le point (3;4) a pour rayon r=5.", reponse: true, justification: "Triplet pythagoricien : √(3²+4²)=√25=5." },
  { enonce: "Le rayon d'un cercle est toujours une longueur positive.", reponse: true, justification: "Un rayon est une distance : il est toujours positif (jamais nul ni négatif pour un vrai cercle)." },
  { enonce: "Un cercle de centre (-1;2) et de rayon 3 a pour équation (x+1)²+(y-2)²=9.", reponse: true, justification: "(x-(-1))²=(x+1)² et r²=9." },
  { enonce: "Le second membre de l'équation d'un cercle non développée est toujours le carré du rayon, jamais le rayon lui-même.", reponse: true, justification: "L'équation s'écrit ...=r², pas ...=r." },
  { enonce: "Un cercle de centre (1;1) passant par (1;5) a pour rayon r=4 (lu directement, alignement vertical).", reponse: true, justification: "Même abscisse (1) pour le centre et le point : le rayon est l'écart des ordonnées, |5-1|=4." },
  { enonce: "Deux points distincts marqués sur le même cercle sont toujours à la même distance du centre.", reponse: true, justification: "C'est la définition même d'un cercle : tous ses points sont à distance r du centre." },
  { enonce: "L'équation d'un cercle de centre (x0;y0) et de rayon r s'écrit (x-x0)²+(y-y0)²=r.", reponse: false, justification: "Le second membre doit être r² (le carré du rayon), pas r." },
  { enonce: "Un cercle de centre (2;3) et de rayon 4 a pour équation (x-2)²+(y-3)²=4.", reponse: false, justification: "Le second membre doit être r²=16, pas 4 (qui serait r²=4, donc r=2)." },
  { enonce: "Si le point marqué est aligné en diagonale avec le centre, le rayon se lit directement en comptant les carreaux.", reponse: false, justification: "En diagonale, il faut passer par la formule de distance (Pythagore), pas une simple lecture directe." },
  { enonce: "Un cercle de centre (0;0) passant par le point (3;4) a pour rayon r=7.", reponse: false, justification: "Le calcul correct (Pythagore) donne r=5, pas 7." },
  { enonce: "Le rayon d'un cercle peut être négatif si le centre est en-dessous de l'axe Ox.", reponse: false, justification: "Le rayon est toujours une longueur positive, quelle que soit la position du centre." },
  { enonce: "Un cercle de centre (-1;2) et de rayon 3 a pour équation (x-1)²+(y+2)²=9.", reponse: false, justification: "Les signes sont inversés : ce devrait être (x+1)²+(y-2)²=9." },
  { enonce: "Le second membre de l'équation d'un cercle non développée est toujours le rayon lui-même, jamais son carré.", reponse: false, justification: "C'est l'inverse : le second membre est toujours r², jamais r directement." },
  { enonce: "Un cercle de centre (1;1) passant par (1;5) a pour rayon r=5.", reponse: false, justification: "L'écart d'ordonnées correct est |5-1|=4, pas 5." },
  { enonce: "Deux points distincts marqués sur un même cercle peuvent être à des distances différentes du centre.", reponse: false, justification: "Tous les points d'un cercle sont, par définition, à exactement la même distance (le rayon) du centre." },
  { enonce: "L'équation d'un cercle nécessite toujours de connaître 3 points de ce cercle, jamais son centre directement.", reponse: false, justification: "Connaître le centre et le rayon (ou un point) suffit amplement ; 3 points ne sont pas nécessaires." },
  { enonce: "Un cercle de centre (3;-2) et de rayon 5 a pour équation (x-3)²+(y+2)²=25.", reponse: true, justification: "(y-(-2))²=(y+2)² et r²=25." },
  { enonce: "Un cercle de centre (0;0) passant par le point (5;12) a pour rayon 13 (triplet pythagoricien 5-12-13).", reponse: true, justification: "√(5²+12²)=√169=13." },
  { enonce: "Un cercle de centre (2;2) passant par (2;-3) a pour rayon 5 (lu directement, alignement vertical).", reponse: true, justification: "Même abscisse (2) pour le centre et le point : le rayon est l'écart des ordonnées, |-3-2|=5." },
  { enonce: "Un cercle de centre (-3;1) et de rayon 6 a pour équation (x+3)²+(y-1)²=36.", reponse: true, justification: "(x-(-3))²=(x+3)² et r²=36." },
  { enonce: "Un cercle de centre (4;0) passant par (0;3) a pour rayon 5.", reponse: true, justification: "Δx=4, Δy=3, rayon=√(16+9)=√25=5." },
  { enonce: "L'équation (x-5)²+(y+4)²=49 représente un cercle de centre (5;-4) et de rayon 7.", reponse: true, justification: "r²=49 → r=√49=7." },
  { enonce: "Un cercle centré à l'origine et de rayon r passe toujours par les points (r;0), (-r;0), (0;r) et (0;-r).", reponse: true, justification: "Ces 4 points vérifient tous x²+y²=r²." },
  { enonce: "Si un point du cercle est décalé de 6 unités horizontalement et 8 unités verticalement par rapport au centre, le rayon vaut 10.", reponse: true, justification: "√(6²+8²)=√(36+64)=√100=10." },
  { enonce: "Un cercle de centre (3;-2) et de rayon 5 a pour équation (x-3)²+(y-2)²=25.", reponse: false, justification: "Le signe est incorrect : ce devrait être (y+2)², pas (y-2)²." },
  { enonce: "Un cercle de centre (0;0) passant par le point (5;12) a pour rayon 17.", reponse: false, justification: "Le calcul correct (Pythagore) donne un rayon de 13, pas 17." },
  { enonce: "Un cercle de centre (2;2) passant par (2;-3) a pour rayon 3.", reponse: false, justification: "L'écart d'ordonnées correct est |-3-2|=5, pas 3." },
  { enonce: "Un cercle de centre (-3;1) et de rayon 6 a pour équation (x-3)²+(y+1)²=36.", reponse: false, justification: "Les deux signes sont inversés : ce devrait être (x+3)²+(y-1)²=36." },
  { enonce: "Un cercle de centre (4;0) passant par (0;3) a pour rayon 7.", reponse: false, justification: "Le calcul correct (Pythagore) donne un rayon de 5, pas 7." },
  { enonce: "L'équation (x-5)²+(y+4)²=49 représente un cercle de rayon 49.", reponse: false, justification: "49 est le CARRÉ du rayon (r²) ; le rayon lui-même vaut r=√49=7." },
  { enonce: "Si un point du cercle est décalé de 6 unités horizontalement et 8 unités verticalement par rapport au centre, le rayon vaut 14 (somme des deux écarts).", reponse: false, justification: "Le rayon se calcule par Pythagore (√(6²+8²)=10), pas par simple addition des écarts." },
];

const CENTRE_RAYON_CERCLE: QuestionVraiFaux[] = [
  { enonce: "Pour représenter un cercle (et non une ellipse), les coefficients devant x² et y² doivent être identiques.", reponse: true, justification: "Un coefficient commun k devant les deux termes quadratiques est la condition pour un cercle." },
  { enonce: "Retrouver le centre et le rayon d'un cercle depuis son équation développée nécessite une complétion du carré.", reponse: true, justification: "C'est la méthode standard pour faire réapparaître la forme (x-x0)²+(y-y0)²=r²." },
  { enonce: "Si l'équation développée est x²+y²-4x+2y-4=0, alors en complétant le carré, le centre est (2;-1).", reponse: true, justification: "x²-4x=(x-2)²-4 et y²+2y=(y+1)²-1, donc centre (2;-1)." },
  { enonce: "Si l'équation développée est x²+y²-4x+2y-4=0, le rayon vaut 3 (r²=4+1+4=9).", reponse: true, justification: "(x-2)²+(y+1)²=4+1+4=9, donc r=√9=3." },
  { enonce: "Un coefficient commun k>1 devant x² et y² doit d'abord être factorisé avant de compléter le carré.", reponse: true, justification: "Il faut isoler k en facteur commun avant de pouvoir compléter le carré à l'intérieur." },
  { enonce: "Le rayon d'un cercle depuis l'équation développée peut être rationnel ou irrationnel selon les valeurs des coefficients.", reponse: true, justification: "Selon que le terme constant obtenu est un carré parfait (de fraction) ou non." },
  { enonce: "Si, après complétion du carré, r²=5, le rayon est irrationnel (r=√5).", reponse: true, justification: "5 n'est pas un carré parfait, donc √5 est irrationnel." },
  { enonce: "Si, après complétion du carré, r²=9/4, le rayon est rationnel (r=3/2).", reponse: true, justification: "9/4 est le carré de la fraction 3/2, donc r=3/2 est rationnel." },
  { enonce: "La méthode de résolution comporte 3 étapes : regroupement/factorisation, complétion du carré, extraction du centre et du rayon.", reponse: true, justification: "C'est exactement la séquence en 3 écrans utilisée par ce générateur." },
  { enonce: "Une équation développée kx²+ky²+bx·x+by·y=c ne représente un vrai cercle que si le terme constant obtenu après complétion du carré est strictement positif.", reponse: true, justification: "Un terme constant négatif ou nul donnerait un rayon carré négatif ou nul : pas de vrai cercle." },
  { enonce: "Pour représenter un cercle, les coefficients devant x² et y² peuvent être différents.", reponse: false, justification: "S'ils sont différents, l'équation représente une ellipse, jamais un cercle." },
  { enonce: "Retrouver le centre et le rayon d'un cercle depuis son équation développée ne nécessite jamais de complétion du carré.", reponse: false, justification: "La complétion du carré est justement la méthode centrale utilisée pour cela." },
  { enonce: "Si l'équation développée est x²+y²-4x+2y-4=0, alors le centre est (-2;1).", reponse: false, justification: "Le calcul correct (complétion du carré) donne le centre (2;-1), signes opposés." },
  { enonce: "Si l'équation développée est x²+y²-4x+2y-4=0, le rayon vaut 9.", reponse: false, justification: "9 est le rayon CARRÉ (r²) ; le rayon lui-même vaut r=√9=3." },
  { enonce: "Un coefficient commun k devant x² et y² n'a jamais besoin d'être factorisé.", reponse: false, justification: "Quand k>1, il faut le mettre en facteur commun avant de compléter le carré." },
  { enonce: "Le rayon d'un cercle depuis l'équation développée est toujours un nombre entier.", reponse: false, justification: "Le rayon peut être rationnel non entier, ou même irrationnel, selon les coefficients." },
  { enonce: "Si, après complétion du carré, r²=5, le rayon est rationnel.", reponse: false, justification: "5 n'est pas un carré parfait : le rayon √5 est irrationnel, pas rationnel." },
  { enonce: "Si, après complétion du carré, r²=9/4, le rayon est irrationnel.", reponse: false, justification: "9/4 est le carré parfait de la fraction 3/2 : le rayon est rationnel, pas irrationnel." },
  { enonce: "La méthode de résolution ne comporte qu'une seule étape : la lecture directe du centre et du rayon.", reponse: false, justification: "Il faut regrouper/factoriser puis compléter le carré avant de pouvoir extraire centre et rayon." },
  { enonce: "Une équation développée peut représenter un cercle même si le terme constant obtenu après complétion du carré est négatif.", reponse: false, justification: "Un terme constant négatif donnerait un rayon carré négatif, impossible pour un vrai cercle." },
  { enonce: "Si l'équation développée est x²+y²+6x-8y+9=0, alors en complétant le carré, le centre est (-3;4).", reponse: true, justification: "x²+6x=(x+3)²-9 et y²-8y=(y-4)²-16, donc centre (-3;4)." },
  { enonce: "Si l'équation développée est x²+y²+6x-8y+9=0, le rayon vaut 4.", reponse: true, justification: "(x+3)²+(y-4)²=9+16-9=16, donc r=√16=4." },
  { enonce: "Pour l'équation développée 2x²+2y²-8x+4y-2=0, il faut d'abord diviser par 2 avant de compléter le carré.", reponse: true, justification: "Le coefficient commun 2 doit être mis en facteur avant de pouvoir compléter le carré." },
  { enonce: "Après division par 2, l'équation 2x²+2y²-8x+4y-2=0 devient x²+y²-4x+2y-1=0.", reponse: true, justification: "Chaque terme est divisé par 2 : -8x/2=-4x, 4y/2=2y, -2/2=-1." },
  { enonce: "Pour l'équation x²+y²-4x+2y-1=0, le rayon obtenu est irrationnel (r=√6).", reponse: true, justification: "(x-2)²+(y+1)²=4+1+1=6, et 6 n'est pas un carré parfait, donc r=√6 est irrationnel." },
  { enonce: "Pour l'équation x²+y²-4x+2y-1=0, le centre est (2;-1).", reponse: true, justification: "x²-4x=(x-2)²-4 et y²+2y=(y+1)²-1, donc centre (2;-1)." },
  { enonce: "Deux équations développées différentes peuvent représenter le même cercle si l'une est un multiple non nul de l'autre.", reponse: true, justification: "Multiplier toute l'équation par une constante non nulle ne change pas le cercle qu'elle représente." },
  { enonce: "Si, après complétion du carré, r²=49/16, le rayon est rationnel, égal à 7/4.", reponse: true, justification: "49/16 est le carré de la fraction 7/4, donc r=7/4 est rationnel." },
  { enonce: "Si l'équation développée est x²+y²+6x-8y+9=0, alors le centre est (3;-4).", reponse: false, justification: "Le calcul correct (complétion du carré) donne le centre (-3;4), signes opposés." },
  { enonce: "Si l'équation développée est x²+y²+6x-8y+9=0, le rayon vaut 16.", reponse: false, justification: "16 est le rayon CARRÉ (r²) ; le rayon lui-même vaut r=√16=4." },
  { enonce: "Pour l'équation développée 2x²+2y²-8x+4y-2=0, on peut compléter le carré directement, sans diviser par 2 au préalable.", reponse: false, justification: "Le coefficient commun 2 doit d'abord être mis en facteur, sinon la complétion du carré est incorrecte." },
  { enonce: "Après division par 2, l'équation 2x²+2y²-8x+4y-2=0 devient x²+y²-4x+2y-2=0.", reponse: false, justification: "Le terme constant correct est -1 (car -2/2=-1), pas -2." },
  { enonce: "Pour l'équation x²+y²-4x+2y-1=0, le rayon obtenu est rationnel.", reponse: false, justification: "r²=6, qui n'est pas un carré parfait : le rayon √6 est irrationnel, pas rationnel." },
  { enonce: "Pour l'équation x²+y²-4x+2y-1=0, le centre est (-2;1).", reponse: false, justification: "Le calcul correct (complétion du carré) donne le centre (2;-1), signes opposés." },
  { enonce: "Si, après complétion du carré, r²=49/16, le rayon est irrationnel.", reponse: false, justification: "49/16 est le carré parfait de la fraction 7/4 : le rayon est rationnel, pas irrationnel." },
];

const EQUATION_PARABOLE_GRAPHE: QuestionVraiFaux[] = [
  { enonce: "Pour une parabole d'axe vertical, l'équation s'écrit (x-x_S)²=2p(y-y_S), où S est le sommet.", reponse: true, justification: "C'est la forme standard d'une parabole à axe vertical (directrice horizontale)." },
  { enonce: "Pour une parabole d'axe horizontal, l'équation s'écrit (y-y_S)²=2p(x-x_S), où S est le sommet.", reponse: true, justification: "C'est la forme standard d'une parabole à axe horizontal (directrice verticale)." },
  { enonce: "Le paramètre p est une valeur SIGNÉE, jamais une distance non signée.", reponse: true, justification: "p porte le signe de l'orientation de la parabole (ouverture vers le haut/bas ou droite/gauche)." },
  { enonce: "Pour une parabole d'axe vertical, p=2(y_F-y_S), où F est le foyer.", reponse: true, justification: "C'est la définition exacte du paramètre p pour une parabole d'axe vertical." },
  { enonce: "Pour une parabole d'axe horizontal, p=2(x_F-x_S).", reponse: true, justification: "C'est la définition exacte du paramètre p pour une parabole d'axe horizontal." },
  { enonce: "Si le sommet est S(0;0) et le foyer F(0;2), alors p=4 et l'équation est x²=8y.", reponse: true, justification: "p=2(2-0)=4 ; équation x²=2p·y=8y." },
  { enonce: "Si p est négatif, la parabole s'ouvre dans le sens opposé à l'axe correspondant (vers le bas ou vers la gauche).", reponse: true, justification: "Le signe de p détermine directement le sens d'ouverture de la parabole." },
  { enonce: "Le foyer d'une parabole se situe toujours sur l'axe de symétrie de la parabole.", reponse: true, justification: "C'est une propriété géométrique fondamentale de la parabole." },
  { enonce: "Si le sommet est S(1;2) et le foyer F(1;4), l'axe de la parabole est vertical.", reponse: true, justification: "Même abscisse pour S et F : le foyer est décalé verticalement, l'axe est donc vertical." },
  { enonce: "Le paramètre p est toujours un nombre pair, car c'est le double d'une différence de coordonnées entières.", reponse: true, justification: "p=2×(différence entière), donc toujours pair par construction." },
  { enonce: "Pour une parabole d'axe vertical, l'équation s'écrit (y-y_S)²=2p(x-x_S).", reponse: false, justification: "C'est la forme d'une parabole d'axe HORIZONTAL, pas vertical." },
  { enonce: "Pour une parabole d'axe horizontal, l'équation s'écrit (x-x_S)²=2p(y-y_S).", reponse: false, justification: "C'est la forme d'une parabole d'axe VERTICAL, pas horizontal." },
  { enonce: "Le paramètre p est toujours une distance positive, jamais une valeur signée.", reponse: false, justification: "p est signé : il peut être négatif si la parabole s'ouvre vers le bas ou la gauche." },
  { enonce: "Pour une parabole d'axe vertical, p=(y_F-y_S) (sans le facteur 2).", reponse: false, justification: "Il manque le facteur 2 : la bonne formule est p=2(y_F-y_S)." },
  { enonce: "Si le sommet est S(0;0) et le foyer F(0;2), alors p=2.", reponse: false, justification: "Le calcul correct donne p=2(2-0)=4, pas 2 (oubli du facteur 2)." },
  { enonce: "Si p est négatif, la parabole s'ouvre nécessairement vers le haut.", reponse: false, justification: "Un p négatif indique au contraire une ouverture vers le bas (axe vertical) ou la gauche (axe horizontal)." },
  { enonce: "Le foyer d'une parabole ne se situe jamais sur son axe de symétrie.", reponse: false, justification: "Le foyer se situe au contraire TOUJOURS sur l'axe de symétrie de la parabole." },
  { enonce: "Si le sommet est S(1;2) et le foyer F(1;4), l'axe de la parabole est horizontal.", reponse: false, justification: "Le décalage entre S et F est vertical (même abscisse) : l'axe est donc vertical, pas horizontal." },
  { enonce: "Le paramètre p peut être un nombre impair si les coordonnées du sommet et du foyer sont entières.", reponse: false, justification: "p est toujours le double d'un entier, donc toujours pair, jamais impair." },
  { enonce: "Le sommet d'une parabole est toujours situé à égale distance du foyer et de l'axe Ox.", reponse: false, justification: "Le sommet est équidistant du foyer et de la DIRECTRICE, pas de l'axe Ox en général." },
  { enonce: "Si le sommet est S(0;0) et le foyer F(3;0), alors p=6 et l'équation est y²=12x.", reponse: true, justification: "Axe horizontal (F décalé en x) : p=2(3-0)=6 ; y²=2p·x=12x." },
  { enonce: "Si le sommet est S(2;-1) et le foyer F(2;-3), alors p=-4.", reponse: true, justification: "Axe vertical (F décalé en y) : p=2(-3-(-1))=2×(-2)=-4." },
  { enonce: "Pour la parabole de sommet S(2;-1) et p=-4 (axe vertical), l'équation est (x-2)²=-8(y+1).", reponse: true, justification: "(x-x_S)²=2p(y-y_S)=2×(-4)×(y+1)=-8(y+1)." },
  { enonce: "Si le sommet est S(-1;3) et le foyer F(2;3), l'axe de la parabole est horizontal.", reponse: true, justification: "Même ordonnée (3) pour S et F : le foyer est décalé horizontalement, l'axe est donc horizontal." },
  { enonce: "Pour S(-1;3) et F(2;3), on a p=6.", reponse: true, justification: "p=2(x_F-x_S)=2(2-(-1))=6." },
  { enonce: "Une parabole avec p>0 et axe horizontal s'ouvre vers la droite.", reponse: true, justification: "p=2(x_F-x_S)>0 signifie que le foyer est à droite du sommet : la parabole s'ouvre vers la droite." },
  { enonce: "Le paramètre p peut aussi s'interpréter comme le double de la distance signée entre le sommet et le foyer, le long de l'axe de la parabole.", reponse: true, justification: "C'est exactement ce qu'exprime la formule p=2(y_F-y_S) ou p=2(x_F-x_S)." },
  { enonce: "Si le sommet est S(0;0) et p=-6 (axe vertical), l'équation de la parabole est x²=-12y.", reponse: true, justification: "x²=2p·y=2×(-6)×y=-12y." },
  { enonce: "Si le sommet est S(0;0) et le foyer F(3;0), alors p=3.", reponse: false, justification: "Le calcul correct donne p=2(3-0)=6, pas 3 (oubli du facteur 2)." },
  { enonce: "Si le sommet est S(2;-1) et le foyer F(2;-3), alors p=4 (positif).", reponse: false, justification: "Le calcul correct donne p=2(-3-(-1))=-4 (négatif), pas +4." },
  { enonce: "Pour la parabole de sommet S(2;-1) et p=-4 (axe vertical), l'équation est (x-2)²=8(y+1).", reponse: false, justification: "Le signe est incorrect : 2p=2×(-4)=-8, donc l'équation correcte est (x-2)²=-8(y+1)." },
  { enonce: "Si le sommet est S(-1;3) et le foyer F(2;3), l'axe de la parabole est vertical.", reponse: false, justification: "Le décalage entre S et F est horizontal (même ordonnée) : l'axe est donc horizontal, pas vertical." },
  { enonce: "Pour S(-1;3) et F(2;3), on a p=3 (différence des abscisses sans le facteur 2).", reponse: false, justification: "Il manque le facteur 2 : la bonne formule donne p=2(2-(-1))=6." },
  { enonce: "Une parabole avec p>0 et axe horizontal s'ouvre vers la gauche.", reponse: false, justification: "Un p positif signifie au contraire que la parabole s'ouvre vers la DROITE." },
  { enonce: "Si le sommet est S(0;0) et p=-6 (axe vertical), l'équation de la parabole est x²=12y.", reponse: false, justification: "Le signe est incorrect : p négatif donne x²=2p·y=-12y (ouverture vers le bas), pas +12y." },
];

const SOMMET_FOYER_PARABOLE: QuestionVraiFaux[] = [
  { enonce: "Le sommet est toujours le milieu du segment reliant le foyer à la directrice (le long de l'axe).", reponse: true, justification: "C'est la propriété géométrique fondamentale reliant sommet, foyer et directrice." },
  { enonce: "La directrice est symétrique du foyer par rapport au sommet, le long de l'axe de la parabole.", reponse: true, justification: "Puisque le sommet est le milieu entre foyer et directrice, l'un est le symétrique de l'autre." },
  { enonce: "Pour retrouver sommet/foyer/p depuis une équation développée, on complète le carré sur la variable qui apparaît au carré.", reponse: true, justification: "La complétion du carré fait réapparaître la forme (variable-sommet)²=2p(autre variable-sommet)." },
  { enonce: "Si l'équation développée est x²-2x-4y+5=0, on peut la réécrire (x-1)²=4y-4=4(y-1), donc le sommet est (1;1).", reponse: true, justification: "x²-2x=(x-1)²-1 ; l'équation devient (x-1)²-1-4y+5=0 → (x-1)²=4y-4=4(y-1)." },
  { enonce: "Dans l'équation précédente, p=2 (car 2p=4).", reponse: true, justification: "(x-1)²=4(y-1) s'identifie à (x-x_S)²=2p(y-y_S) avec 2p=4, donc p=2." },
  { enonce: "Le foyer se situe entre le sommet et la directrice n'est jamais vrai — c'est le sommet qui est entre le foyer et la directrice.", reponse: true, justification: "C'est bien le sommet qui est au milieu, jamais le foyer." },
  { enonce: "Une erreur de signe sur p peut inverser la position du foyer et de la directrice.", reponse: true, justification: "Le signe de p détermine de quel côté du sommet se trouvent le foyer et la directrice." },
  { enonce: "Le coefficient devant le terme au carré dans l'équation développée est toujours positif dans ce générateur (le signe de l'ouverture est porté par p, pas par ce coefficient).", reponse: true, justification: "C'est une convention explicite de ce générateur, pour éviter de doubler le signe de l'ouverture." },
  { enonce: "Si p est positif pour une parabole d'axe vertical, le foyer est au-dessus du sommet.", reponse: true, justification: "p=2(y_F-y_S)>0 signifie y_F>y_S : le foyer est plus haut que le sommet." },
  { enonce: "Si p est négatif pour une parabole d'axe horizontal, le foyer est à gauche du sommet.", reponse: true, justification: "p=2(x_F-x_S)<0 signifie x_F<x_S : le foyer est à gauche du sommet." },
  { enonce: "Le foyer est toujours le milieu du segment reliant le sommet à la directrice.", reponse: false, justification: "C'est le SOMMET qui est le milieu entre le foyer et la directrice, jamais le foyer." },
  { enonce: "La directrice passe toujours par le sommet de la parabole.", reponse: false, justification: "La directrice ne passe jamais par le sommet ; elle est à une distance |p|/2 du sommet." },
  { enonce: "Pour retrouver sommet/foyer/p depuis une équation développée, aucune complétion du carré n'est nécessaire.", reponse: false, justification: "La complétion du carré est justement la méthode indispensable pour cette étape." },
  { enonce: "Si l'équation développée est x²-2x-4y+5=0, le sommet est (1;-1).", reponse: false, justification: "Le calcul correct (complétion du carré) donne le sommet (1;1), pas (1;-1)." },
  { enonce: "Dans l'équation x²-2x-4y+5=0 réécrite (x-1)²=4(y-1), p=4.", reponse: false, justification: "2p=4 donne p=2, pas p=4 (oubli de diviser par 2)." },
  { enonce: "Le foyer se situe toujours entre le sommet et la directrice.", reponse: false, justification: "C'est le sommet qui est toujours entre le foyer et la directrice, pas l'inverse." },
  { enonce: "Une erreur de signe sur p n'a aucune conséquence sur la position du foyer ou de la directrice.", reponse: false, justification: "Une erreur de signe inverse directement le côté du sommet où se trouvent le foyer et la directrice." },
  { enonce: "Le coefficient devant le terme au carré dans l'équation développée peut être négatif dans ce générateur, portant alors le signe de l'ouverture.", reponse: false, justification: "Ce coefficient reste toujours positif ; c'est p, et lui seul, qui porte le signe de l'ouverture." },
  { enonce: "Si p est positif pour une parabole d'axe vertical, le foyer est en-dessous du sommet.", reponse: false, justification: "p positif signifie au contraire que le foyer est AU-DESSUS du sommet." },
  { enonce: "Si p est négatif pour une parabole d'axe horizontal, le foyer est à droite du sommet.", reponse: false, justification: "p négatif signifie au contraire que le foyer est À GAUCHE du sommet." },
  { enonce: "Si l'équation développée est y²+4y-8x+20=0, on peut la réécrire (y+2)²=8(x-2), donc le sommet est (2;-2).", reponse: true, justification: "y²+4y=(y+2)²-4 ; l'équation devient (y+2)²-4-8x+20=0 → (y+2)²=8x-16=8(x-2)." },
  { enonce: "Dans l'équation précédente, p=4 (car 2p=8).", reponse: true, justification: "(y+2)²=8(x-2) s'identifie à (y-y_S)²=2p(x-x_S) avec 2p=8, donc p=4." },
  { enonce: "Pour cette parabole (p=4>0, axe horizontal), le foyer est à droite du sommet.", reponse: true, justification: "p=2(x_F-x_S)>0 signifie x_F>x_S : le foyer est à droite du sommet." },
  { enonce: "Le foyer de la parabole y²+4y-8x+20=0 est le point (4;-2).", reponse: true, justification: "x_F=x_S+p/2=2+2=4 ; y_F=y_S=-2 (axe horizontal, même ordonnée que le sommet)." },
  { enonce: "La directrice de cette parabole est la droite verticale x=0 (symétrique du foyer par rapport au sommet).", reponse: true, justification: "Le sommet (x=2) est le milieu entre le foyer (x=4) et la directrice : (4+x_d)/2=2 donne x_d=0." },
  { enonce: "Une autre équation développée, x²-6x-4y+5=0, se réécrit (x-3)²=4(y+1), donc le sommet est (3;-1).", reponse: true, justification: "x²-6x=(x-3)²-9 ; l'équation devient (x-3)²-9-4y+5=0 → (x-3)²=4y+4=4(y+1)." },
  { enonce: "Pour x²-6x-4y+5=0 réécrite (x-3)²=4(y+1), p=2 (car 2p=4).", reponse: true, justification: "(x-3)²=4(y+1) s'identifie à (x-x_S)²=2p(y-y_S) avec 2p=4, donc p=2." },
  { enonce: "Pour cette parabole (p=2>0, axe vertical), le foyer est au-dessus du sommet, en (3;0).", reponse: true, justification: "y_F=y_S+p/2=-1+1=0 ; le foyer (3;0) est bien au-dessus du sommet (3;-1)." },
  { enonce: "Si l'équation développée est y²+4y-8x+20=0, le sommet est (2;2).", reponse: false, justification: "Le calcul correct (complétion du carré) donne le sommet (2;-2), pas (2;2)." },
  { enonce: "Dans l'équation précédente, p=8.", reponse: false, justification: "2p=8 donne p=4, pas p=8 (oubli de diviser par 2)." },
  { enonce: "Pour cette parabole (p=4>0, axe horizontal), le foyer est à gauche du sommet.", reponse: false, justification: "p positif signifie au contraire que le foyer est À DROITE du sommet." },
  { enonce: "Le foyer de la parabole y²+4y-8x+20=0 est le point (2;2).", reponse: false, justification: "Le calcul correct donne le foyer (4;-2), pas (2;2)." },
  { enonce: "La directrice de cette parabole est la droite horizontale y=0.", reponse: false, justification: "L'axe étant horizontal, la directrice est une droite VERTICALE (x=0), pas horizontale." },
  { enonce: "L'équation x²-6x-4y+5=0 se réécrit (x-3)²=4(y+1), donc le sommet est (-3;1).", reponse: false, justification: "Le calcul correct (complétion du carré) donne le sommet (3;-1), signes opposés." },
  { enonce: "Pour x²-6x-4y+5=0 réécrite (x-3)²=4(y+1), le foyer est en-dessous du sommet, en (3;-2).", reponse: false, justification: "p=2>0 signifie que le foyer est AU-DESSUS du sommet, en (3;0), pas en-dessous." },
];

const CONSTRUCTION_PARABOLE: QuestionVraiFaux[] = [
  { enonce: "La construction géométrique d'une parabole au compas et à l'équerre ne nécessite aucune coordonnée numérique.", reponse: true, justification: "C'est une construction purement géométrique : aucune lecture ni saisie de coordonnées." },
  { enonce: "La méthode de construction utilise un cercle centré au foyer et une droite parallèle à la directrice.", reponse: true, justification: "C'est exactement la méthode cercle-droite utilisée par ce générateur." },
  { enonce: "Le rayon du cercle utilisé doit toujours être strictement supérieur à la moitié de la distance entre le foyer et la directrice.", reponse: true, justification: "C'est la contrainte stricte r>distance(F,d)/2, garantissant une intersection réelle." },
  { enonce: "Les points d'intersection entre le cercle (centré au foyer) et la droite parallèle à la directrice sont des points de la parabole.", reponse: true, justification: "C'est le principe même de la construction : ces points vérifient la définition de la parabole." },
  { enonce: "Chaque point construit est équidistant du foyer et de la directrice, propriété caractéristique de la parabole.", reponse: true, justification: "C'est la définition même d'une parabole : lieu des points équidistants du foyer et de la directrice." },
  { enonce: "Dans cette construction, la directrice est représentée obliquement à l'écran pour éviter une confusion avec les axes du repère.", reponse: true, justification: "L'obliquité de la directrice est une exigence pédagogique explicite de ce générateur." },
  { enonce: "La courbe finale de la parabole est obtenue par interpolation progressive à partir de plusieurs points construits, jamais par des segments droits.", reponse: true, justification: "Une interpolation parabolique progressive relie les points, jamais un tracé libre ni des segments droits." },
  { enonce: "Si le rayon choisi est trop petit (inférieur ou égal à la moitié de la distance foyer-directrice), le cercle ne coupe pas la droite parallèle à la directrice.", reponse: true, justification: "C'est justement la raison de la contrainte stricte r>distance(F,d)/2." },
  { enonce: "La droite parallèle à la directrice, utilisée dans la construction, doit être tracée du côté du foyer.", reponse: true, justification: "La droite doit être du côté de F pour que l'intersection avec le cercle donne des points de la parabole." },
  { enonce: "Chaque itération de la construction (un geste de compas puis d'équerre) produit exactement deux points de la parabole (sauf cas limite).", reponse: true, justification: "Un cercle et une droite sécants se coupent généralement en exactement deux points." },
  { enonce: "La construction géométrique d'une parabole au compas et à l'équerre nécessite de lire les coordonnées numériques de chaque point.", reponse: false, justification: "Aucune coordonnée numérique n'est lue ni saisie : la construction est purement géométrique." },
  { enonce: "La méthode de construction utilise un cercle centré au sommet et une droite perpendiculaire à la directrice.", reponse: false, justification: "Le cercle est centré au FOYER, et la droite est PARALLÈLE à la directrice, pas perpendiculaire." },
  { enonce: "Le rayon du cercle utilisé peut être n'importe quelle valeur positive, même très petite.", reponse: false, justification: "Le rayon doit respecter la contrainte stricte r>distance(F,d)/2, pas n'importe quelle valeur." },
  { enonce: "Les points d'intersection entre le cercle et la droite parallèle à la directrice ne sont jamais des points de la parabole.", reponse: false, justification: "Ce sont justement TOUJOURS des points de la parabole, par construction même de la méthode." },
  { enonce: "Un point de la parabole est toujours plus proche du foyer que de la directrice.", reponse: false, justification: "Un point de la parabole est à égale distance du foyer ET de la directrice, jamais plus proche de l'un." },
  { enonce: "Dans cette construction, la directrice est toujours représentée horizontalement ou verticalement à l'écran.", reponse: false, justification: "La directrice est au contraire toujours représentée OBLIQUEMENT, jamais horizontalement ni verticalement." },
  { enonce: "La courbe finale de la parabole est obtenue en reliant les points construits par des segments droits.", reponse: false, justification: "Elle est obtenue par interpolation parabolique progressive, jamais par des segments droits." },
  { enonce: "Si le rayon choisi est trop petit, le cercle coupe quand même toujours la droite parallèle à la directrice.", reponse: false, justification: "Si le rayon est trop petit, le cercle ne coupe justement PAS la droite." },
  { enonce: "La droite parallèle à la directrice doit être tracée du côté opposé au foyer.", reponse: false, justification: "Elle doit être tracée du même côté que le foyer, pas du côté opposé." },
  { enonce: "Chaque itération de la construction ne peut produire qu'un seul point de la parabole, jamais deux.", reponse: false, justification: "Un cercle et une droite sécants se coupent généralement en deux points, pas un seul." },
  { enonce: "Si le rayon du cercle est choisi exactement égal à la moitié de la distance foyer-directrice, le cercle est tangent à la droite parallèle à la directrice (un seul point).", reponse: true, justification: "C'est le cas limite : la distance du foyer à cette droite égale alors le rayon, d'où tangence." },
  { enonce: "Augmenter le rayon du cercle (au-delà du minimum requis) permet d'obtenir des points de la parabole plus éloignés du sommet.", reponse: true, justification: "Un rayon plus grand éloigne le point d'intersection de l'axe, donc du sommet, le long de la courbe." },
  { enonce: "La distance entre le foyer et la directrice est une valeur fixe, indépendante du rayon choisi pour la construction.", reponse: true, justification: "Cette distance est déterminée par la parabole elle-même (par |p|), pas par les choix faits pendant la construction." },
  { enonce: "Pour un même rayon choisi, tracer la droite parallèle à la directrice à des distances différentes du foyer donne à chaque fois de nouveaux points.", reponse: true, justification: "Chaque nouvelle position de la droite parallèle change les points d'intersection avec le cercle." },
  { enonce: "La construction repose sur la définition même de la parabole comme lieu des points équidistants d'un foyer et d'une directrice.", reponse: true, justification: "C'est exactement cette propriété qui garantit que les points construits appartiennent à la parabole." },
  { enonce: "Si l'on choisit un rayon égal à la distance foyer-directrice entière (et non sa moitié), le cercle coupe quand même la droite parallèle à la directrice en 2 points.", reponse: true, justification: "La distance entière est supérieure à sa moitié : la contrainte r>distance/2 reste respectée." },
  { enonce: "La méthode ne permet théoriquement de construire qu'un nombre fini de points à chaque fois, jamais la totalité de la courbe continue en une seule fois.", reponse: true, justification: "Chaque itération (cercle + droite) donne des points discrets ; la courbe continue est obtenue par interpolation." },
  { enonce: "Le sommet de la parabole peut lui-même être obtenu par cette construction, avec un rayon égal à la moitié de la distance foyer-directrice (cas limite de tangence).", reponse: true, justification: "Dans ce cas limite, le point de tangence est précisément le sommet de la parabole." },
  { enonce: "Si le rayon du cercle est choisi exactement égal à la moitié de la distance foyer-directrice, le cercle coupe la droite en 2 points distincts.", reponse: false, justification: "C'est le cas limite de tangence : un seul point, pas deux." },
  { enonce: "Augmenter le rayon du cercle donne toujours des points plus proches du sommet.", reponse: false, justification: "C'est l'inverse : un rayon plus grand donne des points plus ÉLOIGNÉS du sommet." },
  { enonce: "La distance entre le foyer et la directrice dépend du rayon choisi lors de la construction.", reponse: false, justification: "Cette distance est fixée par la parabole elle-même, indépendamment des choix faits pendant la construction." },
  { enonce: "Pour un même rayon choisi, toutes les positions de la droite parallèle à la directrice donnent exactement les deux mêmes points.", reponse: false, justification: "Chaque position différente de la droite donne en général des points d'intersection différents." },
  { enonce: "La construction ne repose pas sur la définition de la parabole comme lieu de points équidistants, mais sur une autre propriété.", reponse: false, justification: "C'est précisément cette définition (équidistance foyer-directrice) qui fonde la méthode." },
  { enonce: "Si l'on choisit un rayon égal à la distance foyer-directrice entière, le cercle ne coupe jamais la droite parallèle à la directrice.", reponse: false, justification: "Ce rayon, supérieur à la moitié requise, garantit au contraire une intersection en 2 points." },
  { enonce: "Cette méthode de construction permet d'obtenir directement la courbe continue complète de la parabole, sans interpolation ni approximation.", reponse: false, justification: "Elle ne donne que des points discrets, reliés ensuite par interpolation progressive." },
];

const LIEUX_GEOMETRIQUES: QuestionVraiFaux[] = [
  { enonce: "Un lieu géométrique décrit par « les points équidistants d'un point fixe » est un cercle.", reponse: true, justification: "C'est la définition même d'un cercle : l'ensemble des points à distance constante d'un centre." },
  { enonce: "Un lieu géométrique décrit par « les points équidistants d'un point fixe et d'une droite fixe » est une parabole.", reponse: true, justification: "C'est la définition même d'une parabole (foyer et directrice)." },
  { enonce: "Un lieu géométrique décrit par une relation linéaire entre l'abscisse et l'ordonnée (par exemple, l'ordonnée est le triple de l'abscisse) est une droite.", reponse: true, justification: "Une relation du type y=3x décrit exactement une droite passant par l'origine." },
  { enonce: "L'intersection entre un cercle et une droite peut compter 0, 1 ou 2 points.", reponse: true, justification: "Selon la position relative : sécante (2 points), tangente (1 point), ou extérieure (0 point)." },
  { enonce: "Une droite tangente à un cercle le coupe en exactement 1 point.", reponse: true, justification: "C'est la définition même de la tangence : un unique point de contact." },
  { enonce: "Deux cercles peuvent avoir 0, 1 ou 2 points d'intersection selon leur position relative.", reponse: true, justification: "Selon que les cercles sont disjoints, tangents, ou sécants." },
  { enonce: "Une droite et une parabole peuvent avoir 0, 1 ou 2 points d'intersection.", reponse: true, justification: "Une droite peut couper une parabole en 0, 1 (tangente ou parallèle à l'axe) ou 2 points." },
  { enonce: "Pour résoudre un système droite-cercle, on substitue l'équation de la droite dans celle du cercle, obtenant une équation du second degré.", reponse: true, justification: "La substitution fait apparaître une équation quadratique en une seule variable (ou en t, le paramètre)." },
  { enonce: "Le nombre de solutions réelles de l'équation obtenue par substitution donne le nombre de points d'intersection.", reponse: true, justification: "Chaque solution réelle correspond à un point d'intersection réel." },
  { enonce: "« Les points situés à une distance de 5 unités du point (2;-3) » décrit un cercle de centre (2;-3) et de rayon 5.", reponse: true, justification: "C'est exactement la définition d'un cercle de centre (2;-3) et de rayon 5." },
  { enonce: "Un lieu géométrique décrit par « les points équidistants d'un point fixe » est une droite.", reponse: false, justification: "C'est un CERCLE (ensemble des points à distance constante d'un centre), pas une droite." },
  { enonce: "Un lieu géométrique décrit par « les points équidistants d'un point fixe et d'une droite fixe » est un cercle.", reponse: false, justification: "C'est une PARABOLE (foyer et directrice), pas un cercle." },
  { enonce: "Un lieu géométrique décrit par une relation linéaire entre l'abscisse et l'ordonnée est toujours un cercle.", reponse: false, justification: "Une relation linéaire décrit toujours une DROITE, jamais un cercle." },
  { enonce: "L'intersection entre un cercle et une droite peut compter jusqu'à 4 points.", reponse: false, justification: "Une droite étant du premier degré, elle coupe un cercle en au plus 2 points, jamais 4." },
  { enonce: "Une droite tangente à un cercle le coupe toujours en 2 points.", reponse: false, justification: "Une tangente touche le cercle en exactement 1 point, pas 2 (2 points correspond à une sécante)." },
  { enonce: "Deux cercles ont toujours exactement 2 points d'intersection, quelle que soit leur position relative.", reponse: false, justification: "Deux cercles peuvent aussi être tangents (1 point) ou disjoints (0 point)." },
  { enonce: "Une droite et une parabole ont toujours exactement 1 point d'intersection.", reponse: false, justification: "Elles peuvent aussi n'avoir aucun point commun, ou en avoir deux." },
  { enonce: "Pour résoudre un système droite-cercle, on ne peut jamais se ramener à une équation du second degré.", reponse: false, justification: "La substitution mène justement toujours à une équation du second degré." },
  { enonce: "Le nombre de solutions réelles de l'équation obtenue par substitution est toujours égal à 2, quel que soit le cas.", reponse: false, justification: "Ce nombre peut aussi valoir 0 (aucune solution réelle) ou 1 (racine double, tangence)." },
  { enonce: "« Les points situés à une distance de 5 unités du point (2;-3) » décrit une droite passant par (2;-3).", reponse: false, justification: "Cette description est celle d'un CERCLE de centre (2;-3) et de rayon 5, pas d'une droite." },
  { enonce: "Un lieu géométrique décrit par « les points dont l'ordonnée est le carré de l'abscisse » (y=x²) est une parabole.", reponse: true, justification: "C'est la définition analytique standard d'une parabole d'axe vertical passant par l'origine." },
  { enonce: "« Les points équidistants de deux points fixes A et B » forment la médiatrice du segment [AB], une droite.", reponse: true, justification: "C'est la définition même de la médiatrice d'un segment." },
  { enonce: "L'intersection entre une droite et une autre droite (non confondues) peut compter 0 ou 1 point, jamais plus.", reponse: true, justification: "Deux droites distinctes sont soit parallèles (0 point), soit sécantes (exactement 1 point)." },
  { enonce: "Une droite tangente à une parabole la touche en exactement 1 point.", reponse: true, justification: "C'est la définition même de la tangence : un unique point de contact." },
  { enonce: "Pour trouver les points d'intersection de deux cercles, soustraire membre à membre leurs équations développées donne l'équation d'une droite (l'axe radical).", reponse: true, justification: "La soustraction élimine les termes en x² et en y², ne laissant qu'une équation du premier degré." },
  { enonce: "« Les points situés à distance égale des axes Ox et Oy » décrivent deux droites : y=x et y=-x.", reponse: true, justification: "L'égalité |x|=|y| se décompose en y=x (mêmes signes) et y=-x (signes opposés)." },
  { enonce: "Le discriminant de l'équation du second degré obtenue par substitution permet de déterminer le nombre de points d'intersection : positif (2 points), nul (1 point), négatif (0 point).", reponse: true, justification: "C'est le résultat standard reliant le signe du discriminant au nombre de racines réelles." },
  { enonce: "Une parabole et un cercle peuvent avoir jusqu'à 4 points d'intersection.", reponse: true, justification: "La substitution mène à une équation de degré 4, qui peut avoir jusqu'à 4 racines réelles." },
  { enonce: "Un lieu géométrique décrit par « les points dont l'ordonnée est le carré de l'abscisse » (y=x²) est une droite.", reponse: false, justification: "C'est une PARABOLE (relation quadratique entre x et y), jamais une droite." },
  { enonce: "« Les points équidistants de deux points fixes A et B » forment un cercle centré au milieu de [AB].", reponse: false, justification: "C'est la MÉDIATRICE de [AB] (une droite), pas un cercle." },
  { enonce: "L'intersection de deux droites distinctes peut compter 0, 1 ou 2 points selon les cas.", reponse: false, justification: "Deux droites distinctes ont 0 point (parallèles) ou exactement 1 point (sécantes), jamais 2." },
  { enonce: "Une droite tangente à une parabole peut la toucher en 2 points distincts.", reponse: false, justification: "La tangence signifie par définition exactement 1 point de contact, pas 2." },
  { enonce: "Pour trouver les points d'intersection de deux cercles, soustraire leurs équations développées donne une nouvelle équation de cercle.", reponse: false, justification: "La soustraction élimine les termes en x² et y² : le résultat est l'équation d'une DROITE, pas d'un cercle." },
  { enonce: "« Les points situés à distance égale des axes Ox et Oy » décrivent un unique cercle centré à l'origine.", reponse: false, justification: "Ce sont deux DROITES (y=x et y=-x), pas un cercle." },
  { enonce: "Une parabole et un cercle ne peuvent jamais avoir plus de 2 points d'intersection.", reponse: false, justification: "Ils peuvent en avoir jusqu'à 4 (l'équation obtenue par substitution est de degré 4)." },
];

export const BANQUE_QUIZ_GEOMETRIE_ANALYTIQUE: Record<VarianteQuizGeometrieAnalytique, QuestionVraiFaux[]> = {
  equationDroite: EQUATION_DROITE,
  lectureGraphiqueDroite: LECTURE_GRAPHIQUE_DROITE,
  constructionDroite: CONSTRUCTION_DROITE,
  relationsDroites: RELATIONS_DROITES,
  caracteristiquesDroite: CARACTERISTIQUES_DROITE,
  distancePointDroite: DISTANCE_POINT_DROITE,
  intersectionDroites: INTERSECTION_DROITES,
  equationCercleGraphe: EQUATION_CERCLE_GRAPHE,
  centreRayonCercle: CENTRE_RAYON_CERCLE,
  equationParaboleGraphe: EQUATION_PARABOLE_GRAPHE,
  sommetFoyerParabole: SOMMET_FOYER_PARABOLE,
  constructionParabole: CONSTRUCTION_PARABOLE,
  lieuxGeometriques: LIEUX_GEOMETRIQUES,
};
